<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Interactive Session</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../course-materials/assets/css/exercises.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">EDS 217</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">🏠 home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-daily-materials" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">🗓️ daily materials</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-daily-materials">    
        <li>
    <a class="dropdown-item" href="../../course-materials/day1.html">
 <span class="dropdown-text">1️⃣ Day 1 (8/31)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day2.html">
 <span class="dropdown-text">2️⃣ Day 2 (9/1)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day3.html">
 <span class="dropdown-text">3️⃣ Day 3 (9/2)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day4.html">
 <span class="dropdown-text">4️⃣ Day 4 (9/3)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day5.html">
 <span class="dropdown-text">5️⃣ Day 5 (9/4)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day6.html">
 <span class="dropdown-text">6️⃣ Day 6 (9/8)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day7.html">
 <span class="dropdown-text">7️⃣ Day 7 (9/9)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day8.html">
 <span class="dropdown-text">8️⃣ Day 8 (9/10)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day9.html">
 <span class="dropdown-text">9️⃣ Day 9 (9/11)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-interactive-sessions" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">💻 interactive sessions</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-interactive-sessions">    
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1a_positron_notebooks.html">
 <span class="dropdown-text">Session 1a - ⚒️ Positron &amp; Jupyter Notebooks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1b_python_essentials.html">
 <span class="dropdown-text">Session 1b - 🐍 Python Essentials</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1c_data_science_workflow_1.html">
 <span class="dropdown-text">Session 1c - 🎬 The Python Data Science Workflow, Part 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1d_data_science_workflow_2.html">
 <span class="dropdown-text">Session 1d - 🎬 The Python Data Science Workflow, Part 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/2a_reading_data.html">
 <span class="dropdown-text">Session 2a - 🐼 Reading Data into pandas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/2b_exploring_data.html">
 <span class="dropdown-text">Session 2b - 🔎 Exploring a DataFrame</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/2d_lists_and_dicts.html">
 <span class="dropdown-text">Session 2d - 📝 Lists &amp; Dictionaries</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/3a_booleans_and_conditionals.html">
 <span class="dropdown-text">Session 3a - 📝 Booleans &amp; Conditionals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/3b_filtering_data.html">
 <span class="dropdown-text">Session 3b - 🔍 The Filter Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/3c_sorting_and_ranking.html">
 <span class="dropdown-text">Session 3c - 🥇 The Top-N Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4a_cleaning_data.html">
 <span class="dropdown-text">Session 4a - 🧼 Missing, Duplicated, Miscast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4b_functions.html">
 <span class="dropdown-text">Session 4b - ⚙️ Write It Once, Name It, Use It</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4c_transforming_data.html">
 <span class="dropdown-text">Session 4c - ➕ The Derived-Column Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/5a_grouping_data.html">
 <span class="dropdown-text">Session 5a - 🗂️ The Split-Apply-Combine Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/5b_aggregating_data.html">
 <span class="dropdown-text">Session 5b - 📊 Several Answers at Once</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/5d_loops_over_groups.html">
 <span class="dropdown-text">Session 5d - 🔁 When a Pattern Is Not Enough</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6a_joining_data.html">
 <span class="dropdown-text">Session 6a - 🔗 The Join Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6b_reshaping_data.html">
 <span class="dropdown-text">Session 6b - 🧩 Long and Wide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6c_dates.html">
 <span class="dropdown-text">Session 6c - 📆 A Date Is Not a Number</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7a_matplotlib.html">
 <span class="dropdown-text">Session 7a - 🖼️ The Anatomy of a Figure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7b_seaborn.html">
 <span class="dropdown-text">Session 7b - 🎨 Name the Columns, Not the Colours</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7d_project_kickoff.html">
 <span class="dropdown-text">Session 7d - 🚀 Project Kickoff</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-coding-colabs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">🙌 coding colabs</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-coding-colabs">    
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/2c_exploring_unfamiliar_data.html">
 <span class="dropdown-text">🙌 Session 2c - Five Claims About a Dataset You’ve Never Seen</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/3d_ranking_questions.html">
 <span class="dropdown-text">🙌 Session 3d - Which One, and How Do You Know?</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/4d_cleaning_messy_data.html">
 <span class="dropdown-text">🙌 Session 4d - From Field Sheet to DataFrame</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/5c_grouped_comparisons.html">
 <span class="dropdown-text">🙌 Session 5c - The Comparison You Made Yesterday, Properly</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/6d_two_table_exercise.html">
 <span class="dropdown-text">🙌 Session 6d - Two Records, Sixty-Six Years Apart</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/7c_penguins.html">
 <span class="dropdown-text">🙌 Session 7c - One Cloud of Points, Three Species</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../cheatsheets.html"> 
<span class="menu-text">👀 cheatsheets</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-resources" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">📚 resources</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-resources">    
        <li>
    <a class="dropdown-item" href="https://docs.python.org/3/" target="_blank">
 <span class="dropdown-text">📚 Python Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pandas.pydata.org/docs/" target="_blank">
 <span class="dropdown-text">📚 Pandas Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://numpy.org/doc/stable/" target="_blank">
 <span class="dropdown-text">📚 Numpy Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://matplotlib.org/stable/contents.html" target="_blank">
 <span class="dropdown-text">📚 Matplotlib Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://seaborn.pydata.org/" target="_blank">
 <span class="dropdown-text">📚 Seaborn Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://positron.posit.co/" target="_blank">
 <span class="dropdown-text">📚 Positron Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://docs.anaconda.com/" target="_blank">
 <span class="dropdown-text">📚 Anaconda Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://stackoverflow.com/" target="_blank">
 <span class="dropdown-text">📚 Stack Overflow</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://realpython.com/" target="_blank">
 <span class="dropdown-text">📚 Real Python</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://towardsdatascience.com/" target="_blank">
 <span class="dropdown-text">📚 Towards Data Science</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.datacamp.com/" target="_blank">
 <span class="dropdown-text">📚 DataCamp</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.kaggle.com/" target="_blank">
 <span class="dropdown-text">📚 Kaggle</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="http://pythontutor.com/" target="_blank">
 <span class="dropdown-text">🧰 Python Tutor</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pandastutor.com/vis.html#" target="_blank">
 <span class="dropdown-text">🧰 Pandas Tutor</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://wesmckinney.com/book/" target="_blank">
 <span class="dropdown-text">📙 Python for Data Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://jakevdp.github.io/PythonDataScienceHandbook/" target="_blank">
 <span class="dropdown-text">📙 Python for Data Science Handbook</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/jakevdp/PythonDataScienceHandbook" target="_blank">
 <span class="dropdown-text">📙 Python Data Science Handbook (GitHub)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://talkpython.fm/" target="_blank">
 <span class="dropdown-text">📻 Talk Python to Me</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/EDS-217-Essential-Python/EDS-217-Essential-Python.github.io" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-left">
      <h1 class="title">Interactive Session</h1>
            <p class="subtitle lead">🔗 The Join Pattern</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta column-page-left">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link active" data-scroll-target="#getting-started">Getting Started</a></li>
  <li><a href="#two-tables-out-of-one" id="toc-two-tables-out-of-one" class="nav-link" data-scroll-target="#two-tables-out-of-one">Two tables out of one</a></li>
  <li><a href="#the-join-pattern" id="toc-the-join-pattern" class="nav-link" data-scroll-target="#the-join-pattern">The join pattern</a></li>
  <li><a href="#merging-as-an-application-of-set-theory" id="toc-merging-as-an-application-of-set-theory" class="nav-link" data-scroll-target="#merging-as-an-application-of-set-theory">Merging as an application of set theory:</a></li>
  <li><a href="#practical-merging-of-dataframes" id="toc-practical-merging-of-dataframes" class="nav-link" data-scroll-target="#practical-merging-of-dataframes">Practical merging of DataFrames:</a></li>
  <li><a href="#the-first-question-to-ask-a-merge" id="toc-the-first-question-to-ask-a-merge" class="nav-link" data-scroll-target="#the-first-question-to-ask-a-merge">The first question to ask a merge</a></li>
  <li><a href="#keeping-everything-on-one-side" id="toc-keeping-everything-on-one-side" class="nav-link" data-scroll-target="#keeping-everything-on-one-side">Keeping everything on one side</a></li>
  <li><a href="#the-rows-you-lose-are-not-a-random-sample" id="toc-the-rows-you-lose-are-not-a-random-sample" class="nav-link" data-scroll-target="#the-rows-you-lose-are-not-a-random-sample">The rows you lose are not a random sample</a></li>
  <li><a href="#what-a-joined-table-is-for" id="toc-what-a-joined-table-is-for" class="nav-link" data-scroll-target="#what-a-joined-table-is-for">What a joined table is for</a></li>
  <li><a href="#when-the-key-columns-have-different-names" id="toc-when-the-key-columns-have-different-names" class="nav-link" data-scroll-target="#when-the-key-columns-have-different-names">When the key columns have different names</a></li>
  <li><a href="#the-merge-that-quietly-lost-something" id="toc-the-merge-that-quietly-lost-something" class="nav-link" data-scroll-target="#the-merge-that-quietly-lost-something">The merge that quietly lost something</a></li>
  <li><a href="#key-points" id="toc-key-points" class="nav-link" data-scroll-target="#key-points">Key points</a></li>
  <li><a href="#resources" id="toc-resources" class="nav-link" data-scroll-target="#resources">Resources</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block column-page-left" id="quarto-document-content">





<div style="width: 80%; margin: auto;">
<p><img src="../images/joining_panda.jpeg" class="img-fluid"></p>
</div>
<div class="gray-text center-text">
<p><em>A panda, matching two halves along the seam.</em> <a href="https://www.midjourney.com/jobs/e4667ea9-82c4-4239-a6b8-9b32e7e22005?index=3">MidJourney 5</a></p>
</div>
<p>On Friday we asked whether ozone and particulate matter follow the same daily cycle, and we answered it the only way one table allows: we grouped ozone by hour, we grouped PM2.5 by hour, we printed both, and we compared them by eye. Two answers, side by side on the screen, but never side by side in the data.</p>
<p>Comparing by eye is fine for two columns of twenty-four numbers. It stops working the moment you want to ask anything that needs both measurements <strong>in the same row</strong>: was the smoky hour also the ozone hour? Does high PM2.5 predict high ozone three hours later? What is the correlation between them?</p>
<p>To ask any of those questions, the two measurements have to sit in the same table. This morning we will learn the pandas code patterns that allow you to join data together.</p>
<p>By the end of this session you will be able to:</p>
<ul>
<li>write the <strong>join pattern</strong>, <code>pd.merge(left, right, on='key')</code>, and explain what the <strong>key</strong> does</li>
<li>choose between <code>how='inner'</code> and <code>how='left'</code>, and explain what each one does to your row count</li>
<li>check a merge after you run it, and know which numbers to compare to ensure things have gone according to plan</li>
<li>join two tables whose key columns have <strong>different names</strong>, using <code>left_on=</code> and <code>right_on=</code></li>
<li>explain why the rows a join drops are rarely a random sample of your data</li>
</ul>
<section id="getting-started" class="level2">
<h2 class="anchored" data-anchor-id="getting-started">Getting Started</h2>
<ol type="1">
<li><p><strong>Create the file.</strong> In the Explorer, hover over the <strong>EDS217</strong> heading and click <strong>New File…</strong>, then type the name in full, extension included: <code>Session_6A_Joining_Data.ipynb</code></p></li>
<li><p><strong>Check the kernel.</strong> The Kernel Selector in the notebook’s action bar should read <strong>Python 3.11.15 (Conda: eds217)</strong>. If it reads anything else, click it, choose <strong>Change Kernel</strong>, and pick the eds217 entry.</p></li>
<li><p><strong>Add a title cell.</strong> Click <strong>+ Markdown</strong> in the action bar, and give it this content, with today’s date:</p></li>
</ol>
<div class="sourceCode" id="cb1"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Day 6: Session 6A - The Join Pattern</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Session Webpage</span><span class="co">](https://eds-217-essential-python.github.io/course-materials/interactive-sessions/6a_joining_data.html)</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>Date: 09/08/2026</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol start="4" type="1">
<li><p><strong>Save</strong> with <code>Ctrl + S</code> (<code>Cmd + S</code> on macOS), and keep saving as you go.</p></li>
<li><p>Read in the Goleta air quality file, which you have now met twice:</p></li>
</ol>
<div id="9ae884ee" class="cell" data-execution_count="1">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="st">'https://eds-217-essential-python.github.io/data/openaq_goleta_measurments.csv'</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>goleta <span class="op">=</span> pd.read_csv(url)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>goleta[<span class="st">'parameter'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>parameter
pm25    734
o3      711
pm10    517
Name: count, dtype: int64</code></pre>
</div>
</div>
<p>Here is our Goleta air quality file, which we now know contains three parameters and 1,962 rows. Every row is one measurement of one pollutant at one hour.</p>
</section>
<section id="two-tables-out-of-one" class="level2">
<h2 class="anchored" data-anchor-id="two-tables-out-of-one">Two tables out of one</h2>
<p>Before we can join two tables we need two tables, so we will start by making them. Both lines below are Wednesday’s filter pattern, and nothing else:</p>
<div id="312f289a" class="cell" data-execution_count="2">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>o3 <span class="op">=</span> goleta[goleta[<span class="st">'parameter'</span>] <span class="op">==</span> <span class="st">'o3'</span>].copy()</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>pm25 <span class="op">=</span> goleta[goleta[<span class="st">'parameter'</span>] <span class="op">==</span> <span class="st">'pm25'</span>].copy()</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(o3.shape)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pm25.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(711, 15)
(734, 15)</code></pre>
</div>
</div>
<p>Now we have 711 hours of ozone and 734 hours of PM2.5. The two instruments did not record the same number of hours, which is important! A gap like that usually says something about how the data was (or was not) collected.</p>
<p>Each new table has fifteen columns, and twelve of them hold the same value in every row. Keep only the two columns that matter, and give the measurement column a name that says what it is. One method per line, the way we learned last Thursday:</p>
<div id="f3d7de6b" class="cell" data-execution_count="3">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>o3 <span class="op">=</span> o3[[<span class="st">'datetimeLocal'</span>, <span class="st">'value'</span>]]</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>o3 <span class="op">=</span> o3.rename(columns<span class="op">=</span>{<span class="st">'value'</span>: <span class="st">'o3_ppm'</span>})</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>pm25 <span class="op">=</span> pm25[[<span class="st">'datetimeLocal'</span>, <span class="st">'value'</span>]]</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>pm25 <span class="op">=</span> pm25.rename(columns<span class="op">=</span>{<span class="st">'value'</span>: <span class="st">'pm25_ugm3'</span>})</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>o3.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">datetimeLocal</th>
<th data-quarto-table-cell-role="th">o3_ppm</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2024-07-11T18:00:00-07:00</td>
<td>0.025</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2024-07-11T19:00:00-07:00</td>
<td>0.028</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2024-07-11T20:00:00-07:00</td>
<td>0.029</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2024-07-11T21:00:00-07:00</td>
<td>0.027</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2024-07-11T22:00:00-07:00</td>
<td>0.026</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>🐍 Renaming before a join is not just cosmetic. If both tables arrive at the join with a column called <code>value</code>, pandas cannot keep them both under that name, so it renames them <code>value_x</code> and <code>value_y</code> and leaves you to work out which is which. Naming your columns first costs you two lines now, but saves a lot of headache later…</p>
</div>
</div>
</section>
<section id="the-join-pattern" class="level2">
<h2 class="anchored" data-anchor-id="the-join-pattern">The join pattern</h2>
<p>We have two tables (DataFrames) with one column in common: <code>datetimeLocal</code>, the hour the reading was taken. This shared column is the <strong>key</strong>, and a merge (or join) is the operation that lines the two tables up by it.</p>
<p>The way we “join” these two DataFrames is using the <code>pd.merge()</code> function.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>🐍 Are we joining or merging?</p>
<p>We use <code>pd.merge()</code> as the general-purpose command for combining two datasets on a shared key. The name comes from the statistical computing tradition: base R has a <code>merge()</code> function, and SAS uses <code>MERGE</code> in its data steps, so <code>merge</code> was the familiar verb for the audience pandas was written for. There is also a <code>DataFrame.join()</code> method in pandas, which combines two datasets on their <em>index</em> and which is now essentially a convenience wrapper around the same machinery as <code>merge</code> (we’ve seen that happen before in things like <code>.value_counts()</code>). But while the name follows R and SAS, the semantics follow SQL: the <code>how=</code> argument takes <code>inner</code>, <code>outer</code>, <code>left</code>, and <code>right</code>, which are the SQL join types. So the command we use to join datasets is itself a merged version of syntax from different languages… 🤖 🤯 Computers 🤯 🤖!!</p>
</div>
</div>
</section>
<section id="merging-as-an-application-of-set-theory" class="level2">
<h2 class="anchored" data-anchor-id="merging-as-an-application-of-set-theory">Merging as an application of set theory:</h2>
<div style="width: 95%; margin: auto;">
<p><img src="../images/join_types_venn.svg" class="img-fluid"></p>
</div>
<div class="gray-text center-text">
<p><em>The same two tables, joined four ways.</em></p>
</div>
<p>The <code>left</code> table has the keys k0, k1 and k2, plus a column <code>A</code>. The <code>right</code> table has k1, k2 and k3, plus a column <code>B</code>. The two tables agree in the middle and disagree at each end, which is the situation most real joins are in. Each panel shades the part of the two key sets that one <code>how=</code> keeps, and prints the table we get back.</p>
<p>Read the four results against each other. <code>inner</code> returns two rows and drops k0 and k3, because neither of those keys is in both tables. <code>left</code> returns three rows: every key from the left table, with <code>NaN</code> in column <code>B</code> at k0, where the right table has no matching row. <code>right</code> is the mirror of it, with <code>NaN</code> in column <code>A</code> at k3. <code>outer</code> returns all four keys and fills in <code>NaN</code> on both sides. The same two tables give us two, three, three and four rows, and the only thing we changed between the four panels is the value of <code>how=</code>!</p>
</section>
<section id="practical-merging-of-dataframes" class="level2">
<h2 class="anchored" data-anchor-id="practical-merging-of-dataframes">Practical merging of DataFrames:</h2>
<div style="width: 95%; margin: auto;">
<p><img src="../images/join_types_keyaxis.svg" class="img-fluid"></p>
</div>
<div class="gray-text center-text">
<p><em>The same four joins, on tables long enough to have gaps in them.</em></p>
</div>
<p>A three-row table keeps the arithmetic easy to follow, but the files we merge in practice are longer than that and their keys line up much less tidily. In the second figure, <code>df1</code> and <code>df2</code> are drawn against a shared key axis running down the page, so every row sits at the position of its own key, and a missing key shows up as a gap in the column rather than as a number you would have to go and count. Neither table covers the whole axis, and the stretches they are missing are not the same stretches.</p>
<p>The colours show where each part of a row came from: blue marks a key that is present in the result, green a value taken from <code>df1</code>, orange a value taken from <code>df2</code>, and a pale outlined box a <code>NaN</code>, where the key matched on one side only. <code>inner</code> keeps only the keys that both tables cover, so its column is the shortest one in the figure. <code>outer</code> keeps every key that either table covers, so its column is the longest, and the price of those extra rows is a gap wherever only one of the two tables had a value. <code>left</code> and <code>right</code> each keep one table’s keys intact and fill in from the other table wherever a key matches.</p>
<p>Compare the two figures before you go on. The first figure tells us what each <code>how=</code> keeps, and the second tells us what each one costs in rows and in <code>NaN</code> values, which is worth checking on your own data before you trust a merged table.</p>
<div id="d09ee34d" class="cell" data-execution_count="4">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>paired <span class="op">=</span> pd.merge(o3, pm25, on<span class="op">=</span><span class="st">'datetimeLocal'</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>paired.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">datetimeLocal</th>
<th data-quarto-table-cell-role="th">o3_ppm</th>
<th data-quarto-table-cell-role="th">pm25_ugm3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2024-07-11T18:00:00-07:00</td>
<td>0.025</td>
<td>3.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2024-07-11T19:00:00-07:00</td>
<td>0.028</td>
<td>8.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2024-07-11T20:00:00-07:00</td>
<td>0.029</td>
<td>6.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2024-07-11T21:00:00-07:00</td>
<td>0.027</td>
<td>4.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2024-07-11T22:00:00-07:00</td>
<td>0.026</td>
<td>9.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Read it left to right as three instructions:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>pd.merge(left, right, on<span class="op">=</span><span class="st">'key'</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co">#        ↑     ↑         ↑</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co">#        the two tables  the column they have in common</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ul>
<li>the <strong>first two arguments</strong> are the tables, in order. The first is the <em>left</em> table and the second is the <em>right</em> one, and those two labels decide which rows survive when the two tables do not line up exactly.</li>
<li><code>on=</code> names the column that both tables share. Pandas looks up every value of the left table’s key in the right table’s key, and glues the matching rows together end to end.</li>
</ul>
<p>The result has one row for every hour that appears in <strong>both</strong> tables, and the columns of both. For the first time in this course, one row of your data holds two different measurements!</p>
<div id="e920ceb2" class="cell" data-execution_count="5">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>paired.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>(704, 3)</code></pre>
</div>
</div>
</section>
<section id="the-first-question-to-ask-a-merge" class="level2">
<h2 class="anchored" data-anchor-id="the-first-question-to-ask-a-merge">The first question to ask a merge</h2>
<p>We now have 704 rows. We started with 711 hours of ozone and 734 hours of PM2.5.</p>
<p><strong>Where did the other rows go?</strong></p>
<p>You will want to ask that question every single time you merge two tables, because nothing in pandas checks the row count for you. A merge that discards a third of your data looks exactly like a merge that discards nothing.</p>
<p>By default, <code>pd.merge()</code> keeps only the rows whose key appears in <strong>both</strong> tables. The default has a name, and you should write it out:</p>
<div id="f004ddeb" class="cell" data-execution_count="6">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>inner <span class="op">=</span> pd.merge(o3, pm25, on<span class="op">=</span><span class="st">'datetimeLocal'</span>, how<span class="op">=</span><span class="st">'inner'</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>inner.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>(704, 3)</code></pre>
</div>
</div>
<p>Same 704 rows: <code>how='inner'</code> is the merge we already ran, written out in full.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>🐍 An <strong>inner</strong> join keeps the intersection of the two key sets. If you have seen a Venn diagram, this is the lens in the middle:</p>
<p><img src="../images/intersection.jpg" class="img-fluid"></p>
<p>Circle A is the hours ozone was recorded, circle B is the hours PM2.5 was recorded, and an inner join keeps the shaded part.</p>
</div>
</div>
</section>
<section id="keeping-everything-on-one-side" class="level2">
<h2 class="anchored" data-anchor-id="keeping-everything-on-one-side">Keeping everything on one side</h2>
<p>Very often you do not want the intersection. You have a table you care about, and a second table of extra information you would like to attach <strong>where it exists</strong>, without losing rows where it does not.</p>
<p><code>how='left'</code> does exactly that: keep every row of the left table, attach the right table where the key matches, and fill in nulls where it does not.</p>
<div id="999270f5" class="cell" data-execution_count="7">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>left <span class="op">=</span> pd.merge(o3, pm25, on<span class="op">=</span><span class="st">'datetimeLocal'</span>, how<span class="op">=</span><span class="st">'left'</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>left.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>(711, 3)</code></pre>
</div>
</div>
<p>All 711 ozone hours survive. Seven of them have no PM2.5 reading to attach, and we find those seven with the help of our good friend <code>isnull()</code>:</p>
<div id="8200e7a1" class="cell" data-execution_count="8">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>left.isnull().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>datetimeLocal    0
o3_ppm           0
pm25_ugm3        7
dtype: int64</code></pre>
</div>
</div>
<p><code>how='right'</code> does the mirror image, keeping every row of the right table:</p>
<div id="85aa51ff" class="cell" data-execution_count="9">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>right <span class="op">=</span> pd.merge(o3, pm25, on<span class="op">=</span><span class="st">'datetimeLocal'</span>, how<span class="op">=</span><span class="st">'right'</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(right.shape)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(right.isnull().<span class="bu">sum</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(734, 3)
datetimeLocal     0
o3_ppm           30
pm25_ugm3         0
dtype: int64</code></pre>
</div>
</div>
<p>And <code>how='outer'</code> keeps everything from both sides, filling nulls in both directions:</p>
<div id="7364ed84" class="cell" data-execution_count="10">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>outer <span class="op">=</span> pd.merge(o3, pm25, on<span class="op">=</span><span class="st">'datetimeLocal'</span>, how<span class="op">=</span><span class="st">'outer'</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(outer.shape)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(outer.isnull().<span class="bu">sum</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(741, 3)
datetimeLocal     0
o3_ppm           30
pm25_ugm3         7
dtype: int64</code></pre>
</div>
</div>
<table class="table-hover table-bordered caption-top table">
<thead>
<tr class="header">
<th><code>how=</code></th>
<th>Keeps</th>
<th>Rows here</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>'inner'</code> (default)</td>
<td>keys in <strong>both</strong> tables</td>
<td>704</td>
</tr>
<tr class="even">
<td><code>'left'</code></td>
<td>every row of the <strong>left</strong> table</td>
<td>711</td>
</tr>
<tr class="odd">
<td><code>'right'</code></td>
<td>every row of the <strong>right</strong> table</td>
<td>734</td>
</tr>
<tr class="even">
<td><code>'outer'</code></td>
<td>every row of <strong>either</strong> table</td>
<td>741</td>
</tr>
</tbody>
</table>
<p>Four different row counts, out of the same two tables. Which one is correct depends entirely on the question you are asking, and choosing that question is your job rather than the software’s.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="✏️ Test your knowledge">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✏️ Test your knowledge
</div>
</div>
<div class="callout-body-container callout-body">
<p>Build a third table, <code>pm10</code>, the same way you built the other two tables: filter <code>goleta</code> to <code>parameter == 'pm10'</code>, keep <code>datetimeLocal</code> and <code>value</code>, and rename <code>value</code> to <code>pm10_ugm3</code>. Then merge your PM2.5 table with it two ways, keeping <code>pm25</code> on the left both times, once using <code>how='inner'</code> and once using <code>how='left'</code>, and print both shapes. How many PM2.5 hours have no PM10 reading beside them?</p>
</div>
</div>
</section>
<section id="the-rows-you-lose-are-not-a-random-sample" class="level2">
<h2 class="anchored" data-anchor-id="the-rows-you-lose-are-not-a-random-sample">The rows you lose are not a random sample</h2>
<p>The inner join threw away 30 PM2.5 hours and 7 ozone hours, and it is tempting to shrug at 37 rows out of 1,445 and move on.</p>
<p>Please don’t! Look at <strong>which</strong> rows went missing before you decide they do not matter.</p>
<p>On Friday we handed you a line that pulls the hour out of a timestamp. Here it is again, doing the same job on the rows the join could not match:</p>
<div id="023f03b2" class="cell" data-execution_count="11">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>missing_o3 <span class="op">=</span> right[right[<span class="st">'o3_ppm'</span>].isnull()].copy()</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>missing_o3[<span class="st">'datetimeLocal'</span>].<span class="bu">str</span>[<span class="dv">11</span>:<span class="dv">13</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>datetimeLocal
03    30
Name: count, dtype: int64</code></pre>
</div>
</div>
<p>Every single one of the thirty PM2.5 hours with no ozone beside it is at <strong>03:00</strong>. Not spread across the day: all of them, all thirty, at three in the morning, on thirty different days.</p>
<div id="f9ef5b88" class="cell" data-execution_count="12">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>o3[<span class="st">'datetimeLocal'</span>].<span class="bu">str</span>[<span class="dv">11</span>:<span class="dv">13</span>].value_counts().sort_index()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>datetimeLocal
00    31
01    30
02    30
04    31
05    31
06    31
07    31
08    31
09    31
10    31
11    31
12    31
13    31
14    31
15    31
16    31
17    31
18    31
19    31
20    31
21    31
22    31
23    31
Name: count, dtype: int64</code></pre>
</div>
</div>
<p>The ozone table shows the same thing directly. Twenty-three hours of the day have thirty or thirty-one readings, and hour <code>'03'</code> does not appear at all. The Goleta ozone analyser looks like it goes offline for an hour every night, quite possibly to run a calibration, and nothing in the file says so.</p>
<p>The merge surfaced that gap for us. A missing key cannot match anything, so the unmatched rows collect exactly the hours one instrument never recorded.</p>
<div class="callout callout-style-default callout-important callout-titled" title="This is the habit">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
This is the habit
</div>
</div>
<div class="callout-body-container callout-body">
<p>A join is one of the best data quality instruments you have. Whenever you merge two tables, look at the rows that did <strong>not</strong> match, and ask whether they have anything in common. If they do, you have learned something about how your data was collected, and it is often something nobody bothered to write down.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="✏️ Test your knowledge">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✏️ Test your knowledge
</div>
</div>
<div class="callout-body-container callout-body">
<p>Do the mirror version. Pull the seven ozone hours that have no PM2.5 beside them out of <code>left</code>, and look at what hours they fall on. Then, in a markdown cell, say in two or three sentences whether this second gap tells a different story from the 3 a.m. one, and why. Does it look like a schedule, or does it look like an accident?</p>
</div>
</div>
</section>
<section id="what-a-joined-table-is-for" class="level2">
<h2 class="anchored" data-anchor-id="what-a-joined-table-is-for">What a joined table is for</h2>
<p>Now that the two pollutants are in the same row, we can ask the question one table could not answer. On Friday we found that ozone peaks in the early afternoon and PM2.5 peaks around midday, from which it is tempting to conclude that the bad hours are the same hours.</p>
<p>Test it. The top-N pattern from Wednesday, applied to the joined table:</p>
<div id="2cc0f17f" class="cell" data-execution_count="13">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>paired.sort_values(<span class="st">'pm25_ugm3'</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">datetimeLocal</th>
<th data-quarto-table-cell-role="th">o3_ppm</th>
<th data-quarto-table-cell-role="th">pm25_ugm3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">142</td>
<td>2024-07-18T01:00:00-07:00</td>
<td>0.022</td>
<td>22.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">464</td>
<td>2024-08-01T01:00:00-07:00</td>
<td>0.011</td>
<td>22.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">619</td>
<td>2024-08-08T01:00:00-07:00</td>
<td>0.025</td>
<td>21.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">673</td>
<td>2024-08-10T10:00:00-07:00</td>
<td>0.029</td>
<td>20.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">609</td>
<td>2024-08-07T15:00:00-07:00</td>
<td>0.043</td>
<td>19.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">585</td>
<td>2024-08-06T13:00:00-07:00</td>
<td>0.040</td>
<td>19.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">293</td>
<td>2024-07-24T15:00:00-07:00</td>
<td>0.027</td>
<td>17.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">349</td>
<td>2024-07-27T01:00:00-07:00</td>
<td>0.008</td>
<td>17.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">587</td>
<td>2024-08-06T16:00:00-07:00</td>
<td>0.040</td>
<td>16.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">586</td>
<td>2024-08-06T14:00:00-07:00</td>
<td>0.041</td>
<td>16.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Read the timestamps and the ozone column together. The ten smokiest hours of the month are not one group but two. Four of them are at <strong>01:00</strong>, and three of those four sit in the bottom half of the month’s ozone readings, one of them in the bottom six percent. The other six hours are daylight hours, and four of those six are in the top two percent of the month’s ozone readings.</p>
<p>Now average the ten together, and compare that average with the file as a whole:</p>
<div id="c6c6aca2" class="cell" data-execution_count="14">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(paired[<span class="st">'o3_ppm'</span>].mean())</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(paired.sort_values(<span class="st">'pm25_ugm3'</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>)[<span class="st">'o3_ppm'</span>].mean())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>0.022438920454545454
0.028600000000000004</code></pre>
</div>
</div>
<p>The mean of the ten smokiest hours is <strong>higher</strong> than the mean of every hour, 0.029 ppm against 0.022. Read on its own, that number says the smoky hours are also the ozone hours, which is the conclusion the row by row table just argued against. A single average cannot show the split at all, because it is the mean of four low readings and six high ones taken together.</p>
<p>The individual rows give the reading that makes physical sense. Ozone is manufactured by sunlight and cannot be produced at one in the morning, so whatever is putting particulates into Goleta’s air at 1 a.m. is a different process from the one that fouls its afternoons. A mean computed across two processes describes neither one of them well.</p>
<p>Two tables of hourly averages, however carefully we compare them, cannot show us that split, because the comparison we need is between two measurements taken in the same hour. A joined table puts those two measurements in the same row.</p>
</section>
<section id="when-the-key-columns-have-different-names" class="level2">
<h2 class="anchored" data-anchor-id="when-the-key-columns-have-different-names">When the key columns have different names</h2>
<p>The join pattern so far assumes both tables call the key by the same name. Real files rarely line up that neatly, so pandas lets you name the two key columns separately: <em>this column here, that column there</em>.</p>
<p>Here is a case you have already met. On Friday we grouped the national parks visitor records by <code>region</code> and got a handful of two-letter codes back, with no idea what they meant. Count the codes in the output below, because you will want the number in a moment:</p>
<div id="cb2afcba" class="cell" data-execution_count="15">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="st">'https://eds-217-essential-python.github.io/data/national_parks.csv'</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>parks <span class="op">=</span> pd.read_csv(url)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>parks <span class="op">=</span> parks[parks[<span class="st">'year'</span>] <span class="op">!=</span> <span class="st">'Total'</span>].copy()</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>parks[<span class="st">'region'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>region
IM    5682
NE    3637
SE    3442
PW    3194
MW    2578
NC    1547
AK    1018
NT      76
Name: count, dtype: int64</code></pre>
</div>
</div>
<p>Eight codes. Note that this table is not quite Friday’s: Friday’s also kept only the rows whose <code>unit_type</code> is <code>National Park</code>, and the file you have just read in keeps every unit, so it has one code in it that Friday’s did not.</p>
<p>Codes like these are extremely common, because whoever built the file was saving space and already knew what they meant. The fix is a <strong>lookup table</strong>: a small table, often one you write yourself, that translates codes into something a reader can use.</p>
<p>Here is one for the seven geographic regions, which are the ones you met on Friday:</p>
<div id="12c807a5" class="cell" data-execution_count="16">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>regions <span class="op">=</span> pd.DataFrame({</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'code'</span>: [<span class="st">'AK'</span>, <span class="st">'IM'</span>, <span class="st">'MW'</span>, <span class="st">'NC'</span>, <span class="st">'NE'</span>, <span class="st">'PW'</span>, <span class="st">'SE'</span>],</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'region_name'</span>: [<span class="st">'Alaska'</span>, <span class="st">'Intermountain'</span>, <span class="st">'Midwest'</span>, <span class="st">'National Capital'</span>,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                    <span class="st">'Northeast'</span>, <span class="st">'Pacific West'</span>, <span class="st">'Southeast'</span>],</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>regions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="16">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">code</th>
<th data-quarto-table-cell-role="th">region_name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>AK</td>
<td>Alaska</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>IM</td>
<td>Intermountain</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>MW</td>
<td>Midwest</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>NC</td>
<td>National Capital</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>NE</td>
<td>Northeast</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>PW</td>
<td>Pacific West</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>SE</td>
<td>Southeast</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Seven rows and two columns, typed by hand, and it is about to make 21,000 rows readable. The key is <code>region</code> on the left and <code>code</code> on the right, so you name both:</p>
<div id="c1ac718f" class="cell" data-execution_count="17">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>labelled <span class="op">=</span> pd.merge(parks, regions, left_on<span class="op">=</span><span class="st">'region'</span>, right_on<span class="op">=</span><span class="st">'code'</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>labelled[[<span class="st">'unit_name'</span>, <span class="st">'region'</span>, <span class="st">'region_name'</span>, <span class="st">'year'</span>, <span class="st">'visitors'</span>]].head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="17">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">unit_name</th>
<th data-quarto-table-cell-role="th">region</th>
<th data-quarto-table-cell-role="th">region_name</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">visitors</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Crater Lake National Park</td>
<td>PW</td>
<td>Pacific West</td>
<td>1904</td>
<td>1500.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Lake Roosevelt National Recreation Area</td>
<td>PW</td>
<td>Pacific West</td>
<td>1941</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Lewis and Clark National Historical Park</td>
<td>PW</td>
<td>Pacific West</td>
<td>1961</td>
<td>69000.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Olympic National Park</td>
<td>PW</td>
<td>Pacific West</td>
<td>1935</td>
<td>2200.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Santa Monica Mountains National Recreation Area</td>
<td>PW</td>
<td>Pacific West</td>
<td>1982</td>
<td>468144.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="sourceCode" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>pd.merge(left, right, left_on<span class="op">=</span><span class="st">'column_in_left'</span>, right_on<span class="op">=</span><span class="st">'column_in_right'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Naming the two columns separately is the whole difference. <code>on=</code> is the shorthand for the case where the two names happen to agree.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>🐍 The result has <strong>both</strong> key columns, <code>region</code> and <code>code</code>, holding identical values. Keeping both is not a bug: pandas has no way to choose between them, so it returns both and leaves the choice to you. Drop one whenever it bothers you.</p>
</div>
</div>
</section>
<section id="the-merge-that-quietly-lost-something" class="level2">
<h2 class="anchored" data-anchor-id="the-merge-that-quietly-lost-something">The merge that quietly lost something</h2>
<p>Check the row count, the way we now do after every merge:</p>
<div id="fb22041b" class="cell" data-execution_count="18">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(parks.shape)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(labelled.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(21174, 12)
(21098, 14)</code></pre>
</div>
</div>
<p>21,174 rows went in and 21,098 came out. Seventy-six rows did not survive, because the default is an inner join and their region code is missing from your lookup table.</p>
<p>Find them the way you found the 3 a.m. gap:</p>
<div id="096c93e3" class="cell" data-execution_count="19">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>checked <span class="op">=</span> pd.merge(parks, regions, left_on<span class="op">=</span><span class="st">'region'</span>, right_on<span class="op">=</span><span class="st">'code'</span>, how<span class="op">=</span><span class="st">'left'</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>missing <span class="op">=</span> checked[checked[<span class="st">'region_name'</span>].isnull()]</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(missing[<span class="st">'region'</span>].value_counts())</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(missing[<span class="st">'unit_name'</span>].unique())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>region
NT    76
Name: count, dtype: int64
['Blue Ridge Parkway']</code></pre>
</div>
</div>
<p><code>NT</code>, seventy-six rows, all of them the Blue Ridge Parkway. Your lookup table has seven codes and the file has eight, because the Parkway is administered as a National Trail rather than by one of the seven geographic regions.</p>
<p>No error appeared and no warning printed. The inner join returned a perfectly reasonable-looking table with a real American landmark missing from it, and we only know about it because we compared two row counts.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="✏️ Test your knowledge">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✏️ Test your knowledge
</div>
</div>
<div class="callout-body-container callout-body">
<p>Add a row to <code>regions</code> for the <code>NT</code> code with a <code>region_name</code> of your choosing, rebuild the merge, and confirm that all 21,174 rows now survive. Then write one sentence saying which <code>how=</code> you would use in a script that runs every month on a file somebody else maintains, and why.</p>
</div>
</div>
</section>
<section id="key-points" class="level2">
<h2 class="anchored" data-anchor-id="key-points">Key points</h2>
<ul>
<li>The <strong>join pattern</strong> is <code>pd.merge(left, right, on='key')</code>. The key is the column the two tables have in common, and its values are what pandas matches the rows on.</li>
<li>Use <code>left_on=</code> and <code>right_on=</code> when the key columns have <strong>different names</strong> in the two tables.</li>
<li><code>how=</code> decides which rows survive: <code>'inner'</code> keeps keys present in both (the default), <code>'left'</code> keeps every row of the left table, <code>'right'</code> the mirror, and <code>'outer'</code> keeps everything.</li>
<li><strong>Always compare the row count before and after a merge.</strong> No error appears and no warning prints when a join throws data away.</li>
<li><strong>Always run <code>.isnull().sum()</code> after a left, right or outer join.</strong> Those three joins exist in order to produce nulls, and counting the nulls tells you how many rows found no match.</li>
<li>The rows a join fails to match are usually not random. Look at them, because they often tell you something about how the data was collected.</li>
<li>Rename your measurement columns <strong>before</strong> you merge, so you never have to work out what <code>value_x</code> was.</li>
<li>A <strong>lookup table</strong> you write yourself is a legitimate second table, and often the most useful one you have (all seven rows of it!).</li>
</ul>
</section>
<section id="resources" class="level2">
<h2 class="anchored" data-anchor-id="resources">Resources</h2>
<ul>
<li><a href="../../course-materials/cheatsheets/data_merging.html">📖 EDS 217 cheatsheet: merging and joining data</a></li>
<li><a href="../../course-materials/cheatsheets/pandas_dataframes.html">📖 EDS 217 cheatsheet: pandas DataFrames</a></li>
<li><a href="../../course-materials/cheatsheets/data_selection.html">📖 EDS 217 cheatsheet: data selection and filtering</a></li>
<li><a href="https://pandas.pydata.org/docs/reference/api/pandas.merge.html" target="_blank">pandas documentation: <code>pandas.merge</code></a></li>
<li><a href="https://pandas.pydata.org/docs/user_guide/merging.html" target="_blank">pandas user guide: merge, join, concatenate</a></li>
<li><a href="https://openaq.org" target="_blank">OpenAQ</a></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><img src="../../images/bren-logo.png" alt="The Bren School of Environmental Science &amp; Management logo" width="250"></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This website is built with <a href="https://github.com/EDS-217-Essential-Python/EDS-217-Essential-Python.github.io"><i class="fa-brands fa-github" title="the github octocat logo" aria-label="github"></i></a> and <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>