#!/usr/bin/env python3
"""
Install the transparent data cache into the IPython startup directory.

Run once per machine:

    python tools/install_offline_cache.py

Every IPython kernel started afterwards, including the ones Quarto launches
when it renders, loads `tools/eds217_offline_cache.py` and patches
pandas.read_csv / read_excel. The module itself stays in the repo, so later
edits take effect without reinstalling.

Uninstall with --remove.
"""

import argparse
import sys
from pathlib import Path

STARTUP_FILENAME = "00-eds217-offline-cache.py"

TEMPLATE = '''# Auto-generated by tools/install_offline_cache.py -- safe to delete.
# Serves URL-based pandas reads from a local cache so EDS 217 materials
# render without a network connection. Instructor machine only.
import sys as _sys

_TOOLS = r"{tools_dir}"
if _TOOLS not in _sys.path:
    _sys.path.insert(0, _TOOLS)

try:
    import eds217_offline_cache as _eds217_cache
    _eds217_cache.install()
    EDS217_OFFLINE_CACHE = _eds217_cache
except Exception as _exc:  # never break a kernel over this
    print(f"[eds217-cache] not loaded: {{_exc}}", file=_sys.stderr)
'''


def startup_dir() -> Path:
    try:
        from IPython.paths import get_ipython_dir
        base = Path(get_ipython_dir())
    except Exception:
        base = Path.home() / ".ipython"
    return base / "profile_default" / "startup"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--remove", action="store_true", help="uninstall the startup hook")
    args = ap.parse_args()

    d = startup_dir()
    target = d / STARTUP_FILENAME

    if args.remove:
        if target.exists():
            target.unlink()
            print(f"Removed {target}")
        else:
            print(f"Nothing to remove at {target}")
        return 0

    tools_dir = Path(__file__).resolve().parent
    module = tools_dir / "eds217_offline_cache.py"
    if not module.exists():
        print(f"ERROR: {module} not found", file=sys.stderr)
        return 1

    d.mkdir(parents=True, exist_ok=True)
    target.write_text(TEMPLATE.format(tools_dir=str(tools_dir)))

    print(f"Installed  {target}")
    print(f"Points at  {module}")
    print()
    print("Verify with:")
    print('    ipython -c "print(EDS217_OFFLINE_CACHE.status())"')
    print()
    print("Then populate the cache while you still have a connection:")
    print("    python tools/warm_cache.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
