<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Answer Key</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../course-materials/assets/css/exercises.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">EDS 217</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">🏠 home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-daily-materials" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">🗓️ daily materials</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-daily-materials">    
        <li>
    <a class="dropdown-item" href="../../course-materials/day1.html">
 <span class="dropdown-text">1️⃣ Day 1 (8/31)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day2.html">
 <span class="dropdown-text">2️⃣ Day 2 (9/1)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day3.html">
 <span class="dropdown-text">3️⃣ Day 3 (9/2)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day4.html">
 <span class="dropdown-text">4️⃣ Day 4 (9/3)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day5.html">
 <span class="dropdown-text">5️⃣ Day 5 (9/4)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day6.html">
 <span class="dropdown-text">6️⃣ Day 6 (9/8)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day7.html">
 <span class="dropdown-text">7️⃣ Day 7 (9/9)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day8.html">
 <span class="dropdown-text">8️⃣ Day 8 (9/10)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day9.html">
 <span class="dropdown-text">9️⃣ Day 9 (9/11)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-interactive-sessions" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">💻 interactive sessions</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-interactive-sessions">    
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1a_positron_notebooks.html">
 <span class="dropdown-text">Session 1a - ⚒️ Positron &amp; Jupyter Notebooks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1b_python_essentials.html">
 <span class="dropdown-text">Session 1b - 🐍 Python Essentials</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1c_data_science_workflow_1.html">
 <span class="dropdown-text">Session 1c - 🎬 The Python Data Science Workflow, Part 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1d_data_science_workflow_2.html">
 <span class="dropdown-text">Session 1d - 🎬 The Python Data Science Workflow, Part 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/2a_reading_data.html">
 <span class="dropdown-text">Session 2a - 🐼 Reading Data into pandas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/2b_exploring_data.html">
 <span class="dropdown-text">Session 2b - 🔎 Exploring a DataFrame</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/2d_lists_and_dicts.html">
 <span class="dropdown-text">Session 2d - 📝 Lists &amp; Dictionaries</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/3a_booleans_and_conditionals.html">
 <span class="dropdown-text">Session 3a - 📝 Booleans &amp; Conditionals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/3b_filtering_data.html">
 <span class="dropdown-text">Session 3b - 🔍 The Filter Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/3c_sorting_and_ranking.html">
 <span class="dropdown-text">Session 3c - 🥇 The Top-N Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4a_cleaning_data.html">
 <span class="dropdown-text">Session 4a - 🧼 Missing, Duplicated, Miscast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4b_functions.html">
 <span class="dropdown-text">Session 4b - ⚙️ Write It Once, Name It, Use It</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4c_transforming_data.html">
 <span class="dropdown-text">Session 4c - ➕ The Derived-Column Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/5a_grouping_data.html">
 <span class="dropdown-text">Session 5a - 🗂️ The Split-Apply-Combine Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/5b_aggregating_data.html">
 <span class="dropdown-text">Session 5b - 📊 Several Answers at Once</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/5d_loops_over_groups.html">
 <span class="dropdown-text">Session 5d - 🔁 When a Pattern Is Not Enough</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6a_joining_data.html">
 <span class="dropdown-text">Session 6a - 🔗 The Join Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6b_reshaping_data.html">
 <span class="dropdown-text">Session 6b - 🧩 Long and Wide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6c_dates.html">
 <span class="dropdown-text">Session 6c - 📆 A Date Is Not a Number</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7a_matplotlib.html">
 <span class="dropdown-text">Session 7a - 🖼️ The Anatomy of a Figure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7b_seaborn.html">
 <span class="dropdown-text">Session 7b - 🎨 Name the Columns, Not the Colours</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7d_project_kickoff.html">
 <span class="dropdown-text">Session 7d - 🚀 Project Kickoff</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-coding-colabs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">🙌 coding colabs</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-coding-colabs">    
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/2c_exploring_unfamiliar_data.html">
 <span class="dropdown-text">🙌 Session 2c - Five Claims About a Dataset You’ve Never Seen</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/3d_ranking_questions.html">
 <span class="dropdown-text">🙌 Session 3d - Which One, and How Do You Know?</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/4d_cleaning_messy_data.html">
 <span class="dropdown-text">🙌 Session 4d - From Field Sheet to DataFrame</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/5c_grouped_comparisons.html">
 <span class="dropdown-text">🙌 Session 5c - The Comparison You Made Yesterday, Properly</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/6d_two_table_exercise.html">
 <span class="dropdown-text">🙌 Session 6d - Two Records, Sixty-Six Years Apart</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/7c_penguins.html">
 <span class="dropdown-text">🙌 Session 7c - One Cloud of Points, Three Species</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../cheatsheets.html"> 
<span class="menu-text">👀 cheatsheets</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-resources" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">📚 resources</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-resources">    
        <li>
    <a class="dropdown-item" href="https://docs.python.org/3/" target="_blank">
 <span class="dropdown-text">📚 Python Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pandas.pydata.org/docs/" target="_blank">
 <span class="dropdown-text">📚 Pandas Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://numpy.org/doc/stable/" target="_blank">
 <span class="dropdown-text">📚 Numpy Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://matplotlib.org/stable/contents.html" target="_blank">
 <span class="dropdown-text">📚 Matplotlib Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://seaborn.pydata.org/" target="_blank">
 <span class="dropdown-text">📚 Seaborn Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://positron.posit.co/" target="_blank">
 <span class="dropdown-text">📚 Positron Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://docs.anaconda.com/" target="_blank">
 <span class="dropdown-text">📚 Anaconda Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://stackoverflow.com/" target="_blank">
 <span class="dropdown-text">📚 Stack Overflow</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://realpython.com/" target="_blank">
 <span class="dropdown-text">📚 Real Python</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://towardsdatascience.com/" target="_blank">
 <span class="dropdown-text">📚 Towards Data Science</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.datacamp.com/" target="_blank">
 <span class="dropdown-text">📚 DataCamp</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.kaggle.com/" target="_blank">
 <span class="dropdown-text">📚 Kaggle</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="http://pythontutor.com/" target="_blank">
 <span class="dropdown-text">🧰 Python Tutor</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pandastutor.com/vis.html#" target="_blank">
 <span class="dropdown-text">🧰 Pandas Tutor</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://wesmckinney.com/book/" target="_blank">
 <span class="dropdown-text">📙 Python for Data Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://jakevdp.github.io/PythonDataScienceHandbook/" target="_blank">
 <span class="dropdown-text">📙 Python for Data Science Handbook</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/jakevdp/PythonDataScienceHandbook" target="_blank">
 <span class="dropdown-text">📙 Python Data Science Handbook (GitHub)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://talkpython.fm/" target="_blank">
 <span class="dropdown-text">📻 Talk Python to Me</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/EDS-217-Essential-Python/EDS-217-Essential-Python.github.io" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-left">
      <h1 class="title">Answer Key</h1>
            <p class="subtitle lead">🙌 From Field Sheet to DataFrame</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta column-page-left">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#setup" id="toc-setup" class="nav-link active" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#part-1-find-out-what-is-wrong" id="toc-part-1-find-out-what-is-wrong" class="nav-link" data-scroll-target="#part-1-find-out-what-is-wrong">Part 1: Find out what is wrong</a></li>
  <li><a href="#part-2-clean-it" id="toc-part-2-clean-it" class="nav-link" data-scroll-target="#part-2-clean-it">Part 2: Clean it</a></li>
  <li><a href="#part-3-transform-it" id="toc-part-3-transform-it" class="nav-link" data-scroll-target="#part-3-transform-it">Part 3: Transform it</a></li>
  <li><a href="#part-4-ask-it-something" id="toc-part-4-ask-it-something" class="nav-link" data-scroll-target="#part-4-ask-it-something">Part 4: Ask it something</a></li>
  <li><a href="#if-you-finish-early" id="toc-if-you-finish-early" class="nav-link" data-scroll-target="#if-you-finish-early">If you finish early</a></li>
  <li><a href="#where-the-marks-are" id="toc-where-the-marks-are" class="nav-link" data-scroll-target="#where-the-marks-are">Where the marks are</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block column-page-left" id="quarto-document-content">





<div class="callout callout-style-default callout-important callout-titled" title="How to use this key">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How to use this key
</div>
</div>
<div class="callout-body-container callout-body">
<p>Work the colab first, then come here. The code below is <strong>one</strong> correct answer, not the only one. Today’s activity is a colab, so you wrote every line yourself and there are more reasonable ways to write it than there are on a guided exercise. If your code looks different but produces the same numbers, you were right.</p>
<p>The written answers matter more than the code. You can already tell whether your code ran. What you cannot check on your own is whether you read the result correctly, and that is what the green <strong>Answer</strong> boxes are for. Compare your markdown cells against them.</p>
<p>⬅️ Back to <a href="../../course-materials/coding-colabs/4d_cleaning_messy_data.html">the colab</a></p>
</div>
</div>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<div id="e9c744ac" class="cell" data-execution_count="1">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="st">'https://eds-217-essential-python.github.io/data/messy_field_survey.csv'</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>survey <span class="op">=</span> pd.read_csv(url)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>survey.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>(320, 7)</code></pre>
</div>
</div>
</section>
<section id="part-1-find-out-what-is-wrong" class="level2">
<h2 class="anchored" data-anchor-id="part-1-find-out-what-is-wrong">Part 1: Find out what is wrong</h2>
<p><strong>1. How many rows and columns? Run <code>.head()</code> and <code>.info()</code>. Which columns came in as <code>object</code> when you expected a number, and which came in as <code>float64</code> when you expected a whole number?</strong></p>
<div id="e3a3e0b1" class="cell" data-execution_count="2">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(survey.shape)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>survey.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(320, 7)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">site</th>
<th data-quarto-table-cell-role="th">collection date</th>
<th data-quarto-table-cell-role="th">temperature_c</th>
<th data-quarto-table-cell-role="th">pH</th>
<th data-quarto-table-cell-role="th">dissolved_oxygen_mg_L</th>
<th data-quarto-table-cell-role="th">conductivity_uS_cm</th>
<th data-quarto-table-cell-role="th">n_replicates</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>SITE_F</td>
<td>2025-07-28</td>
<td>24.1</td>
<td>5.89</td>
<td>5.51</td>
<td>899.1</td>
<td>4.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>site-d</td>
<td>2025-08-05</td>
<td>12.5</td>
<td>7.74</td>
<td>9.97</td>
<td>300.1</td>
<td>4.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Site_C</td>
<td>2025-07-04</td>
<td>22.6</td>
<td>6.42</td>
<td>7.19</td>
<td>815.8</td>
<td>4.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Site_D</td>
<td>2025-08-15</td>
<td>16.0</td>
<td>7.74</td>
<td>9.73</td>
<td>250.7</td>
<td>3.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>site_a</td>
<td>2025-06-24</td>
<td>14.7</td>
<td>7,64</td>
<td>9.19</td>
<td>338.8</td>
<td>3.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="ec2c7503" class="cell" data-execution_count="3">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>survey.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 320 entries, 0 to 319
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   site                   320 non-null    object 
 1   collection date        320 non-null    object 
 2   temperature_c          302 non-null    float64
 3   pH                     320 non-null    object 
 4   dissolved_oxygen_mg_L  309 non-null    float64
 5   conductivity_uS_cm     313 non-null    float64
 6   n_replicates           315 non-null    float64
dtypes: float64(4), object(3)
memory usage: 17.6+ KB</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>320 rows and 7 columns.</strong> <code>pH</code> is the column that came in as <code>object</code> when you expected a number. <code>site</code> and <code>collection date</code> are also <code>object</code>, but that is correct for text and a date read as text.</p>
<p><code>n_replicates</code> is the <code>float64</code> that should be a whole number. Pandas cannot store a missing value in an integer column, so a single blank anywhere in the column forces the whole thing to float, and you get <code>4.0</code> and <code>3.0</code> instead of <code>4</code> and <code>3</code>. The dtype is therefore evidence: a count column arriving as float almost always means it has gaps.</p>
</div>
</div>
<p><strong>2. Run <code>.isnull().sum()</code>. Which four columns have gaps, and how many each?</strong></p>
<div id="ac88ef1f" class="cell" data-execution_count="4">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>survey.isnull().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>site                      0
collection date           0
temperature_c            18
pH                        0
dissolved_oxygen_mg_L    11
conductivity_uS_cm        7
n_replicates              5
dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong><code>temperature_c</code> 18, <code>dissolved_oxygen_mg_L</code> 11, <code>conductivity_uS_cm</code> 7, and <code>n_replicates</code> 5.</strong> The four columns come to 41 blanks in total, but 41 blanks are not 41 blank rows, and you cannot tell yet how many rows they occupy.</p>
<p>Note what is not in this list. <code>temperature_c</code> also contains nine impossible values that <code>.isnull()</code> counts as present, because <code>-999</code> is a number. The null count is a lower bound on your missing data, not the whole of it.</p>
</div>
</div>
<p><strong>3. Run <code>.duplicated().sum()</code>. How many rows are exact copies of an earlier row?</strong></p>
<div id="476d0c97" class="cell" data-execution_count="5">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>survey.duplicated().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>np.int64(20)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>20 rows.</strong> <code>.duplicated()</code> flags the second and later copies only, so 20 flagged rows means 40 rows of the file are involved, each record appearing exactly twice. A record that appears exactly twice is the usual signature of a transcriber entering a page, losing their place, and entering it again.</p>
</div>
</div>
<p><strong>4. Run <code>survey['site'].value_counts()</code>. There are six sites. How many distinct labels does the file contain? Look carefully at the quotation marks in the output of <code>survey['site'].unique()</code>.</strong></p>
<div id="32453ace" class="cell" data-execution_count="6">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(survey[<span class="st">'site'</span>].nunique())</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'site'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>36</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>site
site-b     16
 site-c    13
SITE_F     12
site_f     12
 site_a    12
SITE_A     12
site_e     12
 site_d    12
site_d     12
Site_A     12
site-e     11
site_f     11
Site_F     11
SITE_B     11
SITE_C     11
 SITE_E     9
Site_C      9
site_e      9
site_a      8
site-c      8
Site_B      8
Site_D      8
SITE_E      7
site_b      7
site_b      7
site_c      7
site-d      7
site_d      7
SITE_D      7
Site_E      6
site_a      6
site_c      5
site-a      4
 site-f     4
 Site_B     4
site-f      3
Name: count, dtype: int64</code></pre>
</div>
</div>
<div id="21ea6db9" class="cell" data-execution_count="7">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'site'</span>].unique()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>array(['SITE_F', 'site-d', 'Site_C', 'Site_D', ' site_a', 'SITE_A',
       'site_a', 'SITE_D', ' site_d', 'site_c', 'site_a ', 'site-a',
       'SITE_C', 'site_d', 'site-e', 'Site_E', 'SITE_B', 'site_e ',
       ' Site_B', 'Site_F', 'site_f ', 'site_f', 'site_e', 'site_c ',
       'site-b', 'site_b ', 'SITE_E', 'site-f', 'site_d ', ' site-c',
       'Site_A', 'site-c', ' site-f', 'Site_B', ' SITE_E', 'site_b'],
      dtype=object)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>36 distinct labels for six sites.</strong> Three separate kinds of damage are stacked on top of each other: capitalisation (<code>SITE_F</code>, <code>Site_C</code>, <code>site_a</code>), the separator character (<code>site-d</code> against <code>site_d</code>), and leading or trailing whitespace.</p>
<p>The whitespace is the one worth dwelling on. In the <code>.value_counts()</code> output, <code>site_b</code> appears on two separate rows with 7 each, and nothing on screen tells you why. Only <code>.unique()</code> shows it, because it prints the quotation marks, and <code>' site-c'</code> and <code>'site_c '</code> are visibly different from <code>'site_c'</code> once the quotes are there. A label you cannot see is still a label pandas will group separately.</p>
</div>
</div>
<p><strong>5. Run <code>.describe()</code> on <code>temperature_c</code>. The minimum is not a temperature any stream has ever had… What’s going on here??</strong></p>
<div id="8fe24bdd" class="cell" data-execution_count="8">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'temperature_c'</span>].describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>count    302.000000
mean     -11.206623
std      173.437298
min     -999.000000
25%       16.700000
50%       18.600000
75%       21.400000
max       26.500000
Name: temperature_c, dtype: float64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The minimum is -999, which is the value the logger records when a reading fails.</strong> No stream is at -999 °C, which is below absolute zero, so the value is not a measurement at all. It is missing data recorded as a number so that the field would not be left empty.</p>
<p>Look at what it has already done to the summary. The mean of this column reads <strong>-11.21 °C</strong> and the standard deviation reads <strong>173.44</strong>. The reported average is colder than every real observation in the column. When a mean sits outside the range of the plausible data, the cause is not skew. Some values in the column are not measurements.</p>
</div>
</div>
</section>
<section id="part-2-clean-it" class="level2">
<h2 class="anchored" data-anchor-id="part-2-clean-it">Part 2: Clean it</h2>
<p><strong>6. Remove the exact duplicate rows. How many rows are left?</strong></p>
<div id="df572f21" class="cell" data-execution_count="9">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>survey <span class="op">=</span> survey.drop_duplicates()</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>survey.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>(300, 7)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>300 rows</strong>, down from 320. The 20 duplicated rows were complete records, which you can confirm later: the null counts you found in question 2 are unchanged after this step, so no blanks were removed along with the copies.</p>
</div>
</div>
<p><strong>7. Fix the <code>site</code> column so that all six sites have one label each. You will need three separate statements, one per method, each assigned back to <code>survey['site']</code>: strip the whitespace, lower-case the text, and replace the hyphens with underscores. Confirm with <code>.value_counts()</code> that you have exactly six distinct site labels, reading <code>site_a</code> through <code>site_f</code>.</strong></p>
<div id="8492c883" class="cell" data-execution_count="10">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'site'</span>] <span class="op">=</span> survey[<span class="st">'site'</span>].<span class="bu">str</span>.strip()</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'site'</span>] <span class="op">=</span> survey[<span class="st">'site'</span>].<span class="bu">str</span>.lower()</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'site'</span>] <span class="op">=</span> survey[<span class="st">'site'</span>].<span class="bu">str</span>.replace(<span class="st">'-'</span>, <span class="st">'_'</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'site'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>site
site_f    50
site_d    50
site_c    50
site_a    50
site_e    50
site_b    50
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Six labels, with exactly 50 rows each.</strong> Thirty-six labels collapsed to six, and the perfect balance is your evidence that you caught all of them: the survey design was 50 visits per site, so any leftover variant would show up as one site with 49 and a stray label with 1.</p>
<p>Each statement is assigned back to <code>survey['site']</code>, which matters. <code>.str.strip()</code> returns a new Series and does not change the column in place, so a line without the assignment runs without error and does nothing at all.</p>
</div>
</div>
<p><strong>8. <code>pH</code> came in as text. Find out why by looking at <code>survey['pH'].unique()</code>, then fix it with one <code>.str.replace()</code> and one <code>.astype()</code>, in that order. Confirm the dtype is <code>float64</code> and that <code>.describe()</code> gives a plausible pH range.</strong></p>
<div id="b318076d" class="cell" data-execution_count="11">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'pH'</span>].unique()[:<span class="dv">12</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>array(['5.89', '7.74', '6.42', '7,64', '7.47', '6.88', '7.54', '7.88',
       '6.68', '7.35', '7.62', '7.63'], dtype=object)</code></pre>
</div>
</div>
<div id="27fac5f0" class="cell" data-execution_count="12">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'pH'</span>] <span class="op">=</span> survey[<span class="st">'pH'</span>].<span class="bu">str</span>.replace(<span class="st">','</span>, <span class="st">'.'</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'pH'</span>] <span class="op">=</span> survey[<span class="st">'pH'</span>].astype(<span class="bu">float</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(survey[<span class="st">'pH'</span>].dtype)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'pH'</span>].describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>float64</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>count    300.000000
mean       7.018533
std        0.492886
min        5.780000
25%        6.615000
50%        7.020000
75%        7.372500
max        8.330000
Name: pH, dtype: float64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Somebody entering these sheets used a comma as the decimal separator</strong>, so values like <code>'7,64'</code> sit alongside <code>'5.89'</code>. Twenty-four of the 300 values are written that way, and pandas reads the whole column as text, because a single unparseable entry forces the dtype for all of them.</p>
<p>After the fix the column is <code>float64</code> and runs from <strong>5.78 to 8.33 with a mean of 7.02</strong>, which is a sensible range for stream water. The order matters: <code>.astype(float)</code> before the replace raises a <code>ValueError</code>, and the message names the exact string it could not convert.</p>
</div>
</div>
<p><strong>9. Three measurement columns have blanks: <code>temperature_c</code>, <code>dissolved_oxygen_mg_L</code>, and <code>conductivity_uS_cm</code>. A row with no measurement is no use to you, so drop those rows in a single <code>.dropna()</code> call with a list in <code>subset=</code>. How many rows did that cost?</strong></p>
<div id="5072d11c" class="cell" data-execution_count="13">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>survey <span class="op">=</span> survey.dropna(subset<span class="op">=</span>[<span class="st">'temperature_c'</span>, <span class="st">'dissolved_oxygen_mg_L'</span>, <span class="st">'conductivity_uS_cm'</span>])</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>survey.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>(264, 7)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>36 rows, leaving 264.</strong> The 36 dropped rows are 18 + 11 + 7 exactly, which tells you something you did not know before: no row was missing two of the three measurements. Every blank sits in a row that is otherwise complete.</p>
<p>Had any row been missing two, the drop would have cost fewer than 36, because <code>.dropna()</code> removes rows and not blanks. Comparing the rows lost against the sum of the column counts is a cheap check on whether your missing data is scattered or concentrated.</p>
</div>
</div>
<p><strong>10. <code>n_replicates</code> also has blanks, but here a blank means the field sheet recorded a single bottle and nobody bothered to write “1”. Fill those with <code>1</code> instead of dropping the rows, then convert the column to <code>int</code>. Confirm with <code>.value_counts()</code>.</strong></p>
<div id="6030ce77" class="cell" data-execution_count="14">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'n_replicates'</span>] <span class="op">=</span> survey[<span class="st">'n_replicates'</span>].fillna(<span class="dv">1</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'n_replicates'</span>] <span class="op">=</span> survey[<span class="st">'n_replicates'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'n_replicates'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>n_replicates
3    158
2     55
4     46
1      5
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>3 is the usual number of bottles (158 rows), then 2 (55) and 4 (46), and exactly 5 rows hold a 1.</strong> Five is also the number of blanks you filled, so the column contained no explicit <code>1</code> before you started. The absence of an explicit <code>1</code> is the evidence for the assumption you were handed: if some sheets wrote <code>1</code> and others left it blank, you would expect to see both, and you do not.</p>
<p>The two lines have to run in this order. <code>.astype(int)</code> on a column containing <code>NaN</code> raises an error, because a missing value cannot be an integer. Filling first is what makes the conversion legal, and the conversion is what turns <code>3.0</code> back into <code>3</code>.</p>
</div>
</div>
<p><strong>11. Now let’s deal with the impossible temperatures. Use the filter pattern from Day 3 to keep only the rows where <code>temperature_c</code> is above <code>-100</code>, and end the line with <code>.copy()</code>. How many rows did the loggers ruin?</strong></p>
<div id="2aa00b95" class="cell" data-execution_count="15">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>survey <span class="op">=</span> survey[survey[<span class="st">'temperature_c'</span>] <span class="op">&gt;</span> <span class="op">-</span><span class="dv">100</span>].copy()</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>survey.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>(255, 7)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Nine rows, leaving 255.</strong> All nine of those rows read <code>-999</code>, and each one was otherwise a complete record with good dissolved oxygen and conductivity, which is why question 9 did not remove them and why they were still here to catch.</p>
<p>The threshold is <code>-100</code> and not <code>-999</code> on purpose. You are excluding a physically impossible range, not one specific number, so the filter still works if a second logger writes <code>-9999</code>. The <code>.copy()</code> tells pandas you want a new table rather than a view of the old one, which is what prevents the <code>SettingWithCopyWarning</code> when you add columns in Part 3.</p>
</div>
</div>
<p><strong>12. Re-run <code>.describe()</code> on <code>temperature_c</code>. Compare the mean to the one you got in task 5. In a markdown cell, write one short statement about what the sentinel rows did to the average you saw in task 5.</strong></p>
<div id="61227fe8" class="cell" data-execution_count="16">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'temperature_c'</span>].describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>count    255.000000
mean      19.218824
std        3.184392
min       12.300000
25%       16.900000
50%       19.100000
75%       21.600000
max       26.500000
Name: temperature_c, dtype: float64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The mean moved from -11.21 °C to 19.22 °C, and the standard deviation from 173.44 to 3.18.</strong> Nine rows out of the 302 non-null temperature readings moved the average by more than 30 degrees, and you can check that directly: each <code>-999</code> sits about 1018 below the true mean, and 9 × 1018 / 302 is about 30.3, which is the whole of the shift. The other rows you removed changed the mean by less than a tenth of a degree.</p>
<p>The standard deviation is the more reliable warning sign. A stream survey with a standard deviation of 173 °C should have stopped you at question 5. Means can be argued about, but a spread of 173 °C across readings that in reality span about 14 °C, from 12.3 to 26.5, indicates a broken column rather than a real result.</p>
</div>
</div>
<p><strong>13. Rename <code>collection date</code> to <code>collection_date</code>, so you can reach it without quoting trouble later. <code>.rename()</code> is from Day 2; it takes <code>columns=</code> and a dictionary.</strong></p>
<div id="3d95b656" class="cell" data-execution_count="17">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>survey <span class="op">=</span> survey.rename(columns<span class="op">=</span>{<span class="st">'collection date'</span>: <span class="st">'collection_date'</span>})</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>survey.columns.tolist()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>['site',
 'collection_date',
 'temperature_c',
 'pH',
 'dissolved_oxygen_mg_L',
 'conductivity_uS_cm',
 'n_replicates']</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Seven columns, with <code>collection date</code> now <code>collection_date</code>.</strong> The space in the original name is the whole problem: <code>survey.collection date</code> is not valid Python, so every reference to it has to go through <code>survey['collection date']</code>. Renaming it once buys you the shorter form everywhere after.</p>
<p><code>.rename()</code> returns a new table rather than changing this one, which is why the result is assigned back to <code>survey</code>. Leave the assignment off and nothing happens, silently.</p>
</div>
</div>
</section>
<section id="part-3-transform-it" class="level2">
<h2 class="anchored" data-anchor-id="part-3-transform-it">Part 3: Transform it</h2>
<p><strong>14. Add a column called <code>conductivity_mS_cm</code> holding conductivity in millisiemens per centimetre, which is the microsiemens value divided by 1000.</strong></p>
<div id="2a292bfa" class="cell" data-execution_count="18">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'conductivity_mS_cm'</span>] <span class="op">=</span> survey[<span class="st">'conductivity_uS_cm'</span>] <span class="op">/</span> <span class="dv">1000</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>survey[[<span class="st">'conductivity_uS_cm'</span>, <span class="st">'conductivity_mS_cm'</span>]].head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="18">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">conductivity_uS_cm</th>
<th data-quarto-table-cell-role="th">conductivity_mS_cm</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>899.1</td>
<td>0.8991</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>300.1</td>
<td>0.3001</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>815.8</td>
<td>0.8158</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>250.7</td>
<td>0.2507</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>338.8</td>
<td>0.3388</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>A new column whose values are the microsiemens ones divided by 1,000.</strong> Dividing a column by a number divides every value in it, which is the derived-column pattern doing arithmetic on a whole column at once rather than a row at a time.</p>
<p>Keeping both columns side by side is the check: read the two numbers across a row and confirm the decimal point moved three places and nothing else changed.</p>
</div>
</div>
<p><strong>15. Add a column called <code>temperature_f</code> holding the temperature in Fahrenheit. Do it twice: once with the derived-column pattern and plain arithmetic, and once by writing a function <code>celsius_to_fahrenheit</code> and using <code>.apply()</code>. Check that the two columns agree.</strong></p>
<div id="51dbc8fd" class="cell" data-execution_count="19">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'temperature_f'</span>] <span class="op">=</span> survey[<span class="st">'temperature_c'</span>] <span class="op">*</span> <span class="dv">9</span> <span class="op">/</span> <span class="dv">5</span> <span class="op">+</span> <span class="dv">32</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> celsius_to_fahrenheit(celsius):</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Convert a temperature in Celsius to Fahrenheit."""</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (celsius <span class="op">*</span> <span class="dv">9</span> <span class="op">/</span> <span class="dv">5</span>) <span class="op">+</span> <span class="dv">32</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'temperature_f_applied'</span>] <span class="op">=</span> survey[<span class="st">'temperature_c'</span>].<span class="bu">apply</span>(celsius_to_fahrenheit)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>survey[[<span class="st">'temperature_c'</span>, <span class="st">'temperature_f'</span>, <span class="st">'temperature_f_applied'</span>]].head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="19">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">temperature_c</th>
<th data-quarto-table-cell-role="th">temperature_f</th>
<th data-quarto-table-cell-role="th">temperature_f_applied</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>24.1</td>
<td>75.38</td>
<td>75.38</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>12.5</td>
<td>54.50</td>
<td>54.50</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>22.6</td>
<td>72.68</td>
<td>72.68</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>16.0</td>
<td>60.80</td>
<td>60.80</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>14.7</td>
<td>58.46</td>
<td>58.46</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The two columns are identical, value for value.</strong> They perform the same arithmetic on the same numbers, so they agree to the last decimal place.</p>
<p>The difference is where the arithmetic happens. The first version hands the whole column to pandas at once. The second hands pandas your function and pandas calls it 255 times, once per value. For a one-line formula the first is faster and easier to read, and you should prefer it. <code>.apply()</code> earns its place when the operation cannot be written as arithmetic on a whole column, which is exactly what question 16 asks for.</p>
</div>
</div>
<p><strong>16. Write a function called <code>classify_ph</code> that takes a pH value and returns <code>'acidic'</code> below 6.5, <code>'alkaline'</code> above 7.5, and <code>'neutral'</code> in between. Apply it to the <code>pH</code> column, store the result in a column called <code>ph_class</code>, and report the counts.</strong></p>
<div id="f1ddf0ff" class="cell" data-execution_count="20">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> classify_ph(value):</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Label a pH value as acidic, neutral, or alkaline."""</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> value <span class="op">&lt;</span> <span class="fl">6.5</span>:</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'acidic'</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> value <span class="op">&gt;</span> <span class="fl">7.5</span>:</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'alkaline'</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'neutral'</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'ph_class'</span>] <span class="op">=</span> survey[<span class="st">'pH'</span>].<span class="bu">apply</span>(classify_ph)</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>survey[<span class="st">'ph_class'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>ph_class
neutral     171
acidic       42
alkaline     42
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>171 neutral, 42 acidic and 42 alkaline</strong>, which adds to 255, so every row was classified and none returned <code>None</code>. The two tails are the same size, which is a reassuring sign that the thresholds are placed sensibly for this dataset rather than cutting it in an arbitrary place.</p>
<p>Watch the boundaries. The function uses strict <code>&lt;</code> and <code>&gt;</code>, so a sample sitting at exactly 6.5 is labelled neutral, and two rows in this table are at exactly 6.5. Had you written <code>&lt;=</code>, your acidic count would be 44 and not 42. The comparison you choose is part of the definition, so say in your notebook which side the boundary falls on.</p>
</div>
</div>
</section>
<section id="part-4-ask-it-something" class="level2">
<h2 class="anchored" data-anchor-id="part-4-ask-it-something">Part 4: Ask it something</h2>
<p><strong>17. Use the filter pattern to build a table of just the acidic samples. Which sites do they come from? Use <code>.value_counts()</code> on <code>site</code>.</strong></p>
<div id="8bd1adde" class="cell" data-execution_count="21">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>acidic <span class="op">=</span> survey[survey[<span class="st">'ph_class'</span>] <span class="op">==</span> <span class="st">'acidic'</span>]</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>acidic[<span class="st">'site'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>site
site_f    27
site_c    14
site_e     1
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Almost all of them come from two sites: <code>site_f</code> with 27 and <code>site_c</code> with 14, plus a single sample from <code>site_e</code>.</strong> That is 41 of the 42 acidic samples in two of the six sites, and three sites contribute none at all.</p>
<p>The clustering looks like a real spatial pattern rather than noise. Acidity is a property of these two streams, not something scattered evenly across the survey, and it is the first result in this exercise that you could not have obtained from the file as it arrived. With 36 site labels, <code>site_f</code> alone was split across six spellings.</p>
</div>
</div>
<p><strong>18. Two of the six sites account for nearly all the acidic samples. Take either one of those two, and compare it against <code>site_d</code>, which is not one of them: filter to each in turn and compare the mean of <code>dissolved_oxygen_mg_L</code>. (Two filters, two <code>.mean()</code> calls. Tomorrow you will learn to do all six at once.)</strong></p>
<div id="a7923ff6" class="cell" data-execution_count="22">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>site_f <span class="op">=</span> survey[survey[<span class="st">'site'</span>] <span class="op">==</span> <span class="st">'site_f'</span>]</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>site_d <span class="op">=</span> survey[survey[<span class="st">'site'</span>] <span class="op">==</span> <span class="st">'site_d'</span>]</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'site_f mean DO:'</span>, site_f[<span class="st">'dissolved_oxygen_mg_L'</span>].mean())</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'site_d mean DO:'</span>, site_d[<span class="st">'dissolved_oxygen_mg_L'</span>].mean())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>site_f mean DO: 6.180232558139535
site_d mean DO: 10.053333333333333</code></pre>
</div>
</div>
<div id="44aa5aab" class="cell" data-execution_count="23">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'site_f mean temperature:'</span>, site_f[<span class="st">'temperature_c'</span>].mean())</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'site_d mean temperature:'</span>, site_d[<span class="st">'temperature_c'</span>].mean())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>site_f mean temperature: 23.297674418604654
site_d mean temperature: 15.179487179487179</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong><code>site_d</code> averages 10.05 mg/L of dissolved oxygen and <code>site_f</code> averages 6.18 mg/L</strong>, a difference of 3.87 mg/L. <code>site_d</code> holds roughly 1.6 times as much oxygen as <code>site_f</code>, and 6 mg/L is around the level below which cold-water fish are stressed, so the gap is biologically meaningful and not merely a number.</p>
<p>The second cell gives the reason. <code>site_f</code> averages 23.30 °C and <code>site_d</code> averages 15.18 °C, a difference of 8.1 degrees, and the two rankings run in opposite directions. Warm water holds less dissolved gas, so the site with the highest temperature has the lowest oxygen. When you rank all six sites with <code>.groupby()</code> tomorrow, you will find the two orderings are exact mirrors of each other, with the coolest site the most oxygenated and the warmest the least, and no site out of place.</p>
<p>If you picked <code>site_c</code> rather than <code>site_f</code>, the argument is the same and the numbers are smaller: <code>site_c</code> averages 6.87 mg/L against <code>site_d</code>’s 10.05, a difference of 3.18 mg/L, and it runs 21.91 °C against 15.18 °C. Either choice shows the same relationship.</p>
<p>The comparison between sites is what the afternoon of cleaning made possible, and it is only visible because 36 site labels became six. Before you cleaned the column, <code>site_f</code> was six separate groups, the largest of them 12 rows, and no comparison between sites was possible at all.</p>
</div>
</div>
<p><strong>19. In a markdown cell of three or four sentences: what would you tell the PI whose project collected this data? Name the single change to their field sheet that would have saved you the most time this afternoon, and describe what evidence in the file makes you pick that one.</strong></p>
<p>There is no single right answer here. A strong response names one change, cites a number from your own output as the evidence, and explains why that change beats the runners-up. Here is one that would earn full marks.</p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ A model answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ A model answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>Print the six site codes on the sheet with a tick box next to each one, so that nobody ever writes a site name by hand again. The evidence is that six sites arrived as 36 distinct labels, and repairing them took three separate operations for three separate kinds of damage. The worst of those was whitespace, which <code>.value_counts()</code> shows as two identical-looking rows and only <code>.unique()</code> reveals, so it is the error most likely to survive into a published analysis.</p>
<p>The change also protects the result rather than only my time. Every comparison between sites in Part 4 was impossible until that column was consistent, because <code>site_f</code> was six groups of at most 12 rows.</p>
<p>The runner-up is the decimal comma in <code>pH</code>, which affected 24 values, and a sheet that showed <code>_ . _ _</code> in the pH box would have prevented it. I would still rank the site codes first, because a wrong pH format raises an error and the whole column fails to convert, while a trailing space raises no error and splits your data without warning. The <code>-999</code> temperatures are the logger’s doing rather than the transcriber’s, so I would raise those with whoever maintains the instrument.</p>
</div>
</div>
</section>
<section id="if-you-finish-early" class="level2">
<h2 class="anchored" data-anchor-id="if-you-finish-early">If you finish early</h2>
<p><strong>Would you get the same final table if you had filtered out the sentinel temperatures first, before the <code>.dropna()</code> in task 9? Does the order of cleaning steps matter here, and would you expect that to be true in general?</strong></p>
<div id="9160ee19" class="cell" data-execution_count="24">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>check <span class="op">=</span> pd.read_csv(url).drop_duplicates()</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>check[<span class="st">'site'</span>] <span class="op">=</span> check[<span class="st">'site'</span>].<span class="bu">str</span>.strip().<span class="bu">str</span>.lower().<span class="bu">str</span>.replace(<span class="st">'-'</span>, <span class="st">'_'</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>check[<span class="st">'pH'</span>] <span class="op">=</span> check[<span class="st">'pH'</span>].<span class="bu">str</span>.replace(<span class="st">','</span>, <span class="st">'.'</span>).astype(<span class="bu">float</span>)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>check <span class="op">=</span> check[check[<span class="st">'temperature_c'</span>] <span class="op">&gt;</span> <span class="op">-</span><span class="dv">100</span>]</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'after filtering first:'</span>, check.shape)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>check <span class="op">=</span> check.dropna(subset<span class="op">=</span>[<span class="st">'temperature_c'</span>, <span class="st">'dissolved_oxygen_mg_L'</span>, <span class="st">'conductivity_uS_cm'</span>])</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'after dropna second: '</span>, check.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>after filtering first: (273, 7)
after dropna second:  (255, 7)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The same 255 rows, in the same order.</strong> Both steps are row selections that read the table without changing any value in it, so the surviving rows are the intersection of the two conditions, and an intersection does not care which condition you apply first.</p>
<p>The intermediate number does change: filtering first leaves 273 rows rather than 264. The reason is that <code>-999 &gt; -100</code> is <code>False</code> and <code>NaN &gt; -100</code> is also <code>False</code>, so the comparison removes the 18 rows with a missing temperature as well as the 9 sentinels, without saying so. Reversing the order moves 18 rows from one step’s tally to the other’s, which is worth knowing if you are reporting how many rows each step cost.</p>
<p>In general order does matter, and the safe rule is that it is only free when every step is a pure selection. As soon as a step fills a value, derives a column or converts a dtype, the steps stop commuting. Task 10 is the clear case in this exercise: <code>.fillna(1)</code> then <code>.astype(int)</code> works, and the same two lines in the other order raises an error.</p>
</div>
</div>
</section>
<section id="where-the-marks-are" class="level2">
<h2 class="anchored" data-anchor-id="where-the-marks-are">Where the marks are</h2>
<p>If you compare your notebook against this key, look for these four things before you look at anything else.</p>
<ol type="1">
<li><strong>Your notebook records the row count after every step that removed rows</strong>, and you can say where the 65 lost rows went: 320 to 300 to 264 to 255, which is 20 duplicates, 36 rows with no measurement, and 9 rows with a broken logger reading.</li>
<li><strong>You found all three kinds of damage in the <code>site</code> column</strong>, including the whitespace that <code>.value_counts()</code> cannot show you. Six labels at 50 rows each is the check.</li>
<li><strong>You recognised <code>-999</code> as missing data rather than as an outlier</strong>, and your task 12 sentence says what it did to the mean and to the standard deviation.</li>
<li><strong>Your interpretation answers say what the number means</strong>, not what the number is. “site_f averages 6.18 mg/L” restates the output. “site_f averages 6.18 mg/L, the lowest of the six sites, and it is also the warmest at 23.30 °C” reads it.</li>
</ol>
<p>⬅️ Back to <a href="../../course-materials/coding-colabs/4d_cleaning_messy_data.html">the colab</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><img src="../../images/bren-logo.png" alt="The Bren School of Environmental Science &amp; Management logo" width="250"></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This website is built with <a href="https://github.com/EDS-217-Essential-Python/EDS-217-Essential-Python.github.io"><i class="fa-brands fa-github" title="the github octocat logo" aria-label="github"></i></a> and <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>