<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Answer Key</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../course-materials/assets/css/exercises.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">EDS 217</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">🏠 home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-daily-materials" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">🗓️ daily materials</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-daily-materials">    
        <li>
    <a class="dropdown-item" href="../../course-materials/day1.html">
 <span class="dropdown-text">1️⃣ Day 1 (8/31)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day2.html">
 <span class="dropdown-text">2️⃣ Day 2 (9/1)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day3.html">
 <span class="dropdown-text">3️⃣ Day 3 (9/2)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day4.html">
 <span class="dropdown-text">4️⃣ Day 4 (9/3)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day5.html">
 <span class="dropdown-text">5️⃣ Day 5 (9/4)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day6.html">
 <span class="dropdown-text">6️⃣ Day 6 (9/8)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day7.html">
 <span class="dropdown-text">7️⃣ Day 7 (9/9)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day8.html">
 <span class="dropdown-text">8️⃣ Day 8 (9/10)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day9.html">
 <span class="dropdown-text">9️⃣ Day 9 (9/11)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-interactive-sessions" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">💻 interactive sessions</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-interactive-sessions">    
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1a_positron_notebooks.html">
 <span class="dropdown-text">Session 1a - ⚒️ Positron &amp; Jupyter Notebooks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1b_python_essentials.html">
 <span class="dropdown-text">Session 1b - 🐍 Python Essentials</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1c_data_science_workflow_1.html">
 <span class="dropdown-text">Session 1c - 🎬 The Python Data Science Workflow, Part 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1d_data_science_workflow_2.html">
 <span class="dropdown-text">Session 1d - 🎬 The Python Data Science Workflow, Part 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/2a_reading_data.html">
 <span class="dropdown-text">Session 2a - 🐼 Reading Data into pandas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/2b_exploring_data.html">
 <span class="dropdown-text">Session 2b - 🔎 Exploring a DataFrame</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/2d_lists_and_dicts.html">
 <span class="dropdown-text">Session 2d - 📝 Lists &amp; Dictionaries</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/3a_booleans_and_conditionals.html">
 <span class="dropdown-text">Session 3a - 📝 Booleans &amp; Conditionals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/3b_filtering_data.html">
 <span class="dropdown-text">Session 3b - 🔍 The Filter Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/3c_sorting_and_ranking.html">
 <span class="dropdown-text">Session 3c - 🥇 The Top-N Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4a_cleaning_data.html">
 <span class="dropdown-text">Session 4a - 🧼 Missing, Duplicated, Miscast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4b_functions.html">
 <span class="dropdown-text">Session 4b - ⚙️ Write It Once, Name It, Use It</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4c_transforming_data.html">
 <span class="dropdown-text">Session 4c - ➕ The Derived-Column Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/5a_grouping_data.html">
 <span class="dropdown-text">Session 5a - 🗂️ The Split-Apply-Combine Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/5b_aggregating_data.html">
 <span class="dropdown-text">Session 5b - 📊 Several Answers at Once</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/5d_loops_over_groups.html">
 <span class="dropdown-text">Session 5d - 🔁 When a Pattern Is Not Enough</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6a_joining_data.html">
 <span class="dropdown-text">Session 6a - 🔗 The Join Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6b_reshaping_data.html">
 <span class="dropdown-text">Session 6b - 🧩 Long and Wide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6c_dates.html">
 <span class="dropdown-text">Session 6c - 📆 A Date Is Not a Number</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7a_matplotlib.html">
 <span class="dropdown-text">Session 7a - 🖼️ The Anatomy of a Figure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7b_seaborn.html">
 <span class="dropdown-text">Session 7b - 🎨 Name the Columns, Not the Colours</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7d_project_kickoff.html">
 <span class="dropdown-text">Session 7d - 🚀 Project Kickoff</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-coding-colabs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">🙌 coding colabs</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-coding-colabs">    
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/2c_exploring_unfamiliar_data.html">
 <span class="dropdown-text">🙌 Session 2c - Five Claims About a Dataset You’ve Never Seen</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/3d_ranking_questions.html">
 <span class="dropdown-text">🙌 Session 3d - Which One, and How Do You Know?</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/4d_cleaning_messy_data.html">
 <span class="dropdown-text">🙌 Session 4d - From Field Sheet to DataFrame</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/5c_grouped_comparisons.html">
 <span class="dropdown-text">🙌 Session 5c - The Comparison You Made Yesterday, Properly</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/6d_two_table_exercise.html">
 <span class="dropdown-text">🙌 Session 6d - Two Records, Sixty-Six Years Apart</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/7c_penguins.html">
 <span class="dropdown-text">🙌 Session 7c - One Cloud of Points, Three Species</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../cheatsheets.html"> 
<span class="menu-text">👀 cheatsheets</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-resources" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">📚 resources</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-resources">    
        <li>
    <a class="dropdown-item" href="https://docs.python.org/3/" target="_blank">
 <span class="dropdown-text">📚 Python Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pandas.pydata.org/docs/" target="_blank">
 <span class="dropdown-text">📚 Pandas Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://numpy.org/doc/stable/" target="_blank">
 <span class="dropdown-text">📚 Numpy Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://matplotlib.org/stable/contents.html" target="_blank">
 <span class="dropdown-text">📚 Matplotlib Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://seaborn.pydata.org/" target="_blank">
 <span class="dropdown-text">📚 Seaborn Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://positron.posit.co/" target="_blank">
 <span class="dropdown-text">📚 Positron Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://docs.anaconda.com/" target="_blank">
 <span class="dropdown-text">📚 Anaconda Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://stackoverflow.com/" target="_blank">
 <span class="dropdown-text">📚 Stack Overflow</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://realpython.com/" target="_blank">
 <span class="dropdown-text">📚 Real Python</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://towardsdatascience.com/" target="_blank">
 <span class="dropdown-text">📚 Towards Data Science</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.datacamp.com/" target="_blank">
 <span class="dropdown-text">📚 DataCamp</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.kaggle.com/" target="_blank">
 <span class="dropdown-text">📚 Kaggle</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="http://pythontutor.com/" target="_blank">
 <span class="dropdown-text">🧰 Python Tutor</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pandastutor.com/vis.html#" target="_blank">
 <span class="dropdown-text">🧰 Pandas Tutor</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://wesmckinney.com/book/" target="_blank">
 <span class="dropdown-text">📙 Python for Data Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://jakevdp.github.io/PythonDataScienceHandbook/" target="_blank">
 <span class="dropdown-text">📙 Python for Data Science Handbook</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/jakevdp/PythonDataScienceHandbook" target="_blank">
 <span class="dropdown-text">📙 Python Data Science Handbook (GitHub)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://talkpython.fm/" target="_blank">
 <span class="dropdown-text">📻 Talk Python to Me</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/EDS-217-Essential-Python/EDS-217-Essential-Python.github.io" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-left">
      <h1 class="title">Answer Key</h1>
            <p class="subtitle lead">🙌 The Comparison You Made Yesterday, Properly</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta column-page-left">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#setup" id="toc-setup" class="nav-link active" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#part-1-all-four-oceans-at-once" id="toc-part-1-all-four-oceans-at-once" class="nav-link" data-scroll-target="#part-1-all-four-oceans-at-once">Part 1: All four oceans at once</a></li>
  <li><a href="#part-2-one-call-instead-of-four" id="toc-part-2-one-call-instead-of-four" class="nav-link" data-scroll-target="#part-2-one-call-instead-of-four">Part 2: One call instead of four</a></li>
  <li><a href="#part-3-where-our-answers-fall-apart" id="toc-part-3-where-our-answers-fall-apart" class="nav-link" data-scroll-target="#part-3-where-our-answers-fall-apart">Part 3: Where our answers fall apart</a></li>
  <li><a href="#part-4-write-it-again" id="toc-part-4-write-it-again" class="nav-link" data-scroll-target="#part-4-write-it-again">Part 4: Write it again</a></li>
  <li><a href="#if-you-finish-early" id="toc-if-you-finish-early" class="nav-link" data-scroll-target="#if-you-finish-early">If you finish early</a></li>
  <li><a href="#where-the-marks-are" id="toc-where-the-marks-are" class="nav-link" data-scroll-target="#where-the-marks-are">Where the marks are</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block column-page-left" id="quarto-document-content">





<div class="callout callout-style-default callout-important callout-titled" title="How to use this key">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How to use this key
</div>
</div>
<div class="callout-body-container callout-body">
<p>Work the colab through with your partner first, then come here. The code below is <strong>one</strong> correct answer, not the only one. The colab you just worked is a 45 minute pair exercise with very little scaffolding, so there are several reasonable ways to write almost every cell. If your code looks different but produces the same numbers, you were right.</p>
<p>The written answers matter more than the code. You can already tell whether your code ran. What you cannot check on your own is whether you read the result correctly, and that is what the green <strong>Answer</strong> boxes are for. Compare your markdown cells against them.</p>
<p>⬅️ Back to <a href="../../course-materials/coding-colabs/5c_grouped_comparisons.html">the colab</a></p>
</div>
</div>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<div id="d8ddc12d" class="cell" data-execution_count="1">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="st">'https://eds-217-essential-python.github.io/data/marine_microplastics.csv'</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(url)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.dropna(subset<span class="op">=</span>[<span class="st">'Measurement'</span>])</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>samples <span class="op">=</span> df[df[<span class="st">'Unit'</span>] <span class="op">==</span> <span class="st">'pieces/m3'</span>].copy()</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>samples[<span class="st">'ocean'</span>] <span class="op">=</span> samples[<span class="st">'Oceans'</span>].<span class="bu">str</span>.replace(<span class="st">' Ocean'</span>, <span class="st">''</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>positive <span class="op">=</span> samples[samples[<span class="st">'Measurement'</span>] <span class="op">&gt;</span> <span class="dv">0</span>].copy()</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>positive.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>(7091, 23)</code></pre>
</div>
</div>
</section>
<section id="part-1-all-four-oceans-at-once" class="level2">
<h2 class="anchored" data-anchor-id="part-1-all-four-oceans-at-once">Part 1: All four oceans at once</h2>
<p><strong>1. Yesterday you computed the mean <code>Measurement</code> for the Atlantic and the Pacific with two filters. Now do all four oceans in one line, and rank the result from dirtiest to cleanest.</strong></p>
<div id="e5abd211" class="cell" data-execution_count="2">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>positive.groupby(<span class="st">'ocean'</span>)[<span class="st">'Measurement'</span>].mean().sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="2">
<pre><code>ocean
Pacific     595.199821
Atlantic    282.729748
Arctic        2.279608
Southern      0.075703
Name: Measurement, dtype: float64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Pacific 595.2, Atlantic 282.7, Arctic 2.28, Southern 0.076 pieces/m3.</strong> One line replaces the two filters, two subsets and two <code>.describe()</code> calls you wrote yesterday, and it also gives you the two oceans you did not ask about. The spread is the first thing to notice: the Pacific mean is nearly eight thousand times the Southern mean, which is a larger difference than any plausible difference in ocean water, and should make you suspicious before you go any further.</p>
</div>
</div>
<p><strong>2. Do the same with the median instead of the mean. Does the order change? If so, which two oceans swap?</strong></p>
<div id="dfa44ada" class="cell" data-execution_count="3">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>positive.groupby(<span class="st">'ocean'</span>)[<span class="st">'Measurement'</span>].median().sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>ocean
Pacific     0.116665
Arctic      0.044000
Atlantic    0.019440
Southern    0.011500
Name: Measurement, dtype: float64</code></pre>
</div>
</div>
<div id="5354c3e7" class="cell" data-execution_count="4">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>means <span class="op">=</span> positive.groupby(<span class="st">'ocean'</span>)[<span class="st">'Measurement'</span>].mean()</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>medians <span class="op">=</span> positive.groupby(<span class="st">'ocean'</span>)[<span class="st">'Measurement'</span>].median()</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'mean ratio:  '</span>, means[<span class="st">'Pacific'</span>] <span class="op">/</span> means[<span class="st">'Atlantic'</span>])</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'median ratio:'</span>, medians[<span class="st">'Pacific'</span>] <span class="op">/</span> medians[<span class="st">'Atlantic'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>mean ratio:   2.1051899432448007
median ratio: 6.001286008230453</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The Arctic and the Atlantic swap.</strong> By mean the Atlantic is second at 282.7 and the Arctic third at 2.28; by median the Arctic is second at 0.0440 and the Atlantic third at 0.0194 pieces/m3.</p>
<p>The Pacific-to-Atlantic ratio is <strong>2.11 on the means and 6.00 on the medians</strong>, so the choice of average changes the size of the claim by a factor of about three. Note also how far the two averages are from each other within a single ocean: the Atlantic mean is 282.7 and the Atlantic median is 0.0194, roughly fifteen thousand times smaller. A gap that large between mean and median always means a few enormous values, and it is a warning that the mean is describing those values rather than the ocean.</p>
</div>
</div>
<p><strong>3. How many samples went into each of those four numbers? (can/should be a single line of code!)</strong></p>
<div id="c15b046e" class="cell" data-execution_count="5">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>positive.groupby(<span class="st">'ocean'</span>)[<span class="st">'Measurement'</span>].count().sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>ocean
Atlantic    6216
Pacific      799
Arctic        58
Southern      18
Name: Measurement, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Atlantic 6,216, Pacific 799, Arctic 58, Southern 18.</strong> The four numbers you have been ranking rest on wildly different amounts of evidence: the Atlantic alone is 88% of this table, and the Arctic and Southern together are 76 rows, about 1% of the 7,091. <code>.count()</code> costs one line and tells you which rows of a grouped table you are allowed to take seriously.</p>
</div>
</div>
<p><strong>4. In a markdown cell: two of the four oceans have numbers you should refuse to report. Name those two oceans and explain why in one sentence.</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The Arctic (58 samples) and the Southern Ocean (18 samples).</strong> Both are too thin to describe an ocean: the Southern figure comes from 18 samples collected by three organizations, 14 of them by one method, so it describes a handful of cruises rather than a body of water covering twenty million square kilometres. A grouped table prints a number for every group it finds, whether or not that group has enough rows to support one, so reading the <code>count</code> column is part of reading the result.</p>
</div>
</div>
</section>
<section id="part-2-one-call-instead-of-four" class="level2">
<h2 class="anchored" data-anchor-id="part-2-one-call-instead-of-four">Part 2: One call instead of four</h2>
<p><strong>5. Replace questions 1 through 3 with a single <code>.agg()</code> call that reports the count, median, mean and max of <code>Measurement</code> for each ocean.</strong></p>
<div id="99fe07a8" class="cell" data-execution_count="6">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>positive.groupby(<span class="st">'ocean'</span>)[<span class="st">'Measurement'</span>].agg([<span class="st">'count'</span>, <span class="st">'median'</span>, <span class="st">'mean'</span>, <span class="st">'max'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">median</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">max</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">ocean</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Arctic</td>
<td>58</td>
<td>0.044000</td>
<td>2.279608</td>
<td>63.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Atlantic</td>
<td>6216</td>
<td>0.019440</td>
<td>282.729748</td>
<td>110480.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Pacific</td>
<td>799</td>
<td>0.116665</td>
<td>595.199821</td>
<td>21156.558533</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Southern</td>
<td>18</td>
<td>0.011500</td>
<td>0.075703</td>
<td>0.499663</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>6. Look at the Atlantic row’s median and maximum. In a markdown cell, explain what a single large number does to a mean computed from 6,216 values. Which of the two measures of central tendency (mean vs.&nbsp;median) would you send to the journalist?</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The single largest Atlantic sample, 110,480, contributes about 17.8 to the mean of 282.7, which is 6% of it, and the ten largest values together contribute 38%.</strong> A mean adds every value and divides by the count. Dividing 110,480 by 6,216 leaves 17.8, which is a tiny fraction of where it started and still nine hundred times the median of 0.0194. One sample survives the averaging as a large number because it began so far from everything else. The result is a mean that only 294 of the 6,216 Atlantic samples, under 5%, actually exceed. An average that is larger than 95% of the data is not describing a typical sample.</p>
<p><strong>Send the median, 0.0194 pieces/m3</strong>, and say how many samples it came from. If the journalist wants the extremes, give them the maximum separately as a maximum, which is an honest way to report a large number without letting it stand in for the ocean.</p>
</div>
</div>
<p><strong>7. Use the dictionary form of <code>.agg()</code>, grouped by <code>ocean</code>, to report the mean <code>Measurement</code>, the number of distinct <code>Sampling Method</code> values, and the number of distinct <code>Organization</code> values in each ocean.</strong></p>
<div id="06f0a79b" class="cell" data-execution_count="7">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>positive.groupby(<span class="st">'ocean'</span>).agg({</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Measurement'</span>: <span class="st">'mean'</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Sampling Method'</span>: <span class="st">'nunique'</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Organization'</span>: <span class="st">'nunique'</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Measurement</th>
<th data-quarto-table-cell-role="th">Sampling Method</th>
<th data-quarto-table-cell-role="th">Organization</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">ocean</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Arctic</td>
<td>2.279608</td>
<td>4</td>
<td>3</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Atlantic</td>
<td>282.729748</td>
<td>10</td>
<td>20</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Pacific</td>
<td>595.199821</td>
<td>7</td>
<td>9</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Southern</td>
<td>0.075703</td>
<td>2</td>
<td>3</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>8. In a markdown cell explain the value of asking for these non-measurement summary data. What might it mean if one ocean had been sampled by only one organization using a single method?</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>They describe <strong>how the number was produced rather than what was measured</strong>, and that is exactly what you need in order to decide whether two oceans can be compared. The Atlantic figure comes from 20 organizations using 10 methods; the Southern figure comes from 3 organizations using 2.</p>
<p>If an ocean had one organization and one method, its mean would be a property of that study, not of that ocean: any habit of that group, any bias in that instrument, would be inseparable from the result, and there would be no second measurement to check it against. The Southern Ocean is close enough to that situation to be worth the caution. <code>nunique</code> on a non-numeric column is a cheap way to ask “how many independent sources agree with this?” before you quote it.</p>
</div>
</div>
</section>
<section id="part-3-where-our-answers-fall-apart" class="level2">
<h2 class="anchored" data-anchor-id="part-3-where-our-answers-fall-apart">Part 3: Where our answers fall apart</h2>
<p><strong>9. Group by <code>Sampling Method</code> instead of by ocean, and report the count and median of <code>Measurement</code> for each method. Rank by median, largest first.</strong></p>
<div id="caeabeab" class="cell" data-execution_count="8">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>by_method <span class="op">=</span> positive.groupby(<span class="st">'Sampling Method'</span>)[<span class="st">'Measurement'</span>].agg([<span class="st">'count'</span>, <span class="st">'median'</span>])</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>by_method.sort_values(<span class="st">'median'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">median</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Sampling Method</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Stainless steel spoon</td>
<td>50</td>
<td>21840.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Van Dorn sampler</td>
<td>84</td>
<td>2000.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Aluminum bucket</td>
<td>57</td>
<td>1710.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">PVC cylinder</td>
<td>292</td>
<td>1410.437236</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">CTD rosette sampler</td>
<td>4</td>
<td>21.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Intake seawater pump</td>
<td>115</td>
<td>2.500000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Plankton net</td>
<td>74</td>
<td>0.840000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Hand picking</td>
<td>12</td>
<td>0.777778</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Manta net</td>
<td>884</td>
<td>0.252943</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">AVANI net</td>
<td>18</td>
<td>0.047533</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Neuston net</td>
<td>4552</td>
<td>0.015120</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Grab sample</td>
<td>949</td>
<td>0.006000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>10. Write down the largest and smallest medians in that table. How many orders of magnitude separate them? (<code>np.log10</code> of the ratio will tell you, or count the zeros.)</strong></p>
<div id="f8b4e5bd" class="cell" data-execution_count="9">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>medians_by_method <span class="op">=</span> positive.groupby(<span class="st">'Sampling Method'</span>)[<span class="st">'Measurement'</span>].median()</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(medians_by_method.<span class="bu">max</span>(), medians_by_method.<span class="bu">min</span>())</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.log10(medians_by_method.<span class="bu">max</span>() <span class="op">/</span> medians_by_method.<span class="bu">min</span>()))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>21840.0 0.006
6.561101383649056</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>21,840 pieces/m3 for the stainless steel spoon and 0.0060 for the grab sample: 6.56 on a log10 scale, so more than six orders of magnitude, a factor of about 3.6 million.</strong></p>
<p>The methods sort into two families, and the reason is physical. The spoon, the Van Dorn sampler (2,000), the aluminum bucket (1,710) and the PVC cylinder (1,410) all scoop a small, fixed volume of surface water and count everything in it, including fibres a few tenths of a millimetre long. The nets, Manta at 0.253, Neuston at 0.0151, AVANI at 0.0475, tow a mesh through hundreds of cubic metres and keep only what the mesh cannot pass. Both report pieces per cubic metre, and the unit column says they are comparable, but they are counting different objects. No difference between oceans in this file is anywhere near six orders of magnitude, so method is the largest single influence on <code>Measurement</code> in the dataset.</p>
</div>
</div>
<p><strong>11. In a markdown cell, before you write any more code: if the oceans were not sampled with the same mix of methods, what might that imply regarding your answer from question 1? Two or three sentences.</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ A model answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ A model answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>It makes question 1 partly a comparison of sampling methods labelled as a comparison of oceans. If one ocean happens to have more bucket and cylinder samples, its mean will be higher no matter what is in the water, because those methods report values thousands of times larger than the nets do. The ocean means would then be measuring the composition of the sampling effort as much as the plastic, and I cannot tell which until I count the methods within each ocean.</p>
<p>Full marks here are for writing the prediction <strong>before</strong> running question 12 and for naming the mechanism, not just the risk. Writing the prediction down and then testing it is how you find a confound, rather than only naming one.</p>
</div>
</div>
<p><strong>12. Let’s see if we can determine the impact of measurement method. Group by both <code>ocean</code> and <code>Sampling Method</code> at once and count the samples. Then call <code>.reset_index()</code> on the result and look at the Atlantic and Pacific rows.</strong></p>
<div id="c3bdc9d4" class="cell" data-execution_count="10">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>ocean_method <span class="op">=</span> positive.groupby([<span class="st">'ocean'</span>, <span class="st">'Sampling Method'</span>])[<span class="st">'Measurement'</span>].count()</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>ocean_method.reset_index().head(<span class="dv">15</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ocean</th>
<th data-quarto-table-cell-role="th">Sampling Method</th>
<th data-quarto-table-cell-role="th">Measurement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Arctic</td>
<td>CTD rosette sampler</td>
<td>4</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Arctic</td>
<td>Grab sample</td>
<td>21</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Arctic</td>
<td>Intake seawater pump</td>
<td>6</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Arctic</td>
<td>Manta net</td>
<td>27</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Atlantic</td>
<td>Aluminum bucket</td>
<td>57</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Atlantic</td>
<td>Grab sample</td>
<td>748</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>Atlantic</td>
<td>Hand picking</td>
<td>12</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>Atlantic</td>
<td>Intake seawater pump</td>
<td>106</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>Atlantic</td>
<td>Manta net</td>
<td>631</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>Atlantic</td>
<td>Neuston net</td>
<td>4390</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>Atlantic</td>
<td>PVC cylinder</td>
<td>104</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>Atlantic</td>
<td>Plankton net</td>
<td>34</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>Atlantic</td>
<td>Stainless steel spoon</td>
<td>50</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>Atlantic</td>
<td>Van Dorn sampler</td>
<td>84</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>Pacific</td>
<td>AVANI net</td>
<td>18</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="d85a6218" class="cell" data-execution_count="11">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>ocean_method.reset_index()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">ocean</th>
<th data-quarto-table-cell-role="th">Sampling Method</th>
<th data-quarto-table-cell-role="th">Measurement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Arctic</td>
<td>CTD rosette sampler</td>
<td>4</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Arctic</td>
<td>Grab sample</td>
<td>21</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Arctic</td>
<td>Intake seawater pump</td>
<td>6</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Arctic</td>
<td>Manta net</td>
<td>27</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Atlantic</td>
<td>Aluminum bucket</td>
<td>57</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Atlantic</td>
<td>Grab sample</td>
<td>748</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>Atlantic</td>
<td>Hand picking</td>
<td>12</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>Atlantic</td>
<td>Intake seawater pump</td>
<td>106</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>Atlantic</td>
<td>Manta net</td>
<td>631</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>Atlantic</td>
<td>Neuston net</td>
<td>4390</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>Atlantic</td>
<td>PVC cylinder</td>
<td>104</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>Atlantic</td>
<td>Plankton net</td>
<td>34</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>Atlantic</td>
<td>Stainless steel spoon</td>
<td>50</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>Atlantic</td>
<td>Van Dorn sampler</td>
<td>84</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>Pacific</td>
<td>AVANI net</td>
<td>18</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>Pacific</td>
<td>Grab sample</td>
<td>166</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">16</td>
<td>Pacific</td>
<td>Intake seawater pump</td>
<td>3</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">17</td>
<td>Pacific</td>
<td>Manta net</td>
<td>226</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">18</td>
<td>Pacific</td>
<td>Neuston net</td>
<td>158</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">19</td>
<td>Pacific</td>
<td>PVC cylinder</td>
<td>188</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">20</td>
<td>Pacific</td>
<td>Plankton net</td>
<td>40</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">21</td>
<td>Southern</td>
<td>Grab sample</td>
<td>14</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">22</td>
<td>Southern</td>
<td>Neuston net</td>
<td>4</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The two oceans were sampled with almost opposite method mixes.</strong> The full table is 23 rows, one per ocean and method pair that actually occurs, and <code>.head(15)</code> stops one row into the Pacific, which is why the second cell prints all of it.</p>
<p>The Atlantic is 4,390 Neuston net out of 6,216, then 748 grab samples and 631 Manta net: three low-reading methods account for 93% of it. The Pacific is spread across Manta 226, PVC cylinder 188, grab 166 and Neuston 158. The PVC cylinder row is the one to stop on: 188 of the Pacific’s 799 samples used a method whose median across the whole file is 1,410 pieces/m3, and the Pacific mean of 595 follows from that fact rather than from the Pacific. In the other direction, the stainless steel spoon and the Van Dorn sampler, the two highest medians in the file, appear in the Atlantic and in no other ocean, and so does the aluminum bucket.</p>
<p>Grouping by two keys is what made this visible. Either key on its own averages the other one away.</p>
</div>
</div>
<p><strong>13. Here’s a simpler and more direct approach: run <code>.value_counts()</code> on <code>Sampling Method</code> for the Atlantic samples and again for the Pacific samples. Which method dominates the Atlantic? What fraction of the Pacific samples used it?</strong></p>
<div id="7d00cb43" class="cell" data-execution_count="12">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>atlantic <span class="op">=</span> positive[positive[<span class="st">'ocean'</span>] <span class="op">==</span> <span class="st">'Atlantic'</span>]</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>pacific <span class="op">=</span> positive[positive[<span class="st">'ocean'</span>] <span class="op">==</span> <span class="st">'Pacific'</span>]</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(atlantic[<span class="st">'Sampling Method'</span>].value_counts())</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pacific[<span class="st">'Sampling Method'</span>].value_counts())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Sampling Method
Neuston net              4390
Grab sample               748
Manta net                 631
Intake seawater pump      106
PVC cylinder              104
Van Dorn sampler           84
Aluminum bucket            57
Stainless steel spoon      50
Plankton net               34
Hand picking               12
Name: count, dtype: int64
Sampling Method
Manta net               226
PVC cylinder            188
Grab sample             166
Neuston net             158
Plankton net             40
AVANI net                18
Intake seawater pump      3
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The Neuston net dominates the Atlantic, 4,390 of 6,216 samples, or 71%. In the Pacific it is 158 of 799, or 20%.</strong> The Atlantic is effectively one method with a few others attached; the Pacific is four methods of comparable size, and its most common one, the Manta net at 226, is not the Atlantic’s most common one.</p>
<p>The method mix alone is enough to explain the difference you reported yesterday without any reference to the amount of plastic in the water. The Neuston net has the second lowest median of any method in the file at 0.0151, so an ocean measured mostly by Neuston net will read low, and the Atlantic is that ocean.</p>
</div>
</div>
<p><strong>14. Now let’s control for these differences. Filter <code>positive</code> to the rows collected with a <code>'Neuston net'</code>, end the line with <code>.copy()</code>, then group that by ocean and report count, median and mean.</strong></p>
<div id="49d58708" class="cell" data-execution_count="13">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>neuston <span class="op">=</span> positive[positive[<span class="st">'Sampling Method'</span>] <span class="op">==</span> <span class="st">'Neuston net'</span>].copy()</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>neuston.groupby(<span class="st">'ocean'</span>)[<span class="st">'Measurement'</span>].agg([<span class="st">'count'</span>, <span class="st">'median'</span>, <span class="st">'mean'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">median</th>
<th data-quarto-table-cell-role="th">mean</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">ocean</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Atlantic</td>
<td>4390</td>
<td>0.015120</td>
<td>0.085767</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Pacific</td>
<td>158</td>
<td>0.030680</td>
<td>0.396195</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Southern</td>
<td>4</td>
<td>0.306271</td>
<td>0.278664</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="1f7d8997" class="cell" data-execution_count="14">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>neuston[neuston[<span class="st">'ocean'</span>] <span class="op">==</span> <span class="st">'Pacific'</span>][<span class="st">'Organization'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>Organization
5 Gyres Institute                                                         82
Sea Education Association                                                 69
Scripps Institution of Oceanography-University of California San Diego     7
Name: count, dtype: int64</code></pre>
</div>
</div>
<p><strong>15. In a markdown cell, write three or four sentences that compare this table with your answer to question 5. Does the Pacific still come out higher than the Atlantic? By how much, measured against the median ratio in your question 5 answer rather than against the mean ratio you sent the journalist yesterday? What happened to the number of Pacific samples you are now relying on?</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ A model answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ A model answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Yes, the Pacific is still higher than the Atlantic, but the claim shrinks from a factor of 6.0 to a factor of 2.0 and the evidence for it shrinks from 799 samples to 158.</strong> Look at the third row before you go on: the Southern Ocean has the highest Neuston median of the three, 0.306, and it rests on four samples. Restricting to one method has not stopped small groups producing large numbers; it has only made the comparison between the two big oceans a fair one. Within Neuston net samples only, the Pacific median is 0.0307 pieces/m3 against the Atlantic’s 0.0151. The gap is a real difference, it points the same way it did yesterday, and it is now a comparison of like with like.</p>
<p>The means change the most. They fall from 595.2 and 282.7 to <strong>0.396 and 0.0858</strong>, a drop of more than three orders of magnitude in each, and closer to four in the Atlantic, because the extreme values behind the question 5 means came from the scoop methods and not from the nets. The 2.1-fold difference in means you reported yesterday did not describe seawater. It described 188 PVC cylinder samples in the Pacific against 4,390 Neuston tows in the Atlantic.</p>
<p>So the effect <strong>survives the control and changes size</strong>, which is a different claim from either “the Pacific is dirtier” or “the difference was an artefact”. Both halves have to be said. And the 158 Pacific samples that support the surviving claim come from only three organizations, 82 of them from one, so this is not 158 independent lines of evidence. It is a difference worth reporting with its sample size attached and worth checking against another single method, for example the Manta net, before anyone builds on it.</p>
</div>
</div>
</section>
<section id="part-4-write-it-again" class="level2">
<h2 class="anchored" data-anchor-id="part-4-write-it-again">Part 4: Write it again</h2>
<p><strong>16. The journalist replies: “Thanks. My editor wants one sentence with a number in it.” Write that sentence in a markdown cell. It must contain a number, must name the sampling method you controlled for, and must not overstate what 158 samples can support.</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ A model answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ A model answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>Comparing only samples taken with a Neuston net, the one method used in both oceans in reasonable numbers, the median Pacific sample contains about twice as much floating plastic as the median Atlantic sample, 0.031 against 0.015 pieces per cubic metre, though the Pacific figure rests on 158 samples from three research groups and should be treated as provisional.</p>
<p>Full marks for a sentence that states all four things: the number, the method, the direction, and the limit. The common failure is dropping the last one, or quoting the mean because it sounds more impressive. The sentence must also survive the reader asking “compared with what?”, which is why the method is named inside it rather than in a footnote.</p>
</div>
</div>
<p><strong>17. In a markdown cell of four or five sentences: what changed between yesterday’s answer and this one, and was it the data or the question? Name the specific line of code that made the difference visible.</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ A model answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ A model answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>The data did not change. It is the same 7,091 rows and the same <code>Measurement</code> column, and yesterday’s arithmetic was correct: the Pacific mean really is 595.2 and the Atlantic mean really is 282.7. What changed is the question. Yesterday we asked which ocean has the larger average, and this afternoon I asked whether the two averages were produced in comparable ways, which is a question about the sampling rather than about the water.</p>
<p>The line that made it visible is:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>positive.groupby([<span class="st">'ocean'</span>, <span class="st">'Sampling Method'</span>])[<span class="st">'Measurement'</span>].count()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Grouping by two keys at once showed 4,390 Neuston tows in the Atlantic against 188 PVC cylinder samples in the Pacific, and once that table is on screen the ocean means cannot be read as ocean means. Question 14 then measured what was left after holding the method fixed: a two-fold difference in the medians, on 158 Pacific samples. The general lesson is that a <code>groupby</code> on one column silently averages over every column you did not group by, and if one of those columns drives the measurement, your comparison is partly about that column instead.</p>
</div>
</div>
</section>
<section id="if-you-finish-early" class="level2">
<h2 class="anchored" data-anchor-id="if-you-finish-early">If you finish early</h2>
<p><strong>Group by <code>Regions</code>, report count and median, and rank by count to find the ten most-sampled regions. Look at which sampling methods were used in the extremes.</strong></p>
<div id="50f873a6" class="cell" data-execution_count="15">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>by_region <span class="op">=</span> positive.groupby(<span class="st">'Regions'</span>)[<span class="st">'Measurement'</span>].agg([<span class="st">'count'</span>, <span class="st">'median'</span>])</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>by_region.sort_values(<span class="st">'count'</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="15">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">median</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Regions</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Caribbean Sea</td>
<td>873</td>
<td>0.006480</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Mediterranean Sea</td>
<td>340</td>
<td>0.557847</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Gulf of Mexico</td>
<td>263</td>
<td>1000.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">North Sea</td>
<td>158</td>
<td>0.022733</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Inner Seas off the West Coast of Scotland</td>
<td>154</td>
<td>0.046132</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Gulf of California</td>
<td>85</td>
<td>1410.437236</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Coastal Waters of Southeast Alaska and British Columbia</td>
<td>22</td>
<td>0.003500</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Celtic Sea</td>
<td>21</td>
<td>0.023467</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Irish Sea and St. George's Channel</td>
<td>20</td>
<td>0.056972</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Gulf of St. Lawrence</td>
<td>18</td>
<td>0.004546</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="295da191" class="cell" data-execution_count="16">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(positive[positive[<span class="st">'Regions'</span>] <span class="op">==</span> <span class="st">'Gulf of California'</span>][<span class="st">'Sampling Method'</span>].value_counts())</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(positive[positive[<span class="st">'Regions'</span>] <span class="op">==</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>               <span class="st">'Coastal Waters of Southeast Alaska and British Columbia'</span>][<span class="st">'Sampling Method'</span>].value_counts())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Sampling Method
PVC cylinder    70
Grab sample      9
Neuston net      6
Name: count, dtype: int64
Sampling Method
Grab sample    22
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The Gulf of California has a median of 1,410 pieces/m3 and coastal Alaska and British Columbia has 0.0035, a ratio of about 403,000.</strong> The same explanation as Part 3 applies, only more starkly: 70 of the Gulf of California’s 85 samples were taken with a PVC cylinder, and all 22 Alaska samples were grab samples. Grab sample is the very bottom of the method table from question 9, and the PVC cylinder is fourth from the top of it, behind the spoon, the Van Dorn sampler and the aluminium bucket.</p>
<p>The Gulf of Mexico row makes the point a third time, with a median of exactly 1,000.0 across 263 samples. A median that comes out as an exact round number usually reflects a reporting convention or a detection threshold rather than the water, and it is worth investigating before it goes into any comparison. Finer geography does not remove a method confound. It only makes the groups smaller, so the confound is harder to see.</p>
</div>
</div>
</section>
<section id="where-the-marks-are" class="level2">
<h2 class="anchored" data-anchor-id="where-the-marks-are">Where the marks are</h2>
<p>If you compare your notebook against this key, look for these four things before you look at anything else.</p>
<ol type="1">
<li><strong>Your question 15 answer says both halves.</strong> The Pacific is still higher after controlling for method, and the size of the difference falls from 6.0 to 2.0 while the sample count falls from 799 to 158. An answer that reports only the survival, or only the collapse, is half the finding.</li>
<li><strong>You read the <code>count</code> column of every grouped table before quoting a number from it.</strong> The Southern Ocean’s 18 rows and the Pacific’s 158 Neuston samples are the two places this matters most in the colab.</li>
<li><strong>You wrote your question 11 prediction before running question 12.</strong> The value of the exercise is in committing to an expectation and then testing it, not in the table itself.</li>
<li><strong>Your interpretation answers say what the number means</strong>, not what the number is. “The Pacific mean is 595.2” restates the output. “The Pacific mean is 595.2, and 188 of its 799 samples used a method whose median is 1,410” reads it.</li>
</ol>
<p>⬅️ Back to <a href="../../course-materials/coding-colabs/5c_grouped_comparisons.html">the colab</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><img src="../../images/bren-logo.png" alt="The Bren School of Environmental Science &amp; Management logo" width="250"></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This website is built with <a href="https://github.com/EDS-217-Essential-Python/EDS-217-Essential-Python.github.io"><i class="fa-brands fa-github" title="the github octocat logo" aria-label="github"></i></a> and <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>