<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Answer Key</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../course-materials/assets/css/exercises.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">EDS 217</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">🏠 home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-daily-materials" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">🗓️ daily materials</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-daily-materials">    
        <li>
    <a class="dropdown-item" href="../../course-materials/day1.html">
 <span class="dropdown-text">1️⃣ Day 1 (8/31)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day2.html">
 <span class="dropdown-text">2️⃣ Day 2 (9/1)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day3.html">
 <span class="dropdown-text">3️⃣ Day 3 (9/2)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day4.html">
 <span class="dropdown-text">4️⃣ Day 4 (9/3)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day5.html">
 <span class="dropdown-text">5️⃣ Day 5 (9/4)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day6.html">
 <span class="dropdown-text">6️⃣ Day 6 (9/8)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day7.html">
 <span class="dropdown-text">7️⃣ Day 7 (9/9)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day8.html">
 <span class="dropdown-text">8️⃣ Day 8 (9/10)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day9.html">
 <span class="dropdown-text">9️⃣ Day 9 (9/11)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-interactive-sessions" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">💻 interactive sessions</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-interactive-sessions">    
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1a_positron_notebooks.html">
 <span class="dropdown-text">Session 1a - ⚒️ Positron &amp; Jupyter Notebooks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1b_python_essentials.html">
 <span class="dropdown-text">Session 1b - 🐍 Python Essentials</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1c_data_science_workflow_1.html">
 <span class="dropdown-text">Session 1c - 🎬 The Python Data Science Workflow, Part 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1d_data_science_workflow_2.html">
 <span class="dropdown-text">Session 1d - 🎬 The Python Data Science Workflow, Part 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/2a_reading_data.html">
 <span class="dropdown-text">Session 2a - 🐼 Reading Data into pandas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/2b_exploring_data.html">
 <span class="dropdown-text">Session 2b - 🔎 Exploring a DataFrame</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/2d_lists_and_dicts.html">
 <span class="dropdown-text">Session 2d - 📝 Lists &amp; Dictionaries</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/3a_booleans_and_conditionals.html">
 <span class="dropdown-text">Session 3a - 📝 Booleans &amp; Conditionals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/3b_filtering_data.html">
 <span class="dropdown-text">Session 3b - 🔍 The Filter Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/3c_sorting_and_ranking.html">
 <span class="dropdown-text">Session 3c - 🥇 The Top-N Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4a_cleaning_data.html">
 <span class="dropdown-text">Session 4a - 🧼 Missing, Duplicated, Miscast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4b_functions.html">
 <span class="dropdown-text">Session 4b - ⚙️ Write It Once, Name It, Use It</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4c_transforming_data.html">
 <span class="dropdown-text">Session 4c - ➕ The Derived-Column Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/5a_grouping_data.html">
 <span class="dropdown-text">Session 5a - 🗂️ The Split-Apply-Combine Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/5b_aggregating_data.html">
 <span class="dropdown-text">Session 5b - 📊 Several Answers at Once</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/5d_loops_over_groups.html">
 <span class="dropdown-text">Session 5d - 🔁 When a Pattern Is Not Enough</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6a_joining_data.html">
 <span class="dropdown-text">Session 6a - 🔗 The Join Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6b_reshaping_data.html">
 <span class="dropdown-text">Session 6b - 🧩 Long and Wide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6c_dates.html">
 <span class="dropdown-text">Session 6c - 📆 A Date Is Not a Number</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/70_building_a_table.html">
 <span class="dropdown-text">Session 7.0 - 🧱 Building a Table Row by Row</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7a_matplotlib.html">
 <span class="dropdown-text">Session 7a - 🖼️ The Anatomy of a Figure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7b_seaborn.html">
 <span class="dropdown-text">Session 7b - 🎨 Name the Columns, Not the Colours</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7d_project_kickoff.html">
 <span class="dropdown-text">Session 7d - 🚀 Project Kickoff</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-coding-colabs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">🙌 coding colabs</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-coding-colabs">    
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/2c_exploring_unfamiliar_data.html">
 <span class="dropdown-text">🙌 Session 2c - Five Claims About a Dataset You’ve Never Seen</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/3d_ranking_questions.html">
 <span class="dropdown-text">🙌 Session 3d - Which One, and How Do You Know?</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/4d_cleaning_messy_data.html">
 <span class="dropdown-text">🙌 Session 4d - From Field Sheet to DataFrame</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/5c_grouped_comparisons.html">
 <span class="dropdown-text">🙌 Session 5c - The Comparison You Made Yesterday, Properly</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/6d_two_table_exercise.html">
 <span class="dropdown-text">🙌 Session 6d - Two Records, Sixty-Six Years Apart</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/7c_penguins.html">
 <span class="dropdown-text">🙌 Session 7c - One Cloud of Points, Three Species</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../cheatsheets.html"> 
<span class="menu-text">👀 cheatsheets</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-resources" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">📚 resources</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-resources">    
        <li>
    <a class="dropdown-item" href="https://docs.python.org/3/" target="_blank">
 <span class="dropdown-text">📚 Python Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pandas.pydata.org/docs/" target="_blank">
 <span class="dropdown-text">📚 Pandas Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://numpy.org/doc/stable/" target="_blank">
 <span class="dropdown-text">📚 Numpy Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://matplotlib.org/stable/contents.html" target="_blank">
 <span class="dropdown-text">📚 Matplotlib Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://seaborn.pydata.org/" target="_blank">
 <span class="dropdown-text">📚 Seaborn Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://positron.posit.co/" target="_blank">
 <span class="dropdown-text">📚 Positron Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://docs.anaconda.com/" target="_blank">
 <span class="dropdown-text">📚 Anaconda Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://stackoverflow.com/" target="_blank">
 <span class="dropdown-text">📚 Stack Overflow</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://realpython.com/" target="_blank">
 <span class="dropdown-text">📚 Real Python</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://towardsdatascience.com/" target="_blank">
 <span class="dropdown-text">📚 Towards Data Science</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.datacamp.com/" target="_blank">
 <span class="dropdown-text">📚 DataCamp</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.kaggle.com/" target="_blank">
 <span class="dropdown-text">📚 Kaggle</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="http://pythontutor.com/" target="_blank">
 <span class="dropdown-text">🧰 Python Tutor</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pandastutor.com/vis.html#" target="_blank">
 <span class="dropdown-text">🧰 Pandas Tutor</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://wesmckinney.com/book/" target="_blank">
 <span class="dropdown-text">📙 Python for Data Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://jakevdp.github.io/PythonDataScienceHandbook/" target="_blank">
 <span class="dropdown-text">📙 Python for Data Science Handbook</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/jakevdp/PythonDataScienceHandbook" target="_blank">
 <span class="dropdown-text">📙 Python Data Science Handbook (GitHub)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://talkpython.fm/" target="_blank">
 <span class="dropdown-text">📻 Talk Python to Me</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/EDS-217-Essential-Python/EDS-217-Essential-Python.github.io" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-left">
      <h1 class="title">Answer Key</h1>
            <p class="subtitle lead">🌊 Microplastics: From Raw File to Real Numbers</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta column-page-left">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#setup" id="toc-setup" class="nav-link active" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#part-1-get-your-bearings" id="toc-part-1-get-your-bearings" class="nav-link" data-scroll-target="#part-1-get-your-bearings">Part 1: Get your bearings</a></li>
  <li><a href="#part-2-decide-what-to-keep" id="toc-part-2-decide-what-to-keep" class="nav-link" data-scroll-target="#part-2-decide-what-to-keep">Part 2: Decide what to keep</a></li>
  <li><a href="#part-3-make-it-comparable" id="toc-part-3-make-it-comparable" class="nav-link" data-scroll-target="#part-3-make-it-comparable">Part 3: Make it comparable</a></li>
  <li><a href="#part-4-the-derived-columns" id="toc-part-4-the-derived-columns" class="nav-link" data-scroll-target="#part-4-the-derived-columns">Part 4: The derived columns</a></li>
  <li><a href="#part-5-a-classifier-of-your-own" id="toc-part-5-a-classifier-of-your-own" class="nav-link" data-scroll-target="#part-5-a-classifier-of-your-own">Part 5: A classifier of your own</a></li>
  <li><a href="#part-6-the-question" id="toc-part-6-the-question" class="nav-link" data-scroll-target="#part-6-the-question">Part 6: The question</a></li>
  <li><a href="#part-7-write-it-up" id="toc-part-7-write-it-up" class="nav-link" data-scroll-target="#part-7-write-it-up">Part 7: Write it up</a></li>
  <li><a href="#where-the-marks-are" id="toc-where-the-marks-are" class="nav-link" data-scroll-target="#where-the-marks-are">Where the marks are</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block column-page-left" id="quarto-document-content">





<div class="callout callout-style-default callout-important callout-titled" title="How to use this key">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How to use this key
</div>
</div>
<div class="callout-body-container callout-body">
<p>Work the exercise first, then come here. The code below is <strong>one</strong> correct answer, not the only one. If your code looks different but produces the same numbers, you were right.</p>
<p>The written answers matter more than the code. You can already tell whether your code ran. What you cannot check on your own is whether you read the result correctly, and that is what the green <strong>Answer</strong> boxes are for. Compare your markdown cells against them.</p>
<p>⬅️ Back to <a href="../../course-materials/eod-practice/eod-day4-2026.html">the exercise</a></p>
</div>
</div>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<div id="afa274e2" class="cell" data-execution_count="1">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="st">'https://eds-217-essential-python.github.io/data/marine_microplastics.csv'</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(url, parse_dates<span class="op">=</span>[<span class="st">'Date'</span>], date_format<span class="op">=</span><span class="st">'%m/</span><span class="sc">%d</span><span class="st">/%Y %I:%M:%S %p'</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>df.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>(16245, 22)</code></pre>
</div>
</div>
</section>
<section id="part-1-get-your-bearings" class="level2">
<h2 class="anchored" data-anchor-id="part-1-get-your-bearings">Part 1: Get your bearings</h2>
<p><strong>1. How many rows and columns? Display the first few rows.</strong></p>
<div id="d318c727" class="cell" data-execution_count="2">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.shape)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(16245, 22)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">OBJECTID</th>
<th data-quarto-table-cell-role="th">Oceans</th>
<th data-quarto-table-cell-role="th">Regions</th>
<th data-quarto-table-cell-role="th">SubRegions</th>
<th data-quarto-table-cell-role="th">Sampling Method</th>
<th data-quarto-table-cell-role="th">Measurement</th>
<th data-quarto-table-cell-role="th">Unit</th>
<th data-quarto-table-cell-role="th">Density Range</th>
<th data-quarto-table-cell-role="th">Density Class</th>
<th data-quarto-table-cell-role="th">Short Reference</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">Organization</th>
<th data-quarto-table-cell-role="th">Keywords</th>
<th data-quarto-table-cell-role="th">Accession Number</th>
<th data-quarto-table-cell-role="th">Accession Link</th>
<th data-quarto-table-cell-role="th">Latitude</th>
<th data-quarto-table-cell-role="th">Longitude</th>
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th">GlobalID</th>
<th data-quarto-table-cell-role="th">x</th>
<th data-quarto-table-cell-role="th">y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>10008</td>
<td>Atlantic Ocean</td>
<td>NaN</td>
<td>NaN</td>
<td>Grab sample</td>
<td>0.020000</td>
<td>pieces/m3</td>
<td>0.005-1</td>
<td>Medium</td>
<td>Barrows et al.2018</td>
<td>...</td>
<td>Adventure Scientist</td>
<td>Adventure Scientist/Citizen Science</td>
<td>211009</td>
<td>https://www.ncei.noaa.gov/access/metadata/land...</td>
<td>-58.428300</td>
<td>-64.1640</td>
<td>2017-02-03</td>
<td>1e5b8e71-037b-4887-a276-f1e4552acb1f</td>
<td>-64.1640</td>
<td>-58.428300</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>8680</td>
<td>Atlantic Ocean</td>
<td>NaN</td>
<td>NaN</td>
<td>Grab sample</td>
<td>0.008000</td>
<td>pieces/m3</td>
<td>0.005-1</td>
<td>Medium</td>
<td>Barrows et al.2018</td>
<td>...</td>
<td>Adventure Scientist</td>
<td>Adventure Scientist/Citizen Science</td>
<td>211009</td>
<td>https://www.ncei.noaa.gov/access/metadata/land...</td>
<td>-51.308200</td>
<td>-60.5467</td>
<td>2013-11-17</td>
<td>a40f7f7c-1025-4aac-ad16-ee4cba196870</td>
<td>-60.5467</td>
<td>-51.308200</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>13257</td>
<td>Pacific Ocean</td>
<td>NaN</td>
<td>NaN</td>
<td>Manta net</td>
<td>0.019886</td>
<td>pieces/m3</td>
<td>0.005-1</td>
<td>Medium</td>
<td>Faure et al.2015</td>
<td>...</td>
<td>Oceaneye Association, Switzerland</td>
<td>Oceaneye Association; Citizen Science</td>
<td>276422</td>
<td>https://www.ncei.noaa.gov/access/metadata/land...</td>
<td>-51.826667</td>
<td>-72.5750</td>
<td>2015-12-26</td>
<td>febf79b8-7e2c-46e6-bc15-e08492ec2029</td>
<td>-72.5750</td>
<td>-51.826667</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>9676</td>
<td>Atlantic Ocean</td>
<td>NaN</td>
<td>NaN</td>
<td>Grab sample</td>
<td>0.018000</td>
<td>pieces/m3</td>
<td>0.005-1</td>
<td>Medium</td>
<td>Barrows et al.2018</td>
<td>...</td>
<td>Adventure Scientist</td>
<td>Adventure Scientist/Citizen Science</td>
<td>211009</td>
<td>https://www.ncei.noaa.gov/access/metadata/land...</td>
<td>-31.696000</td>
<td>-48.5600</td>
<td>2015-08-11</td>
<td>a77121b2-e113-444e-82d9-7af11d62fdd2</td>
<td>-48.5600</td>
<td>-31.696000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>6427</td>
<td>Pacific Ocean</td>
<td>NaN</td>
<td>NaN</td>
<td>Neuston net</td>
<td>0.000000</td>
<td>pieces/m3</td>
<td>0-0.0005</td>
<td>Very Low</td>
<td>Law et al.2014</td>
<td>...</td>
<td>Sea Education Association</td>
<td>SEA</td>
<td>211008</td>
<td>https://www.ncei.noaa.gov/access/metadata/land...</td>
<td>6.350000</td>
<td>-121.8500</td>
<td>2002-12-18</td>
<td>be27c450-02ca-4261-8d89-cae21108e6cc</td>
<td>-121.8500</td>
<td>6.350000</td>
</tr>
</tbody>
</table>

<p>5 rows × 22 columns</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>16,245 rows and 22 columns</strong>, one row per water sample. Look at what the 22 columns are made of: <code>Measurement</code>, <code>Unit</code>, <code>Latitude</code>, <code>Longitude</code> and <code>Date</code> describe the measurement itself, and <code>Sampling Method</code>, <code>Density Range</code> and <code>Density Class</code> describe how it was taken and how the contributing study classified it. Most of the rest is provenance, meaning who took it, under what accession, from which paper, with which DOI. Two columns, <code>x</code> and <code>y</code>, simply repeat <code>Longitude</code> and <code>Latitude</code>.</p>
<p>A file with more provenance columns than measurement columns is the signature of an assembled archive rather than a designed experiment. NOAA pooled 37 separate studies here, and most of the width of this file exists so that any one row can be traced back to the study it came from. You will use those provenance columns in task 6 and again in Part 6.</p>
</div>
</div>
<p><strong>2. Run <code>.info()</code>. Which columns are <code>object</code>, and which of those <em>should</em> be something else?</strong></p>
<div id="5a7d87a3" class="cell" data-execution_count="3">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 16245 entries, 0 to 16244
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   OBJECTID          16245 non-null  int64         
 1   Oceans            15974 non-null  object        
 2   Regions           7996 non-null   object        
 3   SubRegions        588 non-null    object        
 4   Sampling Method   16245 non-null  object        
 5   Measurement       10453 non-null  float64       
 6   Unit              16245 non-null  object        
 7   Density Range     16245 non-null  object        
 8   Density Class     16245 non-null  object        
 9   Short Reference   16245 non-null  object        
 10  Long Reference    16245 non-null  object        
 11  DOI               16245 non-null  object        
 12  Organization      16245 non-null  object        
 13  Keywords          16227 non-null  object        
 14  Accession Number  16245 non-null  int64         
 15  Accession Link    16245 non-null  object        
 16  Latitude          16245 non-null  float64       
 17  Longitude         16245 non-null  float64       
 18  Date              16245 non-null  datetime64[ns]
 19  GlobalID          16245 non-null  object        
 20  x                 16245 non-null  float64       
 21  y                 16245 non-null  float64       
dtypes: datetime64[ns](1), float64(5), int64(2), object(14)
memory usage: 2.7+ MB</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fourteen columns are <code>object</code></strong>: <code>Oceans</code>, <code>Regions</code>, <code>SubRegions</code>, <code>Sampling Method</code>, <code>Unit</code>, <code>Density Range</code>, <code>Density Class</code>, <code>Short Reference</code>, <code>Long Reference</code>, <code>DOI</code>, <code>Organization</code>, <code>Keywords</code>, <code>Accession Link</code> and <code>GlobalID</code>. Most of those are genuinely text, so <code>object</code> is correct for them.</p>
<p>The one that should be something else is <strong><code>Density Range</code></strong>, which holds numbers written as text: <code>'0.005-1'</code>, <code>'30000-40000'</code>, <code>'&gt;=10'</code>. You cannot compare or sort those numerically, and Part 5 is about what happens when you try to read them.</p>
<p>Two more are worth naming. <code>Date</code> is <code>datetime64</code> here only because you passed <code>parse_dates=</code>; without that line it would have been a fifteenth <code>object</code> column, and everything in task 13 would have been impossible. And the mis-typed column runs the other way: <strong><code>Accession Number</code> is <code>int64</code> but is a label, not a quantity</strong>. Task 11 is where you repair it.</p>
</div>
</div>
<p><strong>3. Run <code>.isnull().sum()</code>. How many columns have gaps? Which are the columns, and how many gaps do they have?</strong></p>
<div id="3a5ab220" class="cell" data-execution_count="4">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df.isnull().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>OBJECTID                0
Oceans                271
Regions              8249
SubRegions          15657
Sampling Method         0
Measurement          5792
Unit                    0
Density Range           0
Density Class           0
Short Reference         0
Long Reference          0
DOI                     0
Organization            0
Keywords               18
Accession Number        0
Accession Link          0
Latitude                0
Longitude               0
Date                    0
GlobalID                0
x                       0
y                       0
dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Five columns have gaps. In descending order: <code>SubRegions</code> 15,657, <code>Regions</code> 8,249, <code>Measurement</code> 5,792, <code>Oceans</code> 271, and <code>Keywords</code> 18.</strong></p>
<p><code>Keywords</code> is the one to watch for. It is missing on only 18 rows out of 16,245, so it is easy to skim past in a long column of zeros, and it is the one gap that task 7 leaves behind. Read every line of the output rather than only the large numbers at the top of it.</p>
<p>Notice also that the largest gap is not the important one. <code>SubRegions</code> is missing on 96 percent of rows and costs you nothing, because you were never going to analyse by sub-region. <code>Measurement</code> is missing on 36 percent, and it is the column every later question uses.</p>
</div>
</div>
<p><strong>4. <code>Oceans</code> is missing on 271 rows and <code>Measurement</code> on 5,792. Are those the same rows? How do you know?</strong></p>
<div id="698187d1" class="cell" data-execution_count="5">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The 271 rows missing an ocean are all rows that are also missing a measurement:</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># filtering out the missing measurements leaves nothing missing an ocean.</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>measured <span class="op">=</span> df.dropna(subset<span class="op">=</span>[<span class="st">'Measurement'</span>])</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(measured.shape)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(measured[<span class="st">'Oceans'</span>].isnull().<span class="bu">sum</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(10453, 22)
0</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Not the same rows, but the 271 rows missing an ocean are entirely contained in the 5,792 missing a measurement.</strong> Dropping the rows with no <code>Measurement</code> leaves 10,453 rows, and in those 10,453 rows <code>Oceans</code> is missing zero times. Every row that lacks an ocean also lacks a measurement.</p>
<p>The zero count is how you know, and the logic is worth being precise about. The test is one-directional: it proves the <code>Oceans</code> gaps are a subset of the <code>Measurement</code> gaps, and it says nothing about the other 5,521 rows that have no measurement but do have an ocean.</p>
<p>The practical consequence is that you get the <code>Oceans</code> column cleaned for free. Once you handle <code>Measurement</code> in task 5 you will never need to think about missing oceans again.</p>
</div>
</div>
</section>
<section id="part-2-decide-what-to-keep" class="level2">
<h2 class="anchored" data-anchor-id="part-2-decide-what-to-keep">Part 2: Decide what to keep</h2>
<p><strong>5. Use <code>.dropna()</code> with <code>subset=</code> to keep only the rows with a <code>Measurement</code>. How many rows are left, and what fraction of the file is that?</strong></p>
<div id="fd6f9316" class="cell" data-execution_count="6">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.dropna(subset<span class="op">=</span>[<span class="st">'Measurement'</span>])</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.shape)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.shape[<span class="dv">0</span>] <span class="op">/</span> <span class="dv">16245</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(10453, 22)
0.6434595260080025</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>10,453 rows, which is 64.3 percent of the file.</strong> One line removed 5,792 rows, more than a third of everything you downloaded. Printing the shape after every step is how we notice.</p>
<p>Now compare that with what a bare <code>.dropna()</code> would have done. Bare <code>.dropna()</code> removes any row with a null anywhere, and <code>SubRegions</code> is null on 15,657 rows, so it would have left you <strong>588 rows, 3.6 percent of the file</strong>. The <code>subset=</code> argument is the difference between keeping two-thirds of your data and keeping a twenty-eighth of it.</p>
</div>
</div>
<p><strong>6. Run <code>df['Unit'].value_counts()</code> now and compare it with the counts below, which are what the same line gave before task 5: <code>pieces/m3</code> 10,178, <code>pieces/10 mins</code> 5,792, <code>pieces kg-1 d.w.</code> 275. What did that one line cost you, and which sampling programme did the rows you lost belong to? (Check <code>Sampling Method</code> and <code>Organization</code> on the rows you removed, if you want to be sure.)</strong></p>
<div id="7d8e463a" class="cell" data-execution_count="7">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Unit'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>Unit
pieces/m3           10178
pieces kg-1 d.w.      275
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>It cost you an entire unit.</strong> Before task 5 the counts were <code>pieces/m3</code> 10,178, <code>pieces/10 mins</code> 5,792, <code>pieces kg-1 d.w.</code> 275. Afterwards <code>pieces/10 mins</code> is gone completely, and the 5,792 rows it lost are exactly the 5,792 nulls. Every single row reported in <code>pieces/10 mins</code> had a blank measurement, and no row in the other two units did.</p>
<p>The dropped rows are all one programme: <code>Sampling Method</code> is <code>Hand picking</code> on all 5,792, <code>Organization</code> is <code>University of Texas Marine Science Institute</code> on all 5,792, and the keyword is Nurdle Patrol, a citizen-science beach survey where volunteers count plastic pellets found in ten minutes of walking.</p>
<p>So the null is a fact about a protocol, not sloppy data entry. A count per ten minutes of searching is a real observation, but it is a rate per unit of effort, and there is no volume of water in it to divide by. NOAA left <code>Measurement</code> blank because the field means pieces per cubic metre and these samples have no such value. Dropping them was right, and the reason to know all this is that “we removed 5,792 rows of citizen-science beach data because it was measured on an incompatible scale” is a sentence you can defend, while “we dropped the nulls” is not.</p>
</div>
</div>
<p><strong>7. Fill the gaps in <code>Regions</code> and <code>SubRegions</code> with <code>'Unspecified'</code>, one column at a time, assigning each result back. Confirm with <code>.isnull().sum()</code> that only <code>Keywords</code> is still missing anything.</strong></p>
<div id="001d9fba" class="cell" data-execution_count="8">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Regions'</span>] <span class="op">=</span> df[<span class="st">'Regions'</span>].fillna(<span class="st">'Unspecified'</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'SubRegions'</span>] <span class="op">=</span> df[<span class="st">'SubRegions'</span>].fillna(<span class="st">'Unspecified'</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>df.isnull().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>OBJECTID             0
Oceans               0
Regions              0
SubRegions           0
Sampling Method      0
Measurement          0
Unit                 0
Density Range        0
Density Class        0
Short Reference      0
Long Reference       0
DOI                  0
Organization         0
Keywords            18
Accession Number     0
Accession Link       0
Latitude             0
Longitude            0
Date                 0
GlobalID             0
x                    0
y                    0
dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong><code>Keywords</code> and its 18 nulls, and nothing else.</strong> Going into this step <code>Regions</code> was null on 6,904 rows and <code>SubRegions</code> on 9,865; both are now zero, and every other column reads zero as well. The 18 remaining gaps do no harm, because nothing downstream uses <code>Keywords</code>, but run the confirmation anyway. It is how you know the two <code>.fillna()</code> calls did what you meant, and it is how you would catch it if one of them had been assigned to the wrong column.</p>
<p><code>'Unspecified'</code> is the right filler here for a reason worth stating. It is accurate. It does not claim the sample came from a region, it records that the region was not reported, and it will show up in a <code>.value_counts()</code> as its own category instead of hiding.</p>
</div>
</div>
<p><strong>8. In a markdown cell: task 5 removed rows and task 7 kept them. Both were the right decision. Explain in two or three sentences what made them different.</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The difference is whether the missing column is the one you are analysing.</strong> <code>Measurement</code> is the variable the whole exercise is about, and there is no defensible way to invent a concentration for a sample that was never measured on that scale, so those rows cannot contribute and have to go. <code>Regions</code> and <code>SubRegions</code> are descriptive labels that none of the calculations in this practice depend on, so a row with a valid measurement and a blank region is still a perfectly good measurement.</p>
<p>The rule to remember: <strong>drop on the column you are measuring, fill on the columns you are describing by.</strong> Applied here it kept 10,453 rows instead of 588, and the 9,865 rows that lacked a sub-region are most of the data you went on to analyse.</p>
</div>
</div>
<p><strong>9. Check for duplicated rows. Do it twice: once bare, and once with <code>subset=</code> naming the columns that define a single observation, which here are <code>Latitude</code>, <code>Longitude</code>, <code>Date</code>, <code>Measurement</code> and <code>Unit</code>. Report both numbers and say which one you believe, and why the two differ so much.</strong></p>
<div id="0c3bf010" class="cell" data-execution_count="9">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.duplicated().<span class="bu">sum</span>())</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>sample_columns <span class="op">=</span> [<span class="st">'Latitude'</span>, <span class="st">'Longitude'</span>, <span class="st">'Date'</span>, <span class="st">'Measurement'</span>, <span class="st">'Unit'</span>]</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.duplicated(subset<span class="op">=</span>sample_columns).<span class="bu">sum</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>0
539</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Zero bare, 539 with the subset.</strong> The zero is not evidence of a clean file. <code>.duplicated()</code> with no arguments asks whether two rows match in all 22 columns, and this file has <code>OBJECTID</code> and <code>GlobalID</code>, both of which hold 10,453 distinct values across 10,453 rows. Two rows can never be identical while they each have a unique key, so bare <code>.duplicated()</code> on a table with an ID column is guaranteed to return zero and tells you nothing.</p>
<p>The subset asks the question you actually meant: did two rows record the same measurement, in the same unit, at the same coordinates, on the same day? 539 rows are flagged, and 360 of those 539 report a measurement of exactly zero.</p>
<p><strong>Which do I believe? The 539 flagged rows, but as a list of candidates rather than a verdict.</strong> Two rows at the same place, on the same day, reporting the same number may be a copy, and 326 of the flagged rows come from a single organisation, which is where an ingestion error would show up. They may equally be two genuine replicate tows at one station, and the file has no column that distinguishes those two possibilities. The honest report is “539 rows are indistinguishable on the fields that define an observation, and I would ask the data provider before removing them”, not “the file has 539 duplicates”.</p>
</div>
</div>
</section>
<section id="part-3-make-it-comparable" class="level2">
<h2 class="anchored" data-anchor-id="part-3-make-it-comparable">Part 3: Make it comparable</h2>
<p><strong>10 and 11. Filter to <code>pieces/m3</code>, and make <code>Accession Number</code> a label.</strong></p>
<div id="7629417c" class="cell" data-execution_count="10">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>samples <span class="op">=</span> df[df[<span class="st">'Unit'</span>] <span class="op">==</span> <span class="st">'pieces/m3'</span>].copy()</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>samples.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>(10178, 22)</code></pre>
</div>
</div>
<div id="1a41ae41" class="cell" data-execution_count="11">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>samples[<span class="st">'Accession Number'</span>] <span class="op">=</span> samples[<span class="st">'Accession Number'</span>].astype(<span class="bu">str</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>samples[<span class="st">'Accession Number'</span>].dtype</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>dtype('O')</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>10,178 rows</strong>, which drops the 275 rows reported in <code>pieces kg-1 d.w.</code>. Those are sediment samples, pieces per kilogram of dry sediment, and they were collected with corers and spoons rather than nets. Pieces per kilogram of mud and pieces per cubic metre of water are different physical quantities, and no conversion factor exists between them, so keeping them would mean averaging two things that are not the same thing.</p>
<p><code>Accession Number</code> changes from <code>int64</code> to <code>object</code>. It is an archive catalogue number, so the mean of a set of accession numbers is meaningless, but pandas would compute one without complaint if you asked. Converting it to text removes the possibility.</p>
</div>
</div>
<p><strong>12. The <code>Oceans</code> values all end in the word “Ocean”. Use <code>.str.replace()</code> to make a new column called <code>ocean</code> holding the short name, and check it with <code>.value_counts()</code>.</strong></p>
<div id="e768e8d5" class="cell" data-execution_count="12">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>samples[<span class="st">'ocean'</span>] <span class="op">=</span> samples[<span class="st">'Oceans'</span>].<span class="bu">str</span>.replace(<span class="st">' Ocean'</span>, <span class="st">''</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>samples[<span class="st">'ocean'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>ocean
Atlantic    9039
Pacific     1050
Arctic        69
Southern      20
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Atlantic 9,039, Pacific 1,050, Arctic 69, Southern 20.</strong> Those four sum to 10,178, which is the full row count, so nothing was lost in the replacement and no ocean is missing.</p>
<p>Read the imbalance now, because it is the fact that Part 6 turns on. The Atlantic contributes <strong>89 percent</strong> of the samples and the Pacific <strong>10 percent</strong>, and there is no Indian Ocean in this table at all. The imbalance is a statement about where research vessels sail out of, not about where plastic is.</p>
</div>
</div>
<p><strong>13. Add a column called <code>year</code> holding the year each sample was taken, using the supplied line from the setup Field Note. Then run <code>.value_counts()</code> on <code>year</code>. Which single year contributed the most samples? In a markdown cell, say whether the archive is spread evenly across its fifty-one calendar years, and what an uneven spread would mean for anyone who wants to use it to describe a trend.</strong></p>
<div id="57b691a7" class="cell" data-execution_count="13">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>samples[<span class="st">'year'</span>] <span class="op">=</span> samples[<span class="st">'Date'</span>].dt.year</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>samples[<span class="st">'year'</span>].value_counts().head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>year
2014    836
2018    724
1992    517
2015    486
2001    473
2000    445
1998    415
1996    408
1997    388
2016    370
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>2014, with 836 samples, 8.2 percent of the file.</strong> 2018 is second with 724.</p>
<p><strong>The archive is not spread evenly, and it is not close.</strong> The dates run from 1972 to 2022, but only 38 distinct years appear, so <strong>13 years contain no samples at all</strong>. The median year contributes 235 samples; 2014 contributes more than three times that. The top five years hold 30 percent of everything.</p>
<p>For anyone wanting a trend, the uneven coverage is disqualifying on its own. A plot of mean concentration against year would move whenever the mix of contributing studies changed, and the mix changes every year. 2014 is mostly Adventure Scientist tows and is 780 Atlantic out of 836; 2018 is led by a single Mexican study that sampled both coasts: of its 370 rows, 220 are Pacific and 150 Atlantic. So a rise from 2014 to 2018 would partly be a rise from the Atlantic to the Pacific and from one net to another. <strong>Sampling effort is confounded with year, with ocean, and with method simultaneously.</strong> The archive can tell you what has been measured, but it cannot tell you what has changed.</p>
</div>
</div>
</section>
<section id="part-4-the-derived-columns" class="level2">
<h2 class="anchored" data-anchor-id="part-4-the-derived-columns">Part 4: The derived columns</h2>
<p><strong>14. Run <code>.describe()</code> on <code>Measurement</code>. Write down the median and the maximum. How many orders of magnitude separate them?</strong></p>
<div id="265995e4" class="cell" data-execution_count="14">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>samples[<span class="st">'Measurement'</span>].describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>count     10178.000000
mean        219.409152
std        2599.554575
min           0.000000
25%           0.000000
50%           0.007200
75%           0.049937
max      110480.000000
Name: Measurement, dtype: float64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Median 0.0072, maximum 110,480 pieces per cubic metre, a little over seven orders of magnitude apart</strong> (log10 of 110,480 divided by 0.0072 is 7.19).</p>
<p>Two other numbers in that output deserve as much attention. The <strong>mean is 219.4</strong>, roughly 30,000 times the median, which only happens when a handful of enormous values are dragging the average away from every actual sample. And the <strong>25th percentile is exactly 0.0</strong>, so at least a quarter of the samples found no plastic at all.</p>
<p>A column whose middle value is seven-thousandths and whose largest value is six figures is not going to behave on a linear axis, which is what the histogram in task 15 puts on screen.</p>
</div>
</div>
<p><strong>15 and 16. The histogram, and why it is useless.</strong></p>
<div id="0db74c04" class="cell" data-execution_count="15">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>counts, edges, _ <span class="op">=</span> plt.hist(samples[<span class="st">'Measurement'</span>])</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'pieces per cubic metre'</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co"># plt.hist hands back the bin counts and edges, which is how we read a figure</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co"># we cannot see anything in.</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'bin width:'</span>, edges[<span class="dv">1</span>] <span class="op">-</span> edges[<span class="dv">0</span>])</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'counts per bin:'</span>, counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="eod-day4-2026-key_files/figure-html/cell-16-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>bin width: 11048.0
counts per bin: [1.0147e+04 6.0000e+00 1.1000e+01 4.0000e+00 4.0000e+00 3.0000e+00
 0.0000e+00 1.0000e+00 0.0000e+00 2.0000e+00]</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Ten equal-width bins across a range of 110,480 makes each bin 11,048 wide, and 10,147 of the 10,178 values fall in the first one.</strong> The first bar therefore holds 99.7 percent of the data, and the other nine bars hold 31 samples between them and are too short to see.</p>
<p>The plot is a faithful picture of a linear axis applied to a quantity that varies over seven orders of magnitude, and the single sentence the question wants is that the bins are set by the maximum while nearly every value sits near the minimum.</p>
</div>
</div>
<p><strong>17. Filter <code>samples</code> to the rows where <code>Measurement</code> is greater than zero, end the line with <code>.copy()</code>, and call it <code>positive</code>. How many samples reported exactly zero pieces? Is zero a measurement or a missing value?</strong></p>
<div id="509ac6d3" class="cell" data-execution_count="16">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>positive <span class="op">=</span> samples[samples[<span class="st">'Measurement'</span>] <span class="op">&gt;</span> <span class="dv">0</span>].copy()</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(positive.shape)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(samples.shape[<span class="dv">0</span>] <span class="op">-</span> positive.shape[<span class="dv">0</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(7091, 24)
3087</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>7,091 positive samples, and 3,087 reported exactly zero, which is 30.3 percent of the file.</strong></p>
<p><strong>Zero is a measurement.</strong> A net was towed, a known volume of water passed through it, and no plastic was found. A zero is a result, and it is a different kind of statement from the 5,792 rows you dropped in task 5, where no measurement of this kind was ever attempted. The file supports this reading: all 3,087 zeros have a <code>Density Class</code> of <code>Very Low</code>, and 3,003 of them have the <code>Density Range</code> <code>'0-0.0005'</code>, so NOAA recorded them as observed values rather than gaps.</p>
<p>The filter in this task is therefore not a cleaning step, and you should not describe it as one. You are removing 30 percent of your real data for an arithmetic reason: <code>np.log10(0)</code> is negative infinity, and task 18 needs finite numbers. Any statement you make about <code>positive</code> from here on is a statement about samples that found plastic, conditional on finding any, and the 3,087 zeros belong in the write-up as their own finding.</p>
</div>
</div>
<p><strong>18 and 19. The log column, its <code>.describe()</code>, the histogram again, and what the shape shows.</strong></p>
<div id="a735afe3" class="cell" data-execution_count="17">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>positive[<span class="st">'log10_measurement'</span>] <span class="op">=</span> np.log10(positive[<span class="st">'Measurement'</span>])</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>positive[<span class="st">'log10_measurement'</span>].describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>count    7091.000000
mean       -1.254441
std         1.502175
min        -3.170053
25%        -2.188425
50%        -1.665546
75%        -0.879686
max         5.043284
Name: log10_measurement, dtype: float64</code></pre>
</div>
</div>
<div id="ce63ca2c" class="cell" data-execution_count="18">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>plt.hist(positive[<span class="st">'log10_measurement'</span>])</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'log10(pieces per cubic metre)'</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="eod-day4-2026-key_files/figure-html/cell-19-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>The values now run from <strong>-3.17 to 5.04</strong>, with a median of <strong>-1.67</strong> and a mean of <strong>-1.25</strong>, and the whole range is visible at once. Reading those back into the original units: the middle sample holds about 0.02 pieces per cubic metre, the smallest about 0.0007, the largest about 110,000.</p>
<p><strong>The plot shows one thing <code>.describe()</code> did not: the distribution has two peaks.</strong> There is a large mode centred near log10 of -2, and then a second, clearly separated cluster between log10 of 3 and 4, holding 372 samples at roughly 1,000 to 10,000 pieces per cubic metre, with an almost empty gap in between. Every number <code>.describe()</code> gives you, the mean, the quartiles, the standard deviation, assumes there is one hump to describe, and reports the average of two populations as though it were the centre of one.</p>
</div>
</div>
<div id="4e2c5981" class="cell" data-execution_count="19">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Going beyond what question 19 asks: where does the upper cluster come from?</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>extreme <span class="op">=</span> positive[positive[<span class="st">'Measurement'</span>] <span class="op">&gt;</span> <span class="dv">57</span>]</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(extreme.shape[<span class="dv">0</span>])</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(extreme[<span class="st">'Sampling Method'</span>].value_counts())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>489
Sampling Method
PVC cylinder             292
Van Dorn sampler          84
Aluminum bucket           57
Stainless steel spoon     50
Intake seawater pump       5
CTD rosette sampler        1
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>All 489 samples above 57 pieces per cubic metre were collected with a bottle, a bucket or a spoon</strong>: PVC cylinder 292, Van Dorn sampler 84, aluminium bucket 57, stainless steel spoon 50, seawater intake pump 5, CTD rosette sampler 1. <strong>Not one of them came from a net.</strong></p>
<p>So the second mode is a method and not a place. A neuston net filters hundreds of cubic metres and retains particles above roughly a third of a millimetre; a two-litre bottle filters two thousandths of a cubic metre and its contents are examined under a microscope, so a single fibre in the bottle becomes 500 pieces per cubic metre. The two groups are both correctly reported and they are not measuring the same thing.</p>
<p>You are not expected to have found this yourself. It is here because it is the reason the answer to Part 6 has to be hedged, and because a second mode in a histogram is almost always a second population, which means a second protocol, a second instrument, or a second study.</p>
</div>
</div>
</section>
<section id="part-5-a-classifier-of-your-own" class="level2">
<h2 class="anchored" data-anchor-id="part-5-a-classifier-of-your-own">Part 5: A classifier of your own</h2>
<p><strong>20 and 21. Write <code>density_class</code>, test it, and apply it.</strong></p>
<div id="0f304da4" class="cell" data-execution_count="20">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> density_class(measurement):</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Label a microplastic concentration in pieces/m3."""</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> measurement <span class="op">&lt;</span> <span class="fl">0.01</span>:</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'low'</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> measurement <span class="op">&lt;</span> <span class="dv">1</span>:</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'medium'</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'high'</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(density_class(<span class="fl">0.001</span>), density_class(<span class="fl">0.5</span>), density_class(<span class="dv">50</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>low medium high</code></pre>
</div>
</div>
<div id="328a0f4b" class="cell" data-execution_count="21">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>positive[<span class="st">'my_class'</span>] <span class="op">=</span> positive[<span class="st">'Measurement'</span>].<span class="bu">apply</span>(density_class)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>positive[<span class="st">'my_class'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>my_class
medium    3782
low       2440
high       869
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>The three tests return <code>low</code>, <code>medium</code>, <code>high</code>, which is what you want to see before you spend one line of <code>.apply()</code> on 7,091 rows.</p>
<p>Applied, the counts are <strong>medium 3,782 (53.3 percent), low 2,440 (34.4 percent), high 869 (12.3 percent)</strong>. Note what the <code>elif</code> chain does for you: because the branches are checked in order, the <code>elif measurement &lt; 1</code> line only ever sees values that already failed <code>&lt; 0.01</code>, so you do not need to write <code>0.01 &lt;= measurement &lt; 1</code>. Each boundary appears exactly once, which is also why the classifier cannot leave a value unlabelled.</p>
</div>
</div>
<p><strong>22. Now compare your labels with NOAA’s. Filter <code>positive</code> to the rows NOAA labelled <code>'Medium'</code>, and run <code>.value_counts()</code> on <code>my_class</code> for just those rows. Do the same for NOAA’s <code>'Very Low'</code>.</strong></p>
<div id="761e0aa2" class="cell" data-execution_count="22">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>noaa_medium <span class="op">=</span> positive[positive[<span class="st">'Density Class'</span>] <span class="op">==</span> <span class="st">'Medium'</span>]</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(noaa_medium[<span class="st">'my_class'</span>].value_counts())</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>noaa_very_low <span class="op">=</span> positive[positive[<span class="st">'Density Class'</span>] <span class="op">==</span> <span class="st">'Very Low'</span>]</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(noaa_very_low[<span class="st">'my_class'</span>].value_counts())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>my_class
medium    3774
low        935
high       325
Name: count, dtype: int64
my_class
medium    8
high      5
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>NOAA’s 5,034 <code>Medium</code> rows split into <strong>3,774 of my medium, 935 of my low, and 325 of my high</strong>. NOAA’s 13 <code>Very Low</code> rows split into <strong>8 medium and 5 high</strong>, with nothing at all in low.</p>
<p>The second result is the one that cannot be explained away. The actual measurements NOAA called <code>Very Low</code> run from 0.111 to 80 pieces per cubic metre. A sample of 80 pieces per cubic metre sits above 93 percent of the positive samples in this archive, in the top 7 percent, and their column calls it very low.</p>
</div>
</div>
<p><strong>23. Something is wrong, and it is not your function. In a markdown cell, explain what NOAA’s <code>Density Class</code> must actually mean, given that samples they called <code>Very Low</code> fall in your <code>high</code> bin. Then say whether you would use their column in an analysis, and why.</strong></p>
<div id="f245a5f8" class="cell" data-execution_count="23">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>positive[[<span class="st">'Density Class'</span>, <span class="st">'Density Range'</span>]].drop_duplicates().sort_values(<span class="st">'Density Class'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="23">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Density Class</th>
<th data-quarto-table-cell-role="th">Density Range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">81</td>
<td>High</td>
<td>1-10</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4856</td>
<td>High</td>
<td>30000-40000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">13</td>
<td>Low</td>
<td>0.0005-0.005</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0</td>
<td>Medium</td>
<td>0.005-1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">37</td>
<td>Medium</td>
<td>500-30000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">56</td>
<td>Very High</td>
<td>&gt;=10</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">248</td>
<td>Very High</td>
<td>&gt;40000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">222</td>
<td>Very Low</td>
<td>0-100</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>In <code>positive</code>, three of the five class labels are attached to more than one numeric range, so <code>Density Class</code> is relative to the study that contributed the row.</strong> Note which table that is: with the zeros filtered out, <code>Very Low</code> keeps only <code>'0-100'</code>. In the full <code>samples</code> table it has two ranges as well, which is what you saw in task 17, and there it is four of five. The table says the rest plainly: <code>Medium</code> is both <code>'0.005-1'</code> and <code>'500-30000'</code>. <code>High</code> is both <code>'1-10'</code> and <code>'30000-40000'</code>. <code>Very High</code> is both <code>'&gt;=10'</code> and <code>'&gt;40000'</code>. <code>Very Low</code> here is <code>'0-100'</code>.</p>
<p>The arithmetic matches exactly. Of the 5,034 NOAA <code>Medium</code> rows, 4,709 have the range <code>'0.005-1'</code> and hold values from 0.005 to 0.996, while 325 have the range <code>'500-30000'</code> and hold values from 705 to 28,320. The 325 rows with the wider range are precisely the ones my classifier called high. Nothing has gone wrong on either side: NOAA is answering “was this sample high or low <strong>for its own study</strong>”, and my function is answering “was this sample high or low <strong>in pieces per cubic metre</strong>”. The two questions are different, so they have different answers.</p>
<p><strong>Would I use their column? Only within a single study, never across the archive.</strong> Inside one <code>Short Reference</code> it is a useful, expert-assigned relative label. Across the archive it cannot be counted, filtered or grouped, because a value of 80 is <code>Very Low</code> in one contributing paper and would be <code>Very High</code> in another, so “how many high-density samples are there” mixes incompatible scales and returns a number that means nothing. Where I need an absolute comparison, I would use the classifier I wrote, and publish its thresholds so a reader can disagree with them.</p>
<p>The general lesson is that a categorical column inherits the definition of whoever created it, and that definition often does not travel with the file. Before you group by somebody else’s category, find the rule that produced it.</p>
</div>
</div>
</section>
<section id="part-6-the-question" class="level2">
<h2 class="anchored" data-anchor-id="part-6-the-question">Part 6: The question</h2>
<p><strong>24. Build two tables with the filter pattern: the Atlantic samples and the Pacific samples, from <code>positive</code>. Report the row count of each.</strong></p>
<div id="4ec812b3" class="cell" data-execution_count="24">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>atlantic <span class="op">=</span> positive[positive[<span class="st">'ocean'</span>] <span class="op">==</span> <span class="st">'Atlantic'</span>].copy()</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>pacific <span class="op">=</span> positive[positive[<span class="st">'ocean'</span>] <span class="op">==</span> <span class="st">'Pacific'</span>].copy()</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(atlantic.shape)</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pacific.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(6216, 26)
(799, 26)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Atlantic 6,216, Pacific 799</strong>, out of 7,091 positive samples. The split is 87.7 percent Atlantic against 11.3 percent Pacific, so the Atlantic has close to eight times as many samples before either table has been looked at.</p>
</div>
</div>
<p><strong>25. Run <code>.describe()</code> on <code>Measurement</code> for each. Compare the two medians (the <code>50%</code> row), and then compare the two means. They will probably tell you two different stories. Which one would you put in a report, and why?</strong></p>
<div id="97aeea0b" class="cell" data-execution_count="25">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(atlantic[<span class="st">'Measurement'</span>].describe())</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pacific[<span class="st">'Measurement'</span>].describe())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>count      6216.000000
mean        282.729748
std        3266.793731
min           0.000676
25%           0.006374
50%           0.019440
75%           0.098790
max      110480.000000
Name: Measurement, dtype: float64
count      799.000000
mean       595.199821
std       1644.030554
min          0.001000
25%          0.010000
50%          0.116665
75%          2.611356
max      21156.558533
Name: Measurement, dtype: float64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Medians: Atlantic 0.0194, Pacific 0.1167 pieces per cubic metre, so the Pacific is 6.0 times the Atlantic. Means: Atlantic 282.7, Pacific 595.2, so the Pacific is 2.1 times the Atlantic.</strong> Same data, same direction, a factor of three difference in how big the effect is.</p>
<p><strong>I would report the median, and say that I am doing so.</strong> The mean is not describing a typical sample in either ocean. Only 294 of the 6,216 Atlantic samples, 4.7 percent, are above the Atlantic mean of 282.7, and that mean is roughly 2,900 times the Atlantic 75th percentile of 0.0988. It is an average that fewer than five samples in a hundred reach, with six thousand near-zeros underneath it, and the Atlantic standard deviation of 3,267 is larger than the mean, which is the arithmetic saying so.</p>
<p>The medians are also not the whole story, and the quartiles say why. The Pacific 75th percentile is 2.61 against the Atlantic’s 0.0988, a factor of 26, far larger than the factor of 6 at the median. The two distributions differ more in their upper halves than in their middles, and task 19 already told you what lives in those upper halves.</p>
</div>
</div>
<p><strong>26. Compare the mean of <code>log10_measurement</code> for each instead. In a markdown cell, say what that comparison is doing that the comparison of raw means was not.</strong></p>
<div id="55073419" class="cell" data-execution_count="26">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(atlantic[<span class="st">'log10_measurement'</span>].mean())</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pacific[<span class="st">'log10_measurement'</span>].mean())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>-1.3755951615008193
-0.30290512867855834</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>-1.376 for the Atlantic and -0.303 for the Pacific</strong>, a difference of 1.07 on a base-10 log scale, so the Pacific typical value is about <strong>11.8 times</strong> the Atlantic. Converted back, 10 to the power -1.376 is 0.042 and 10 to the power -0.303 is 0.498 pieces per cubic metre.</p>
<p><strong>Averaging the logs gives every sample equal weight regardless of its size.</strong> On the raw scale, one sample of 110,480 counts as much as five and a half million samples of 0.02, so the raw mean is decided by a few rows. On the log scale, a sample ten times above the typical value pulls the average by exactly as much as a sample ten times below it pulls it back. Equal weighting on the log scale is the right weighting for a quantity that varies multiplicatively, which is what the task 18 histogram showed this one does.</p>
<p>The name for 10 raised to the mean of the logs is the <strong>geometric mean</strong>, and the three comparisons you now have are worth writing down together: means 2.1 times, medians 6.0 times, geometric means 11.8 times. All three say Pacific is higher. <strong>Any one of them quoted alone is a choice you owe the reader an explanation for.</strong></p>
</div>
</div>
<p><strong>27. Before you conclude anything: how many Pacific samples are there, out of how many total? Task 12 counted the oceans in <code>samples</code>, before the zeros came out, so expect a different pair of numbers here. In one sentence, say what you would need to know about <em>how the samples were collected</em> before you would publish a comparison between these two oceans.</strong></p>
<div id="cad77d69" class="cell" data-execution_count="27">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(positive[<span class="st">'ocean'</span>].value_counts())</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The question is about gear, so count the methods within each ocean.</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name <span class="kw">in</span> [<span class="st">'Atlantic'</span>, <span class="st">'Pacific'</span>]:</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>()</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(name)</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(positive[positive[<span class="st">'ocean'</span>] <span class="op">==</span> name][<span class="st">'Sampling Method'</span>]</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>          .value_counts().head(<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>ocean
Atlantic    6216
Pacific      799
Arctic        58
Southern      18
Name: count, dtype: int64

Atlantic
Sampling Method
Neuston net             4390
Grab sample              748
Manta net                631
Intake seawater pump     106
Name: count, dtype: int64

Pacific
Sampling Method
Manta net       226
PVC cylinder    188
Grab sample     166
Neuston net     158
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>799 Pacific samples out of 7,091, which is 11.3 percent</strong>, and task 12 shows the same imbalance before the zeros were removed: 9,039 Atlantic against 1,050 Pacific.</p>
<p>The one sentence: <strong>you would need to know whether the two oceans were sampled with the same gear, because a net and a bottle do not count the same particles.</strong></p>
<p>That is short enough to write in the time you have. The numbers behind it: 4,390 of the Atlantic samples are neuston net tows, while 188 of the 799 Pacific samples, nearly a quarter of them, come from a single study using a PVC cylinder.</p>
<p>Two further things make it worse rather than better. 61 percent of the Atlantic rows come from one organisation, the Sea Education Association, so “the Atlantic” here is largely one long-running programme on one set of transects. And the two oceans were not sampled in the same era: 39 percent of the Atlantic samples were taken before 2000 against 2.8 percent of the Pacific ones, and the median Atlantic sample year is 2003 against the Pacific’s 2015. The comparison in tasks 25 and 26 is therefore between two different sets of instruments, deployed by different groups, in different decades, and it happens to also be between two oceans.</p>
</div>
</div>
</section>
<section id="part-7-write-it-up" class="level2">
<h2 class="anchored" data-anchor-id="part-7-write-it-up">Part 7: Write it up</h2>
<p>There is no single right answer here. A strong response cites at least three numbers you computed, names one cleaning decision and what it cost, and states at least one thing the dataset cannot tell the journalist. Here is one that would earn full marks.</p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ A model answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ A model answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>The short answer is that this dataset does show higher concentrations in the Pacific, and that it is not good enough evidence to print.</p>
<p>Working from NOAA’s marine microplastics archive, I kept the 10,178 samples reported in pieces per cubic metre and set aside the 3,087 that found no plastic at all, which is 30 percent of them and a finding in its own right. Among the 7,091 samples that did find plastic, the median Atlantic sample holds 0.019 pieces per cubic metre and the median Pacific sample 0.117, so the typical Pacific sample is about six times the typical Atlantic one. I would not use the means, which are 283 and 595: only 4.7 percent of Atlantic samples are above the Atlantic mean, so that number describes a few extreme tows rather than the ocean.</p>
<p>The cleaning decision that cost the most was dropping 5,792 rows with no measurement. They were all Nurdle Patrol beach surveys reported as pieces found per ten minutes of searching, and there is no way to convert an effort-based count into a concentration, so a third of the archive was removed at the first step.</p>
<p>What this cannot tell you is whether the difference is the ocean or the instrument. The Atlantic has 6,216 samples to the Pacific’s 799, 61 percent of the Atlantic rows come from one organisation, and every one of the 489 highest readings in the file was taken with a bottle or a bucket rather than a net. There is no Indian Ocean here at all. The file is an archive of where people have sampled, and the garbage patch is not in it as a measurement.</p>
</div>
</div>
</section>
<section id="where-the-marks-are" class="level2">
<h2 class="anchored" data-anchor-id="where-the-marks-are">Where the marks are</h2>
<p>If you compare your notebook against this key, look for these four things before you look at anything else.</p>
<ol type="1">
<li><strong>Your task 6 answer names the protocol.</strong> The 5,792 nulls are one citizen-science programme reporting pieces per ten minutes, and every row of that programme is null. A markdown cell that says “dropped the missing values” without saying what they were is where the mark is lost.</li>
<li><strong>Your task 23 answer says NOAA is not wrong.</strong> The two classifiers disagree because <code>Density Class</code> is relative to each contributing study and yours is absolute. An answer that concludes NOAA made a mistake has read the <code>Density Range</code> table but not understood it.</li>
<li><strong>You treated the 3,087 zeros as data.</strong> Filtering them was necessary for <code>np.log10</code>, not for cleanliness, and everything after task 17 describes samples that found plastic.</li>
<li><strong>Your Part 7 answer hedges the ocean comparison on how the samples were collected</strong>, and every number in it has a code cell above it that produced it. Quoting a number without the cell that produced it is an easy way to lose marks on this exercise.</li>
</ol>
<p>⬅️ Back to <a href="../../course-materials/eod-practice/eod-day4-2026.html">the exercise</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><img src="../../images/bren-logo.png" alt="The Bren School of Environmental Science &amp; Management logo" width="250"></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This website is built with <a href="https://github.com/EDS-217-Essential-Python/EDS-217-Essential-Python.github.io"><i class="fa-brands fa-github" title="the github octocat logo" aria-label="github"></i></a> and <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>