<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Answer Key</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../course-materials/assets/css/exercises.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">EDS 217</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">🏠 home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-daily-materials" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">🗓️ daily materials</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-daily-materials">    
        <li>
    <a class="dropdown-item" href="../../course-materials/day1.html">
 <span class="dropdown-text">1️⃣ Day 1 (8/31)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day2.html">
 <span class="dropdown-text">2️⃣ Day 2 (9/1)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day3.html">
 <span class="dropdown-text">3️⃣ Day 3 (9/2)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day4.html">
 <span class="dropdown-text">4️⃣ Day 4 (9/3)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day5.html">
 <span class="dropdown-text">5️⃣ Day 5 (9/4)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day6.html">
 <span class="dropdown-text">6️⃣ Day 6 (9/8)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day7.html">
 <span class="dropdown-text">7️⃣ Day 7 (9/9)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day8.html">
 <span class="dropdown-text">8️⃣ Day 8 (9/10)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day9.html">
 <span class="dropdown-text">9️⃣ Day 9 (9/11)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-interactive-sessions" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">💻 interactive sessions</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-interactive-sessions">    
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1a_positron_notebooks.html">
 <span class="dropdown-text">Session 1a - ⚒️ Positron &amp; Jupyter Notebooks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1b_python_essentials.html">
 <span class="dropdown-text">Session 1b - 🐍 Python Essentials</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1c_data_science_workflow_1.html">
 <span class="dropdown-text">Session 1c - 🎬 The Python Data Science Workflow, Part 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1d_data_science_workflow_2.html">
 <span class="dropdown-text">Session 1d - 🎬 The Python Data Science Workflow, Part 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/2a_reading_data.html">
 <span class="dropdown-text">Session 2a - 🐼 Reading Data into pandas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/2b_exploring_data.html">
 <span class="dropdown-text">Session 2b - 🔎 Exploring a DataFrame</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/2d_lists_and_dicts.html">
 <span class="dropdown-text">Session 2d - 📝 Lists &amp; Dictionaries</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/3a_booleans_and_conditionals.html">
 <span class="dropdown-text">Session 3a - 📝 Booleans &amp; Conditionals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/3b_filtering_data.html">
 <span class="dropdown-text">Session 3b - 🔍 The Filter Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/3c_sorting_and_ranking.html">
 <span class="dropdown-text">Session 3c - 🥇 The Top-N Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4a_cleaning_data.html">
 <span class="dropdown-text">Session 4a - 🧼 Missing, Duplicated, Miscast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4b_functions.html">
 <span class="dropdown-text">Session 4b - ⚙️ Write It Once, Name It, Use It</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4c_transforming_data.html">
 <span class="dropdown-text">Session 4c - ➕ The Derived-Column Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/5a_grouping_data.html">
 <span class="dropdown-text">Session 5a - 🗂️ The Split-Apply-Combine Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/5b_aggregating_data.html">
 <span class="dropdown-text">Session 5b - 📊 Several Answers at Once</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/5d_loops_over_groups.html">
 <span class="dropdown-text">Session 5d - 🔁 When a Pattern Is Not Enough</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6a_joining_data.html">
 <span class="dropdown-text">Session 6a - 🔗 The Join Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6b_reshaping_data.html">
 <span class="dropdown-text">Session 6b - 🧩 Long and Wide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6c_dates.html">
 <span class="dropdown-text">Session 6c - 📆 A Date Is Not a Number</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/70_building_a_table.html">
 <span class="dropdown-text">Session 7.0 - 🧱 Building a Table Row by Row</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7a_matplotlib.html">
 <span class="dropdown-text">Session 7a - 🖼️ The Anatomy of a Figure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7b_seaborn.html">
 <span class="dropdown-text">Session 7b - 🎨 Name the Columns, Not the Colours</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7d_project_kickoff.html">
 <span class="dropdown-text">Session 7d - 🚀 Project Kickoff</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-coding-colabs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">🙌 coding colabs</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-coding-colabs">    
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/2c_exploring_unfamiliar_data.html">
 <span class="dropdown-text">🙌 Session 2c - Five Claims About a Dataset You’ve Never Seen</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/3d_ranking_questions.html">
 <span class="dropdown-text">🙌 Session 3d - Which One, and How Do You Know?</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/4d_cleaning_messy_data.html">
 <span class="dropdown-text">🙌 Session 4d - From Field Sheet to DataFrame</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/5c_grouped_comparisons.html">
 <span class="dropdown-text">🙌 Session 5c - The Comparison You Made Yesterday, Properly</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/6d_two_table_exercise.html">
 <span class="dropdown-text">🙌 Session 6d - Two Records, Sixty-Six Years Apart</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/7c_penguins.html">
 <span class="dropdown-text">🙌 Session 7c - One Cloud of Points, Three Species</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../cheatsheets.html"> 
<span class="menu-text">👀 cheatsheets</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-resources" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">📚 resources</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-resources">    
        <li>
    <a class="dropdown-item" href="https://docs.python.org/3/" target="_blank">
 <span class="dropdown-text">📚 Python Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pandas.pydata.org/docs/" target="_blank">
 <span class="dropdown-text">📚 Pandas Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://numpy.org/doc/stable/" target="_blank">
 <span class="dropdown-text">📚 Numpy Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://matplotlib.org/stable/contents.html" target="_blank">
 <span class="dropdown-text">📚 Matplotlib Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://seaborn.pydata.org/" target="_blank">
 <span class="dropdown-text">📚 Seaborn Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://positron.posit.co/" target="_blank">
 <span class="dropdown-text">📚 Positron Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://docs.anaconda.com/" target="_blank">
 <span class="dropdown-text">📚 Anaconda Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://stackoverflow.com/" target="_blank">
 <span class="dropdown-text">📚 Stack Overflow</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://realpython.com/" target="_blank">
 <span class="dropdown-text">📚 Real Python</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://towardsdatascience.com/" target="_blank">
 <span class="dropdown-text">📚 Towards Data Science</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.datacamp.com/" target="_blank">
 <span class="dropdown-text">📚 DataCamp</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.kaggle.com/" target="_blank">
 <span class="dropdown-text">📚 Kaggle</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="http://pythontutor.com/" target="_blank">
 <span class="dropdown-text">🧰 Python Tutor</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pandastutor.com/vis.html#" target="_blank">
 <span class="dropdown-text">🧰 Pandas Tutor</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://wesmckinney.com/book/" target="_blank">
 <span class="dropdown-text">📙 Python for Data Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://jakevdp.github.io/PythonDataScienceHandbook/" target="_blank">
 <span class="dropdown-text">📙 Python for Data Science Handbook</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/jakevdp/PythonDataScienceHandbook" target="_blank">
 <span class="dropdown-text">📙 Python Data Science Handbook (GitHub)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://talkpython.fm/" target="_blank">
 <span class="dropdown-text">📻 Talk Python to Me</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/EDS-217-Essential-Python/EDS-217-Essential-Python.github.io" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-left">
      <h1 class="title">Answer Key</h1>
            <p class="subtitle lead">🍌 The Banana Index: Ranking the Cost of Food</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta column-page-left">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#setup" id="toc-setup" class="nav-link active" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#part-1-get-your-bearings" id="toc-part-1-get-your-bearings" class="nav-link" data-scroll-target="#part-1-get-your-bearings">Part 1: Get your bearings</a></li>
  <li><a href="#part-2-three-rankings" id="toc-part-2-three-rankings" class="nav-link" data-scroll-target="#part-2-three-rankings">Part 2: Three rankings</a></li>
  <li><a href="#part-3-which-foods-are-on-every-list" id="toc-part-3-which-foods-are-on-every-list" class="nav-link" data-scroll-target="#part-3-which-foods-are-on-every-list">Part 3: Which foods are on every list?</a></li>
  <li><a href="#part-4-filtering-by-score" id="toc-part-4-filtering-by-score" class="nav-link" data-scroll-target="#part-4-filtering-by-score">Part 4: Filtering by score</a></li>
  <li><a href="#part-5-land-not-carbon" id="toc-part-5-land-not-carbon" class="nav-link" data-scroll-target="#part-5-land-not-carbon">Part 5: Land, not carbon</a></li>
  <li><a href="#part-6-cheese" id="toc-part-6-cheese" class="nav-link" data-scroll-target="#part-6-cheese">Part 6: Cheese</a></li>
  <li><a href="#part-7-write-it-up" id="toc-part-7-write-it-up" class="nav-link" data-scroll-target="#part-7-write-it-up">Part 7: Write it up</a></li>
  <li><a href="#where-the-marks-are" id="toc-where-the-marks-are" class="nav-link" data-scroll-target="#where-the-marks-are">Where the marks are</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block column-page-left" id="quarto-document-content">





<div class="callout callout-style-default callout-important callout-titled" title="How to use this key">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How to use this key
</div>
</div>
<div class="callout-body-container callout-body">
<p>Work the exercise first, then come here. The code below is <strong>one</strong> correct answer, not the only one. If your code looks different but produces the same numbers, you were right.</p>
<p>The written answers matter more than the code. You can already tell whether your code ran. What you cannot check on your own is whether you read the result correctly, and that is what the green <strong>Answer</strong> boxes are for. Compare your markdown cells against them.</p>
<p>⬅️ Back to <a href="../../course-materials/eod-practice/eod-day3-2026.html">the exercise</a></p>
</div>
</div>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<div id="8138fd91" class="cell" data-execution_count="1">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="st">'https://eds-217-essential-python.github.io/data/banana_index.csv'</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(url, index_col<span class="op">=</span><span class="st">'entity'</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>df.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>(160, 16)</code></pre>
</div>
</div>
<div id="3fba1aad" class="cell" data-execution_count="2">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.drop([<span class="st">'year'</span>, <span class="st">'Banana values'</span>, <span class="st">'type'</span>, <span class="st">'Chart?'</span>, <span class="st">'Unnamed: 16'</span>], axis<span class="op">=</span><span class="st">'columns'</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df.columns.tolist()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="2">
<pre><code>['emissions_kg',
 'emissions_1000kcal',
 'emissions_100g_protein',
 'emissions_100g_fat',
 'land_use_kg',
 'land_use_1000kcal',
 'Land use per 100 grams of protein',
 'Land use per 100 grams of fat',
 'Bananas index (kg)',
 'Bananas index (1000 kcalories)',
 'Bananas index (100g protein)']</code></pre>
</div>
</div>
</section>
<section id="part-1-get-your-bearings" class="level2">
<h2 class="anchored" data-anchor-id="part-1-get-your-bearings">Part 1: Get your bearings</h2>
<p><strong>1. How many foods are in the dataset, and how many columns are left after the drop?</strong></p>
<div id="77ce5c99" class="cell" data-execution_count="3">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>(160, 11)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>160 foods and 11 columns.</strong> The file arrived with 16 columns and you dropped 5, so 11 remain. The number of rows never changed, because dropping columns does not remove foods.</p>
</div>
</div>
<p><strong>2. Display the first few rows. What do the three columns whose names begin with <code>Bananas index</code> contain?</strong></p>
<div id="e713d556" class="cell" data-execution_count="4">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">emissions_kg</th>
<th data-quarto-table-cell-role="th">emissions_1000kcal</th>
<th data-quarto-table-cell-role="th">emissions_100g_protein</th>
<th data-quarto-table-cell-role="th">emissions_100g_fat</th>
<th data-quarto-table-cell-role="th">land_use_kg</th>
<th data-quarto-table-cell-role="th">land_use_1000kcal</th>
<th data-quarto-table-cell-role="th">Land use per 100 grams of protein</th>
<th data-quarto-table-cell-role="th">Land use per 100 grams of fat</th>
<th data-quarto-table-cell-role="th">Bananas index (kg)</th>
<th data-quarto-table-cell-role="th">Bananas index (1000 kcalories)</th>
<th data-quarto-table-cell-role="th">Bananas index (100g protein)</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">entity</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Ale</td>
<td>0.488690</td>
<td>0.317338</td>
<td>0.878525</td>
<td>2.424209</td>
<td>0.811485</td>
<td>0.601152</td>
<td>1.577687</td>
<td>3.065766</td>
<td>0.559558</td>
<td>0.362340</td>
<td>0.113771</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Almond butter</td>
<td>0.387011</td>
<td>0.067265</td>
<td>0.207599</td>
<td>0.079103</td>
<td>7.683045</td>
<td>1.296870</td>
<td>3.608433</td>
<td>1.495297</td>
<td>0.443134</td>
<td>0.076804</td>
<td>0.026885</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Almond milk</td>
<td>0.655888</td>
<td>2.222230</td>
<td>13.595512</td>
<td>4.057470</td>
<td>1.370106</td>
<td>2.675063</td>
<td>12.687839</td>
<td>4.600530</td>
<td>0.751002</td>
<td>2.537364</td>
<td>1.760651</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Almonds</td>
<td>0.602368</td>
<td>0.105029</td>
<td>0.328335</td>
<td>0.119361</td>
<td>8.230927</td>
<td>1.423376</td>
<td>4.261040</td>
<td>1.610136</td>
<td>0.689721</td>
<td>0.119923</td>
<td>0.042520</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Apple juice</td>
<td>0.458378</td>
<td>0.955184</td>
<td>29.152212</td>
<td>19.754980</td>
<td>0.660629</td>
<td>1.382839</td>
<td>43.232158</td>
<td>26.246743</td>
<td>0.524851</td>
<td>1.090638</td>
<td>3.775280</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>Each one is a <strong>ratio</strong>, not a measurement. Each column divides a food’s climate cost by the climate cost of the same amount of banana, and the three columns differ only in what “the same amount” means: a kilogram of food, a thousand calories of food, or a hundred grams of protein. So a score of 20 means twenty bananas’ worth, on whichever basis that column uses. The raw emissions columns those ratios were built from are still in the table, which is what lets you check the arithmetic yourself.</p>
</div>
</div>
<p><strong>3. Run <code>.info()</code>. Two columns have missing values. Which, and how many?</strong></p>
<div id="9de3ceb2" class="cell" data-execution_count="5">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Index: 160 entries, Ale to Yoghurt
Data columns (total 11 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   emissions_kg                       160 non-null    float64
 1   emissions_1000kcal                 160 non-null    float64
 2   emissions_100g_protein             158 non-null    float64
 3   emissions_100g_fat                 160 non-null    float64
 4   land_use_kg                        160 non-null    float64
 5   land_use_1000kcal                  160 non-null    float64
 6   Land use per 100 grams of protein  158 non-null    float64
 7   Land use per 100 grams of fat      160 non-null    float64
 8   Bananas index (kg)                 160 non-null    float64
 9   Bananas index (1000 kcalories)     160 non-null    float64
 10  Bananas index (100g protein)       160 non-null    float64
dtypes: float64(11)
memory usage: 15.0+ KB</code></pre>
</div>
</div>
<div id="8c2364dd" class="cell" data-execution_count="6">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df.isnull().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>emissions_kg                         0
emissions_1000kcal                   0
emissions_100g_protein               2
emissions_100g_fat                   0
land_use_kg                          0
land_use_1000kcal                    0
Land use per 100 grams of protein    2
Land use per 100 grams of fat        0
Bananas index (kg)                   0
Bananas index (1000 kcalories)       0
Bananas index (100g protein)         0
dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong><code>emissions_100g_protein</code> and <code>Land use per 100 grams of protein</code>, two missing values each.</strong></p>
<p>Both are per-protein measures, and that is not a coincidence. A food with no protein at all cannot have a per-protein figure, because the division has nothing to divide by. The missing values are telling you something true about the food rather than something careless about the data collection. A null is sometimes a fact, and this one is worth pausing on.</p>
</div>
</div>
<p><strong>4. What is the value of <code>Bananas index (kg)</code> for <code>Bananas</code> itself? Explain in a sentence why the number has to come out that way.</strong></p>
<div id="97104d5f" class="cell" data-execution_count="7">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df.loc[<span class="st">'Bananas'</span>, <span class="st">'Bananas index (kg)'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>np.float64(1.0)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>1.0</strong>, and it could not be anything else. The index is each food’s emissions divided by the banana’s emissions, so the banana’s own row is its emissions divided by itself. The banana is the unit of the scale, in the same way that a metre is one metre long.</p>
</div>
</div>
</section>
<section id="part-2-three-rankings" class="level2">
<h2 class="anchored" data-anchor-id="part-2-three-rankings">Part 2: Three rankings</h2>
<p><strong>5, 6 and 7. The three top-10 lists.</strong></p>
<div id="1b2914a8" class="cell" data-execution_count="8">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Bananas index (kg)'</span>].sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>entity
Beef steak         148.563324
Beef mince         108.816189
Beef meatballs      81.052853
Beef burger         61.803856
Lamb chops          35.383303
Lamb (leg)          35.198904
Lamb burgers        30.833345
Cottage cheese      28.944313
Parmesan cheese     27.499275
Prawns              23.943772
Name: Bananas index (kg), dtype: float64</code></pre>
</div>
</div>
<div id="4a52789f" class="cell" data-execution_count="9">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Bananas index (1000 kcalories)'</span>].sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>entity
Beef steak        77.752629
Beef mince        54.049393
Beef meatballs    35.782826
Cottage cheese    33.508657
Prawns            30.063042
Lettuce           28.915534
Raspberries       28.105624
Beef burger       25.011498
Lamb (leg)        17.335509
Coconut milk      14.670763
Name: Bananas index (1000 kcalories), dtype: float64</code></pre>
</div>
</div>
<div id="3eb7e0a0" class="cell" data-execution_count="10">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Bananas index (100g protein)'</span>].sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>entity
Coconut milk      33.320155
Sugar             20.685802
Grapes            15.128521
Beef steak         8.312805
Raspberries        7.878815
Beef mince         6.878002
Marmalade          6.495684
Butter             6.192303
Lettuce            5.173570
Beef meatballs     4.612929
Name: Bananas index (100g protein), dtype: float64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>Three lists of ten foods each, and the only thing that changed between them is the column name. By kilogram the top ten is four beef products, three lamb, two cheeses and prawns. Per thousand calories the beef stays at the top and lettuce, raspberries and coconut milk join it. Per hundred grams of protein coconut milk, sugar and grapes take the first three places while beef steak, beef mince and beef meatballs hold fourth, sixth and tenth.</p>
<p>If your numbers match but your row order differs, check that you passed <code>ascending=False</code>. If you got a table with eleven columns rather than a single labelled column, you used the whole-table form of the top-N pattern, which is not wrong but is harder to read here.</p>
</div>
</div>
<p><strong>8. In a markdown cell, describe in two or three sentences how the three lists differ from one another. What kind of food rises to the top when the denominator changes from a kilogram to a thousand calories, and what kind rises again when it changes to a hundred grams of protein?</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ranked <strong>per kilogram</strong>, the list is meat: four beef products, three lamb, two cheeses and prawns. Ranked <strong>per thousand calories</strong>, the beef stays but lamb largely drops out and lettuce and raspberries appear, because they are mostly water and you have to eat a great deal of either to obtain a thousand calories. Ranked <strong>per hundred grams of protein</strong>, three foods with almost no protein in them take the top places: coconut milk, sugar and grapes, because dividing by a number close to zero blows the ratio up. The beef does not leave, though. Beef steak is still fourth, beef mince sixth and beef meatballs tenth, so the protein ranking mixes the genuinely costly foods together with the arithmetic artefacts.</p>
<p>So the answer to the question as asked: moving from a kilogram to a thousand calories promotes <strong>bulky, watery foods</strong>, because it takes a lot of lettuce or raspberries to reach a thousand calories. Moving again to a hundred grams of protein promotes <strong>foods with almost no protein</strong>, because the denominator gets very small. Neither move is telling you those foods became worse. Both are telling you the question changed.</p>
</div>
</div>
</section>
<section id="part-3-which-foods-are-on-every-list" class="level2">
<h2 class="anchored" data-anchor-id="part-3-which-foods-are-on-every-list">Part 3: Which foods are on every list?</h2>
<p><strong>9. Question 8 was about how the lists differ. Now find what they agree on. Print the three top-10 lists again, one after another, and compare them by eye. In a markdown cell, write down the exact set of foods that appear in </strong>all three<strong>, and say how many foods appear on one list only.</strong></p>
<div id="e60518d1" class="cell" data-execution_count="11">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Top 10 for Bananas index (kg):'</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">'Bananas index (kg)'</span>].sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>))</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">Top 10 for Bananas index (1000 kcalories):'</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">'Bananas index (1000 kcalories)'</span>].sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>))</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'</span><span class="ch">\n</span><span class="st">Top 10 for Bananas index (100g protein):'</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">'Bananas index (100g protein)'</span>].sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Top 10 for Bananas index (kg):
entity
Beef steak         148.563324
Beef mince         108.816189
Beef meatballs      81.052853
Beef burger         61.803856
Lamb chops          35.383303
Lamb (leg)          35.198904
Lamb burgers        30.833345
Cottage cheese      28.944313
Parmesan cheese     27.499275
Prawns              23.943772
Name: Bananas index (kg), dtype: float64

Top 10 for Bananas index (1000 kcalories):
entity
Beef steak        77.752629
Beef mince        54.049393
Beef meatballs    35.782826
Cottage cheese    33.508657
Prawns            30.063042
Lettuce           28.915534
Raspberries       28.105624
Beef burger       25.011498
Lamb (leg)        17.335509
Coconut milk      14.670763
Name: Bananas index (1000 kcalories), dtype: float64

Top 10 for Bananas index (100g protein):
entity
Coconut milk      33.320155
Sugar             20.685802
Grapes            15.128521
Beef steak         8.312805
Raspberries        7.878815
Beef mince         6.878002
Marmalade          6.495684
Butter             6.192303
Lettuce            5.173570
Beef meatballs     4.612929
Name: Bananas index (100g protein), dtype: float64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Beef steak, Beef mince and Beef meatballs</strong>, and nothing else, survive all three ways of asking the question.</p>
<p><strong>Seven foods appear on one list only:</strong> lamb chops, lamb burgers and parmesan cheese from the kilogram ranking, and butter, grapes, marmalade and sugar from the protein ranking. Seven more appear on exactly two. Thirty ranking places are shared out among only seventeen different foods, so the three lists overlap a great deal more than reading them one after another suggests.</p>
</div>
</div>
<p><strong>10. Questions 8 and 9 asked what the lists say. Now say what it means. In a markdown cell, explain what you learn about a food from the fact that it sits near the top of all three lists at once, and what you learn about a food that tops one list and appears on neither of the others. Name one food of each kind from your answer to question 9, and say which of the two tells you more about the food itself rather than about the denominator.</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>A food at the top of all three lists is expensive <strong>however you measure it</strong>. Its ranking does not depend on the choice of denominator, so no reasonable objection about the basis of comparison rescues it. <strong>Beef steak</strong> is the clearest case: first by weight, first by calorie, fourth by protein.</p>
<p>A food that tops one list only is telling you about the <strong>denominator</strong>, not about the food. <strong>Sugar</strong> is second per hundred grams of protein and appears nowhere else, because sugar has essentially no protein, and a small number divided by a number close to zero is large. The arithmetic behind the ranking is correct, but the claim it seems to make about sugar’s climate cost is misleading.</p>
<p>To answer the last part directly: the food on all three lists tells you more about the food. Beef steak is costly on every basis anyone has proposed, so there is no denominator you could switch to that would rescue it. Sugar’s position tells you about the denominator instead, and it would move the moment you picked a different one.</p>
<p>The practical lesson is that the choice of denominator is an argument, not a technicality. Pick the one that matches what the food is actually for. Compare protein sources per gram of protein and staples per calorie.</p>
</div>
</div>
</section>
<section id="part-4-filtering-by-score" class="level2">
<h2 class="anchored" data-anchor-id="part-4-filtering-by-score">Part 4: Filtering by score</h2>
<p><strong>11. Use the filter pattern to find every food with a <code>Bananas index (kg)</code> above 10. How many are there?</strong></p>
<div id="660656b7" class="cell" data-execution_count="12">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>expensive_by_weight <span class="op">=</span> df[df[<span class="st">'Bananas index (kg)'</span>] <span class="op">&gt;</span> <span class="dv">10</span>]</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>expensive_by_weight.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>(34, 11)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>34 foods</strong>, which is a little over one fifth of the dataset.</p>
</div>
</div>
<p><strong>12 and 13. The <code>~</code> version, the <code>&lt; 1</code> version, and why they differ.</strong></p>
<div id="6bd8b326" class="cell" data-execution_count="13">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>no_worse_than_banana <span class="op">=</span> df[<span class="op">~</span>(df[<span class="st">'Bananas index (kg)'</span>] <span class="op">&gt;</span> <span class="dv">1</span>)]</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(no_worse_than_banana.shape)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>better_than_banana <span class="op">=</span> df[df[<span class="st">'Bananas index (kg)'</span>] <span class="op">&lt;</span> <span class="dv">1</span>]</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(better_than_banana.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(26, 11)
(25, 11)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>26 and 25.</strong> The difference is exactly one row, and it is <strong>Bananas itself</strong>.</p>
<p><code>~(df['Bananas index (kg)'] &gt; 1)</code> keeps every food that is <em>not</em> above 1, which includes foods that equal 1. <code>df['Bananas index (kg)'] &lt; 1</code> is strictly less than, so it drops them. Only one food in this dataset scores exactly 1.0, and by construction it is the banana.</p>
<p>The general point is that <code>~(x &gt; 1)</code> means <code>x &lt;= 1</code>, not <code>x &lt; 1</code>. Negating a strict comparison gives you a non-strict one, and the boundary value moves from one side to the other. Whenever a filter returns one row more or fewer than you expected, check the boundary first.</p>
</div>
</div>
<p><strong>14. Use a two-condition filter to find the foods that score above 5 per kilogram and below 1 per 100 g of protein. End the line with <code>.copy()</code>, because you will display the result a couple of different ways. Display the two banana index columns for those foods, ranked by <code>Bananas index (kg)</code>.</strong></p>
<div id="800d0d65" class="cell" data-execution_count="14">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>costly_but_protein_rich <span class="op">=</span> df[</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    (df[<span class="st">'Bananas index (kg)'</span>] <span class="op">&gt;</span> <span class="dv">5</span>) <span class="op">&amp;</span> (df[<span class="st">'Bananas index (100g protein)'</span>] <span class="op">&lt;</span> <span class="dv">1</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>].copy()</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(costly_but_protein_rich.shape)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>costly_but_protein_rich[</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    [<span class="st">'Bananas index (kg)'</span>, <span class="st">'Bananas index (100g protein)'</span>]</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>].sort_values(<span class="st">'Bananas index (kg)'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(16, 11)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="14">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Bananas index (kg)</th>
<th data-quarto-table-cell-role="th">Bananas index (100g protein)</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">entity</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Halloumi cheese</td>
<td>18.517731</td>
<td>0.911172</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Mackerel</td>
<td>15.579540</td>
<td>0.923830</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Tuna</td>
<td>14.971502</td>
<td>0.643961</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Pork chops</td>
<td>13.927860</td>
<td>0.959339</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Cod</td>
<td>12.485389</td>
<td>0.917841</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Salmon</td>
<td>11.922582</td>
<td>0.625777</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Chicken thighs</td>
<td>11.429423</td>
<td>0.692125</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Pork sausages</td>
<td>11.184385</td>
<td>0.895281</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Chicken wings</td>
<td>10.973219</td>
<td>0.661129</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Cod fish fingers</td>
<td>10.663750</td>
<td>0.899990</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Chicken breast</td>
<td>10.616967</td>
<td>0.585148</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Chicken sausages</td>
<td>9.348264</td>
<td>0.699427</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Cod fishcakes</td>
<td>8.949080</td>
<td>0.847154</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Chicken burger</td>
<td>6.222579</td>
<td>0.474208</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Olive oil</td>
<td>5.936487</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Eggs</td>
<td>5.079982</td>
<td>0.407148</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>16 foods.</strong> The <code>.copy()</code> matters because you display the result twice, once as a count and once as a two-column ranking, and pandas warns you about editing a slice of another table if you skip it.</p>
<p>Note the parentheses. Each condition is wrapped in its own pair before <code>&amp;</code> joins them, and leaving them out gives you an error about ambiguous truth values rather than the answer. Question 15 asks what these 16 foods have in common, so read the row labels before you go on.</p>
</div>
</div>
<p><strong>15. In a markdown cell: what do the foods in question 14 have in common? What is the argument this table makes about how we should compare foods?</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>16 foods, and almost all of them are animal protein</strong>: fish (tuna, cod, cod fish fingers, cod fishcakes, salmon, mackerel), poultry (chicken breast, thighs, wings, sausages, burger), pork chops, pork sausages, eggs, and halloumi. Olive oil is the one that does not fit, and the reason is worth chasing down. Its <code>Bananas index (100g protein)</code> is exactly <code>0.0</code>, and its <code>emissions_100g_protein</code> is one of the two missing values you found in question 3. The zero is standing in for a number nobody could compute, because olive oil has essentially no protein to divide by, so olive oil met your <code>&lt; 1</code> condition without ever being measured. Sunflower oil is the other <code>0.0</code> in that column. A filter cannot tell a real zero from a missing one, and this is the first time in the course that the difference has changed an answer.</p>
<p>The argument is this: these foods look costly when you weigh them and cheap when you weigh what you eat them <strong>for</strong>. Nobody eats 100 g of chicken as a substitute for 100 g of lettuce; they eat it as a source of protein. Comparing per kilogram flatters foods that are mostly water and penalises foods that are dense in the thing you actually want. Choosing a denominator is choosing what question you are asking, and this table is what that choice looks like when it changes the answer.</p>
</div>
</div>
</section>
<section id="part-5-land-not-carbon" class="level2">
<h2 class="anchored" data-anchor-id="part-5-land-not-carbon">Part 5: Land, not carbon</h2>
<p><strong>16, 17 and 18.</strong></p>
<div id="05835c4d" class="cell" data-execution_count="15">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>banana_land_use <span class="op">=</span> df.loc[<span class="st">'Bananas'</span>, <span class="st">'land_use_1000kcal'</span>]</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>banana_land_use</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>np.float64(2.71787661)</code></pre>
</div>
</div>
<div id="c571b799" class="cell" data-execution_count="16">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'land_use_1000kcal'</span>].sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>entity
Beef steak          223.690135
Beef mince          147.166781
Beef meatballs       94.463012
Beef burger          54.560874
Cottage cheese       34.694337
Lettuce              34.681560
Lamb (leg)           21.444985
Lentils              20.535191
Lamb chops           16.711250
Chilli con carne     16.398791
Name: land_use_1000kcal, dtype: float64</code></pre>
</div>
</div>
<div id="69f7678b" class="cell" data-execution_count="17">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>hungriest <span class="op">=</span> df[<span class="st">'land_use_1000kcal'</span>].idxmax()</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(hungriest)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.loc[hungriest, <span class="st">'land_use_1000kcal'</span>] <span class="op">/</span> df.loc[<span class="st">'Bananas'</span>, <span class="st">'land_use_1000kcal'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Beef steak
82.30327093473166</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>A banana uses <strong>2.72 square metres</strong> of land per thousand calories. The most land-hungry food is <strong>beef steak</strong>, at 223.7 square metres per thousand calories, which is <strong>82.3 times</strong> the banana’s land use.</p>
<p>Note that <code>.idxmax()</code> gave you the <strong>label</strong> and not the number. Returning the label is the whole reason <code>.idxmax()</code> exists: paired with <code>.loc[]</code>, it lets you ask “which one?” and then “how much?” as two separate, readable steps.</p>
</div>
</div>
<p><strong>19. Compare your land-use top 10 with your emissions top 10 from question 6. Both are measured per thousand calories, so they are the fair comparison. Are they the same foods? Answer in a markdown cell, and name one food that appears on one list and not the other.</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Seven of the ten foods are the same</strong>: beef steak, beef mince, beef meatballs, beef burger, cottage cheese, lamb (leg) and lettuce. So the two measures agree far more than they disagree, and beef sits at the top of both.</p>
<p>Three foods appear only in the land-use list: <strong>lentils</strong>, lamb chops and chilli con carne. Lentils are the interesting one. They take a lot of land per calorie and emit comparatively little, so a ranking built on carbon alone would tell you nothing about them. Three foods appear only in the emissions list: prawns, raspberries and coconut milk. Prawns are the mirror image, because much of their footprint comes from fuel and refrigeration rather than from land.</p>
<p>Both lists here are per thousand calories, which is what makes the comparison fair. Had you compared the land-use list against your question 5 ranking, which is per kilogram, some of the difference you found would have been the change of denominator rather than a difference between land and carbon.</p>
<p>Land and carbon are correlated but not interchangeable. A food can be costly in one and unremarkable in the other, and which you measure determines which foods you notice.</p>
</div>
</div>
</section>
<section id="part-6-cheese" class="level2">
<h2 class="anchored" data-anchor-id="part-6-cheese">Part 6: Cheese</h2>
<p><strong>20. Build a table of just the cheeses, then find the cheese with the highest <code>Bananas index (1000 kcalories)</code>.</strong></p>
<div id="ba530451" class="cell" data-execution_count="18">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>cheese <span class="op">=</span> df.<span class="bu">filter</span>(like<span class="op">=</span><span class="st">'heese'</span>, axis<span class="op">=</span><span class="st">'rows'</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(cheese.shape)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>cheese[<span class="st">'Bananas index (1000 kcalories)'</span>].sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(12, 11)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>entity
Cottage cheese          33.508657
Mozzarella cheese        7.723795
Parmesan cheese          7.272295
Goat’s cheese            7.102344
Blue cheese              6.980327
Cheddar cheese           6.172845
Halloumi cheese          6.031632
Macaroni cheese          5.989042
Ricotta cheese           5.939072
Feta cheese              5.757135
Chocolate cheesecake     1.368605
Cheesecake               0.798615
Name: Bananas index (1000 kcalories), dtype: float64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Cottage cheese, at 33.51.</strong> It is far above the rest: the next cheese, mozzarella, is 7.72, so cottage cheese is more than four times the second-place figure. Cottage cheese is largely water, so a thousand calories of it is a great deal of cheese.</p>
</div>
</div>
<p><strong>21. How many rows did <code>.filter(like='heese')</code> give you? Look at the names carefully. Is every one of them a cheese? In a markdown cell, say what the result tells you about matching rows on text.</strong></p>
<div id="af94652c" class="cell" data-execution_count="19">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>cheese.index.tolist()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="19">
<pre><code>['Blue cheese',
 'Cheddar cheese',
 'Cheesecake',
 'Chocolate cheesecake',
 'Cottage cheese',
 'Feta cheese',
 'Goat’s cheese',
 'Halloumi cheese',
 'Macaroni cheese',
 'Mozzarella cheese',
 'Parmesan cheese',
 'Ricotta cheese']</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>12 rows, and no, they are not all cheeses.</strong> <code>Cheesecake</code> and <code>Chocolate cheesecake</code> are desserts, and <code>Macaroni cheese</code> is a cooked dish rather than a cheese. Only nine of the twelve are cheese in the sense you meant.</p>
<p>Matching on a substring matches <strong>strings, not meanings</strong>. <code>.filter(like='heese')</code> did exactly what you asked and had no way to know what you intended. Printing the labels and reading them is why you read them after any text-based selection, rather than trusting the row count. The habit of looking at what a filter caught, and not just how much it caught, will save you repeatedly.</p>
</div>
</div>
<p><strong>22. Where does the top cheese sit in the whole dataset’s calorie ranking? Check it against your answer to question 6.</strong></p>
<div id="d30a6bb5" class="cell" data-execution_count="20">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Bananas index (1000 kcalories)'</span>].sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>entity
Beef steak        77.752629
Beef mince        54.049393
Beef meatballs    35.782826
Cottage cheese    33.508657
Prawns            30.063042
Lettuce           28.915534
Raspberries       28.105624
Beef burger       25.011498
Lamb (leg)        17.335509
Coconut milk      14.670763
Name: Bananas index (1000 kcalories), dtype: float64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fourth out of 160</strong>, behind beef steak, beef mince and beef meatballs. It is visible in your question 6 answer, which is the check: cottage cheese was already sitting in that top 10, and finding it again from the cheese table means both calculations agree.</p>
<p>Cottage cheese is the only non-meat food in the top four of the calorie ranking, which is what makes the cheese section worth having.</p>
</div>
</div>
</section>
<section id="part-7-write-it-up" class="level2">
<h2 class="anchored" data-anchor-id="part-7-write-it-up">Part 7: Write it up</h2>
<p>There is no single right answer here. A strong response cites at least three numbers you computed, names at least one disagreement between the rankings, and reaches a conclusion the numbers support. Here is one that would earn full marks.</p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ A model answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ A model answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>Cutting bananas is not where the gains are. A banana scores 1.0 on the kilogram index by definition, and it sits at 135th of 160 foods on that ranking. Beef steak scores 148.6 on the same scale, so a kilogram of steak emits roughly 149 times what a kilogram of bananas emits, and per thousand calories beef steak needs 82.3 times the land a banana needs. Removing bananas from a diet changes a very small number and creates a gap that has to be filled by something else.</p>
<p>The dataset does make bananas look worse under one measure. Per hundred grams of protein they rise to 63rd of 160, above eggs, chicken breast, salmon, tuna, cod and pork chops, because a banana has almost no protein and the division inflates the ratio. The disagreement between the rankings is the point rather than a flaw. Coconut milk, sugar and grapes top the protein ranking for the same arithmetic reason, and nobody would argue that sugar is a worse climate choice than beef. The comparison is only meaningful when the denominator matches what the food is for, and bananas are not a protein source.</p>
<p>If my friend wants a change that shows up in the numbers, the place to look is the 34 foods scoring above 10 per kilogram, which is a little over a fifth of this dataset and is dominated by beef, lamb and cheese. Substituting one of those a week would move more carbon than eliminating bananas entirely.</p>
</div>
</div>
</section>
<section id="where-the-marks-are" class="level2">
<h2 class="anchored" data-anchor-id="where-the-marks-are">Where the marks are</h2>
<p>If you compare your notebook against this key, look for these four things before you look at anything else.</p>
<ol type="1">
<li><strong>Every number in your Part 7 write-up has a code cell above it that produced it.</strong> Quoting a number you did not compute is the single most common way to lose marks on this exercise.</li>
<li><strong>Your Part 4 boundary answer is right.</strong> Questions 12 and 13 differ by one row, and knowing which row and why is the point of asking both.</li>
<li><strong>You looked at the cheese labels</strong> rather than trusting the count.</li>
<li><strong>Your interpretation answers say what the number means</strong>, not what the number is. “34 foods score above 10” restates the output. “34 foods, a fifth of the dataset, and almost all of them are meat or cheese” reads it.</li>
</ol>
<p>⬅️ Back to <a href="../../course-materials/eod-practice/eod-day3-2026.html">the exercise</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><img src="../../images/bren-logo.png" alt="The Bren School of Environmental Science &amp; Management logo" width="250"></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This website is built with <a href="https://github.com/EDS-217-Essential-Python/EDS-217-Essential-Python.github.io"><i class="fa-brands fa-github" title="the github octocat logo" aria-label="github"></i></a> and <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>