<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Answer Key</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../course-materials/assets/css/exercises.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">EDS 217</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">🏠 home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../course-materials/the-data-science-workflow.html"> 
<span class="menu-text">🔟 the workflow</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://docs.google.com/document/d/1yBKyJFT22bKynDn4TzrNwdeZ6lb9NELqCeewhifcugo/edit?usp=sharing" target="_blank"> 
<span class="menu-text">📋 syllabus</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-daily-materials" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">🗓️ daily materials</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-daily-materials">    
        <li>
    <a class="dropdown-item" href="../../course-materials/day1.html">
 <span class="dropdown-text">1️⃣ Day 1 (8/31)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day2.html">
 <span class="dropdown-text">2️⃣ Day 2 (9/1)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day3.html">
 <span class="dropdown-text">3️⃣ Day 3 (9/2)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day4.html">
 <span class="dropdown-text">4️⃣ Day 4 (9/3)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day5.html">
 <span class="dropdown-text">5️⃣ Day 5 (9/4)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day6.html">
 <span class="dropdown-text">6️⃣ Day 6 (9/8)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day7.html">
 <span class="dropdown-text">7️⃣ Day 7 (9/9)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day8.html">
 <span class="dropdown-text">8️⃣ Day 8 (9/10)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day9.html">
 <span class="dropdown-text">9️⃣ Day 9 (9/11)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-interactive-sessions" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">💻 interactive sessions</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-interactive-sessions">    
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1a_positron_notebooks.html">
 <span class="dropdown-text">Session 1a - ⚒️ Positron &amp; Jupyter Notebooks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1b_python_essentials.html">
 <span class="dropdown-text">Session 1b - 🐍 Python Essentials</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1c_data_science_workflow_1.html">
 <span class="dropdown-text">Session 1c - 🎬 The Python Data Science Workflow, Part 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1d_data_science_workflow_2.html">
 <span class="dropdown-text">Session 1d - 🎬 The Python Data Science Workflow, Part 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/2a_reading_data.html">
 <span class="dropdown-text">Session 2a - 🐼 Reading Data into pandas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/2b_exploring_data.html">
 <span class="dropdown-text">Session 2b - 🔎 Exploring a DataFrame</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/2d_lists_and_dicts.html">
 <span class="dropdown-text">Session 2d - 📝 Lists &amp; Dictionaries</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/3a_booleans_and_conditionals.html">
 <span class="dropdown-text">Session 3a - 📝 Booleans &amp; Conditionals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/3b_filtering_data.html">
 <span class="dropdown-text">Session 3b - 🔍 The Filter Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/3c_sorting_and_ranking.html">
 <span class="dropdown-text">Session 3c - 🥇 The Top-N Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4a_cleaning_data.html">
 <span class="dropdown-text">Session 4a - 🧼 Missing, Duplicated, Miscast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4b_functions.html">
 <span class="dropdown-text">Session 4b - ⚙️ Write It Once, Name It, Use It</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4c_transforming_data.html">
 <span class="dropdown-text">Session 4c - ➕ The Derived-Column Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/5a_grouping_data.html">
 <span class="dropdown-text">Session 5a - 🗂️ The Split-Apply-Combine Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/5b_aggregating_data.html">
 <span class="dropdown-text">Session 5b - 📊 Several Answers at Once</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/5d_loops_over_groups.html">
 <span class="dropdown-text">Session 5d - 🔁 When a Pattern Is Not Enough</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6a_joining_data.html">
 <span class="dropdown-text">Session 6a - 🔗 The Join Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6b_reshaping_data.html">
 <span class="dropdown-text">Session 6b - 🧩 Long and Wide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6c_dates.html">
 <span class="dropdown-text">Session 6c - 📆 A Date Is Not a Number</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7a_matplotlib.html">
 <span class="dropdown-text">Session 7a - 🖼️ The Anatomy of a Figure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7b_seaborn.html">
 <span class="dropdown-text">Session 7b - 🎨 Name the Columns, Not the Colours</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7d_project_kickoff.html">
 <span class="dropdown-text">Session 7d - 🚀 Project Kickoff</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-coding-colabs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">🙌 coding colabs</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-coding-colabs">    
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/2c_exploring_unfamiliar_data.html">
 <span class="dropdown-text">🙌 Session 2c - Five Claims About a Dataset You’ve Never Seen</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/3d_ranking_questions.html">
 <span class="dropdown-text">🙌 Session 3d - Which One, and How Do You Know?</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/4d_cleaning_messy_data.html">
 <span class="dropdown-text">🙌 Session 4d - From Field Sheet to DataFrame</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/5c_grouped_comparisons.html">
 <span class="dropdown-text">🙌 Session 5c - The Comparison You Made Last Night, Properly</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/6d_two_table_exercise.html">
 <span class="dropdown-text">🙌 Session 6d - Two Records, Sixty-Six Years Apart</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/7c_penguins.html">
 <span class="dropdown-text">🙌 Session 7c - One Cloud of Points, Three Species</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../cheatsheets.html"> 
<span class="menu-text">👀 cheatsheets</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-resources" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">📚 resources</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-resources">    
        <li>
    <a class="dropdown-item" href="https://docs.python.org/3/" target="_blank">
 <span class="dropdown-text">📚 Python Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pandas.pydata.org/docs/" target="_blank">
 <span class="dropdown-text">📚 Pandas Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://numpy.org/doc/stable/" target="_blank">
 <span class="dropdown-text">📚 Numpy Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://matplotlib.org/stable/contents.html" target="_blank">
 <span class="dropdown-text">📚 Matplotlib Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://seaborn.pydata.org/" target="_blank">
 <span class="dropdown-text">📚 Seaborn Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://positron.posit.co/" target="_blank">
 <span class="dropdown-text">📚 Positron Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://docs.anaconda.com/" target="_blank">
 <span class="dropdown-text">📚 Anaconda Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://stackoverflow.com/" target="_blank">
 <span class="dropdown-text">📚 Stack Overflow</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://realpython.com/" target="_blank">
 <span class="dropdown-text">📚 Real Python</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://towardsdatascience.com/" target="_blank">
 <span class="dropdown-text">📚 Towards Data Science</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.datacamp.com/" target="_blank">
 <span class="dropdown-text">📚 DataCamp</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.kaggle.com/" target="_blank">
 <span class="dropdown-text">📚 Kaggle</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="http://pythontutor.com/" target="_blank">
 <span class="dropdown-text">🧰 Python Tutor</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pandastutor.com/vis.html#" target="_blank">
 <span class="dropdown-text">🧰 Pandas Tutor</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://wesmckinney.com/book/" target="_blank">
 <span class="dropdown-text">📙 Python for Data Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://jakevdp.github.io/PythonDataScienceHandbook/" target="_blank">
 <span class="dropdown-text">📙 Python for Data Science Handbook</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/jakevdp/PythonDataScienceHandbook" target="_blank">
 <span class="dropdown-text">📙 Python Data Science Handbook (GitHub)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://talkpython.fm/" target="_blank">
 <span class="dropdown-text">📻 Talk Python to Me</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/EDS-217-Essential-Python/EDS-217-Essential-Python.github.io" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-left">
      <h1 class="title">Answer Key</h1>
            <p class="subtitle lead">🌲 Forty Thousand Zip Codes 🌴</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta column-page-left">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#setup" id="toc-setup" class="nav-link active" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#part-1-three-files" id="toc-part-1-three-files" class="nav-link" data-scroll-target="#part-1-three-files">Part 1: Three files</a></li>
  <li><a href="#part-2-one-table-out-of-three" id="toc-part-2-one-table-out-of-three" class="nav-link" data-scroll-target="#part-2-one-table-out-of-three">Part 2: One table out of three</a></li>
  <li><a href="#part-3-the-first-map" id="toc-part-3-the-first-map" class="nav-link" data-scroll-target="#part-3-the-first-map">Part 3: The first map</a></li>
  <li><a href="#part-4-what-actually-changed" id="toc-part-4-what-actually-changed" class="nav-link" data-scroll-target="#part-4-what-actually-changed">Part 4: What actually changed</a></li>
  <li><a href="#part-5-states-and-the-count-column" id="toc-part-5-states-and-the-count-column" class="nav-link" data-scroll-target="#part-5-states-and-the-count-column">Part 5: States, and the count column</a></li>
  <li><a href="#part-6-write-it-up" id="toc-part-6-write-it-up" class="nav-link" data-scroll-target="#part-6-write-it-up">Part 6: Write it up</a></li>
  <li><a href="#where-the-marks-are" id="toc-where-the-marks-are" class="nav-link" data-scroll-target="#where-the-marks-are">Where the marks are</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block column-page-left" id="quarto-document-content">





<div class="callout callout-style-default callout-important callout-titled" title="How to use this key">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How to use this key
</div>
</div>
<div class="callout-body-container callout-body">
<p>Work the exercise first, then come here. The code below is <strong>one</strong> correct answer, not the only one. If your code looks different but produces the same numbers, you were right.</p>
<p>The written answers matter more than the code. You can already tell whether your code ran. What you cannot check on your own is whether you read the result correctly, and that is what the green <strong>Answer</strong> boxes are for. Compare your markdown cells against them.</p>
<p>⬅️ Back to <a href="../../course-materials/eod-practice/eod-day7-2026.html">the exercise</a></p>
</div>
</div>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<div id="c8560ac5" class="cell" data-execution_count="1">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>base <span class="op">=</span> <span class="st">'https://eds-217-essential-python.github.io/data/'</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>zones_2012 <span class="op">=</span> pd.read_csv(base <span class="op">+</span> <span class="st">'hardiness_zones_2012.csv'</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>zones_2023 <span class="op">=</span> pd.read_csv(base <span class="op">+</span> <span class="st">'hardiness_zones_2023.csv'</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>zipcodes <span class="op">=</span> pd.read_csv(base <span class="op">+</span> <span class="st">'zip_code_database.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="6d3f005b" class="cell" data-execution_count="2">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>zones_2023[<span class="st">'zipcode'</span>] <span class="op">=</span> zones_2023[<span class="st">'zipcode'</span>].astype(<span class="bu">str</span>).<span class="bu">str</span>.zfill(<span class="dv">5</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>zones_2012[<span class="st">'zipcode'</span>] <span class="op">=</span> zones_2012[<span class="st">'zipcode'</span>].astype(<span class="bu">str</span>).<span class="bu">str</span>.zfill(<span class="dv">5</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>zipcodes[<span class="st">'zip'</span>] <span class="op">=</span> zipcodes[<span class="st">'zip'</span>].astype(<span class="bu">str</span>).<span class="bu">str</span>.zfill(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="part-1-three-files" class="level2">
<h2 class="anchored" data-anchor-id="part-1-three-files">Part 1: Three files</h2>
<p><strong>1. How many rows and columns does each of the three tables have? What are the column names of the two zone tables, and are they the same?</strong></p>
<div id="5a79e0f2" class="cell" data-execution_count="3">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(zones_2012.shape, <span class="bu">list</span>(zones_2012.columns))</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(zones_2023.shape, <span class="bu">list</span>(zones_2023.columns))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(zipcodes.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(40534, 4) ['zipcode', 'zone', 'trange', 'zonetitle']
(39921, 4) ['zipcode', 'zone', 'trange', 'zonetitle']
(42522, 16)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>2012 is 40,534 rows by 4 columns, 2023 is 39,921 by 4, and the zip code database is 42,522 by 16.</strong> The two zone tables have exactly the same four column names, <code>zipcode</code>, <code>zone</code>, <code>trange</code> and <code>zonetitle</code>, in the same order, which is what makes stacking them safe in question 4. The zip code database is a different kind of file: many more columns, and one row per zip code rather than one row per zip code per map.</p>
</div>
</div>
<p><strong>2. Run <code>.isnull().sum()</code> on both zone tables. Then look at <code>.head()</code> of either one and say, in one sentence, what <code>zone</code>, <code>trange</code> and <code>zonetitle</code> each hold and which of the three is redundant.</strong></p>
<div id="7749981a" class="cell" data-execution_count="4">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(zones_2012.isnull().<span class="bu">sum</span>())</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(zones_2023.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>zipcode      0
zone         0
trange       0
zonetitle    0
dtype: int64
  zipcode zone     trange      zonetitle
0   00501   7b    5 to 10    7b: 5 to 10
1   00544   7b    5 to 10    7b: 5 to 10
2   01001   6b    -5 to 0    6b: -5 to 0
3   01002   6a  -10 to -5  6a: -10 to -5
4   01003   6a  -10 to -5  6a: -10 to -5</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>No nulls anywhere in either file</strong>, in any of the four columns. <code>zone</code> is the short label (<code>6a</code>), <code>trange</code> is the five-degree temperature range that label stands for (<code>-10 to -5</code>), and <code>zonetitle</code> is the two of them pasted together with a colon (<code>6a: -10 to -5</code>), so <code>zonetitle</code> tells you nothing that is not already in the other two columns and is the redundant one.</p>
<p>A file with zero nulls is worth a moment of suspicion rather than relief. It usually means every row was assigned a value by a model, which is exactly what happened here: PRISM interpolated a continuous temperature surface and then read a value off it for every zip code. Nothing was left blank because nothing was measured at the zip code.</p>
</div>
</div>
<p><strong>3. The two files do not have the same number of rows. Before you do anything else, write down two different explanations for that which do not involve anybody making a mistake.</strong></p>
<div id="20a23b07" class="cell" data-execution_count="5">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>in_2012_only <span class="op">=</span> <span class="bu">set</span>(zones_2012[<span class="st">'zipcode'</span>]) <span class="op">-</span> <span class="bu">set</span>(zones_2023[<span class="st">'zipcode'</span>])</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>in_2023_only <span class="op">=</span> <span class="bu">set</span>(zones_2023[<span class="st">'zipcode'</span>]) <span class="op">-</span> <span class="bu">set</span>(zones_2012[<span class="st">'zipcode'</span>])</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">len</span>(in_2012_only), <span class="bu">len</span>(in_2023_only))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>635 22</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>Two explanations that involve nobody making a mistake:</p>
<ol type="1">
<li><strong>The zip code system itself changed.</strong> USPS retires zip codes and creates new ones continuously, so eleven years apart the two files are describing two slightly different lists of places. This is the larger effect here: 635 zip codes appear in 2012 and not in 2023, while 22 appear in 2023 and not in 2012.</li>
<li><strong>The two maps were built by different methods.</strong> The 2023 map used a different station network, a finer grid and a longer normals period, so a zip code that could be assigned a value under one procedure need not be assignable under the other.</li>
</ol>
<p>The important consequence comes later: the 2012 file covers a partly different set of locations from the 2023 file, so any comparison of the two whole files compares two different populations. Question 6 does exactly that, and question 17 is where you find out what it cost.</p>
</div>
</div>
</section>
<section id="part-2-one-table-out-of-three" class="level2">
<h2 class="anchored" data-anchor-id="part-2-one-table-out-of-three">Part 2: One table out of three</h2>
<p><strong>4. Add a <code>year</code> column to each zone table, then stack the two of them into one table called <code>zones</code>, using the stacking pattern. How many rows?</strong></p>
<div id="3abdbb9d" class="cell" data-execution_count="6">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>zones_2023[<span class="st">'year'</span>] <span class="op">=</span> <span class="dv">2023</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>zones_2012[<span class="st">'year'</span>] <span class="op">=</span> <span class="dv">2012</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>zones <span class="op">=</span> pd.concat([zones_2023, zones_2012], ignore_index<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>zones.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>(80455, 5)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>80,455 rows and 5 columns</strong>, which is 39,921 plus 40,534 exactly. <code>pd.concat</code> stacked the rows and nothing was dropped or merged, because the two tables had identical column names. The <code>year</code> column is what makes the stack usable: without it the two halves would be indistinguishable once they were in the same table.</p>
</div>
</div>
<p><strong>5. Add <code>trange_min</code> using the line from the Field Note, then confirm it has no nulls and look at its distinct values with <code>.value_counts().sort_index()</code>. In a markdown cell, say what you notice about the spacing of those values and what that means for the phrase “how much warmer”.</strong></p>
<div id="c3bac3d5" class="cell" data-execution_count="7">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>zones[<span class="st">'trange_min'</span>] <span class="op">=</span> zones[<span class="st">'trange'</span>].<span class="bu">str</span>.split().<span class="bu">str</span>.get(<span class="dv">0</span>).astype(<span class="bu">int</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(zones[<span class="st">'trange_min'</span>].isnull().<span class="bu">sum</span>())</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(zones[<span class="st">'trange_min'</span>].value_counts().sort_index())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>0
trange_min
-40       41
-35      617
-30     1879
-25     3099
-20     4857
-15     7642
-10    11034
-5     10605
 0      8916
 5      7295
 10     6822
 15     5911
 20     3921
 25     4003
 30     2153
 35     1425
 40      216
 45       19
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Zero nulls, and only 18 distinct values, every one of them a multiple of five</strong>, running from -40 °F to 45 °F with no gaps and no value in between. There is no zip code at -12 or at 3, because no such label exists.</p>
<p>That spacing is a property of the map and not of the country. <code>trange_min</code> is the cold edge of a five-degree bin, so it is a <strong>label</strong>, not a measurement. The phrase “how much warmer” can therefore only ever be answered here in whole multiples of five degrees, and the honest reading of any difference you compute is “this place crossed a zone boundary”, not “this place warmed by five degrees”. Hold on to that sentence: it is what questions 18 and 22 are about.</p>
</div>
</div>
<p><strong>6. Compute the mean <code>trange_min</code> for each year and report the difference. This is the headline number, and you are about to spend the rest of the practice finding out how much it is worth.</strong></p>
<div id="c4c73691" class="cell" data-execution_count="8">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>means <span class="op">=</span> zones.groupby(<span class="st">'year'</span>)[<span class="st">'trange_min'</span>].mean()</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(means.<span class="bu">round</span>(<span class="dv">3</span>))</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(means[<span class="dv">2023</span>] <span class="op">-</span> means[<span class="dv">2012</span>], <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>year
2012   -1.900
2023    1.017
Name: trange_min, dtype: float64
2.917</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The mean zone minimum is -1.900 °F in 2012 and 1.017 °F in 2023, a difference of 2.917 °F.</strong></p>
<p>Two things are wrong with that number as a headline. First, it is a mean of bin labels, and no place in the file warmed by 2.917 °F, because 2.917 is not a value any zip code can take. Second, it compares two different sets of zip codes, since 635 zip codes are in the 2012 file only. The paired version, computed over the 39,858 zip codes present in both files, is 2.884 °F in question 17’s table. The two agree closely here, which is the reassuring case, but you only know that because you checked.</p>
</div>
</div>
<p><strong>7. Merge <code>zones</code> with <code>zipcodes</code> to attach a state, a latitude and a longitude to every row. The key columns are called different things in the two tables. Compare the row count before and after, then run the merge again with <code>how='left'</code> and find out how many rows failed to match and how many distinct zip codes that is.</strong></p>
<div id="c292b083" class="cell" data-execution_count="9">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>located <span class="op">=</span> pd.merge(zones, zipcodes, left_on<span class="op">=</span><span class="st">'zipcode'</span>, right_on<span class="op">=</span><span class="st">'zip'</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(zones.shape)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(located.shape)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>check <span class="op">=</span> pd.merge(zones, zipcodes, left_on<span class="op">=</span><span class="st">'zipcode'</span>, right_on<span class="op">=</span><span class="st">'zip'</span>, how<span class="op">=</span><span class="st">'left'</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>missing <span class="op">=</span> check[check[<span class="st">'zip'</span>].isnull()]</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(missing.shape)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(missing[<span class="st">'zipcode'</span>].nunique())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>(80455, 6)
(80352, 22)
(103, 22)
63</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>80,455 rows went in and 80,352 came out, so 103 rows were lost, covering 63 distinct zip codes.</strong> The default merge is an inner join, so a zone row whose zip code is absent from the zip code database is silently discarded. The <code>how='left'</code> version is how you make the loss visible: every row survives, and the ones that failed to match are exactly the rows where <code>zip</code> is null.</p>
<p>Note that 103 rows over 63 zip codes means most of those zip codes were lost twice, once in each year. Comparing the row count before and after is the cheapest habit in this whole exercise, and it is the one that catches a merge that quietly deleted a tenth of your data.</p>
</div>
</div>
<p><strong>8. In a markdown cell: 103 rows out of 80,455 did not match, covering 63 zip codes. Is that a number you would fix, a number you would mention, or a number you would ignore? Say which and why. There is more than one defensible answer.</strong></p>
<div id="b9207ab3" class="cell" data-execution_count="10">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">sorted</span>(missing[<span class="st">'zipcode'</span>].unique()))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>['08644', '20252', '25888', '27268', '29486', '33191', '33192', '33198', '34249', '34441', '35270', '40166', '40750', '41021', '41025', '46197', '46210', '46213', '46288', '55131', '56908', '56935', '56966', '56967', '56968', '56969', '56970', '56971', '56973', '56998', '56999', '58803', '60418', '60569', '63380', '64162', '66630', '68544', '72255', '72405', '72643', '72713', '73960', '75036', '75059', '75064', '75072', '76190', '84009', '85288', '86005', '87547', '87654', '88888', '89437', '90134', '95214', '97003', '97079', '97129', '97250', '97252', '97703']</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Mention it, do not fix it.</strong> 103 rows is 0.13 percent of the file, so no result in this notebook can turn on them, and hand-repairing 63 zip codes would take an hour and introduce errors of your own. But you say so in a sentence, because a reader who recomputes your numbers from the raw files should not have to discover the gap themselves.</p>
<p>Printing the codes is what makes the decision defensible rather than lazy. Eleven of the 63 are in the 56900 block, which USPS assigns to federal agencies in Washington DC, and one is 88888, the novelty code for Santa Claus at the North Pole. These are administrative codes and post office box ranges, not towns with gardens in them, so losing them costs the analysis nothing. Had the 63 been a contiguous block of rural counties in one state, the same 0.13 percent would have needed fixing. <strong>Whether a loss matters depends on what was lost, not on how large it is.</strong></p>
</div>
</div>
</section>
<section id="part-3-the-first-map" class="level2">
<h2 class="anchored" data-anchor-id="part-3-the-first-map">Part 3: The first map</h2>
<p><strong>9. Filter <code>located</code> to the 2023 rows only, then draw a scatter plot with <code>longitude</code> across the bottom, <code>latitude</code> up the side, and <code>hue='trange_min'</code>. Make the figure twelve inches by seven. Label both axes and title it.</strong></p>
<div id="1187bbc6" class="cell" data-execution_count="11">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>recent <span class="op">=</span> located[located[<span class="st">'year'</span>] <span class="op">==</span> <span class="dv">2023</span>]</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">7</span>))</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(data<span class="op">=</span>recent, x<span class="op">=</span><span class="st">'longitude'</span>, y<span class="op">=</span><span class="st">'latitude'</span>, hue<span class="op">=</span><span class="st">'trange_min'</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Longitude'</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Latitude'</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Average annual minimum temperature by zip code, 2023'</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="eod-day7-2026-key_files/figure-html/cell-12-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>10. Something is wrong with that figure, and it is not subtle. Describe it in a markdown cell.</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The whole country is crushed into the left-hand 40 percent or so of the figure, and one lone point sits by itself out at the right, near longitude 0.</strong> The x-axis runs from about -125 to 0 because seaborn scaled it to fit every point it was given, and the single point at -2.12 dragged the right edge sixty-five degrees past the coast of Maine.</p>
<p>Nothing is wrong with the colours, the y-axis or the rest of the data. One value in one column set the scale for the entire figure.</p>
</div>
</div>
<p><strong>11. Find the culprit. Use the filter pattern on <code>located</code> to pull out every row with a <code>longitude</code> greater than −60, and print its zip code, state, city, latitude and longitude.</strong></p>
<div id="cb523e94" class="cell" data-execution_count="12">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>located[located[<span class="st">'longitude'</span>] <span class="op">&gt;</span> <span class="op">-</span><span class="dv">60</span>][[<span class="st">'zipcode'</span>, <span class="st">'state'</span>, <span class="st">'primary_city'</span>,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">'latitude'</span>, <span class="st">'longitude'</span>, <span class="st">'year'</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">zipcode</th>
<th data-quarto-table-cell-role="th">state</th>
<th data-quarto-table-cell-role="th">primary_city</th>
<th data-quarto-table-cell-role="th">latitude</th>
<th data-quarto-table-cell-role="th">longitude</th>
<th data-quarto-table-cell-role="th">year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">8343</td>
<td>22350</td>
<td>VA</td>
<td>Alexandria</td>
<td>48.31</td>
<td>-2.12</td>
<td>2023</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">48349</td>
<td>22350</td>
<td>VA</td>
<td>Alexandria</td>
<td>48.31</td>
<td>-2.12</td>
<td>2012</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>12. In a markdown cell, two or three sentences. That is one zip code, appearing once in each year: two rows out of eighty thousand. Look up roughly where latitude 48.3, longitude −2.1 is. Is the temperature reading wrong, or is something else wrong? And say plainly what those two rows did to your figure.</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Zip code 22350, Alexandria, Virginia, recorded at 48.31 N and 2.12 W, which is in Brittany, in northwestern France.</strong> Alexandria is at roughly 38.8 N, 77.0 W, so the latitude is off by about ten degrees and the longitude by about seventy-five. The error is in the <strong>coordinates</strong>, which came from the zip code database, and not in the temperature: 22350 is zone 7b, 5 to 10 °F, which is an ordinary reading for the Washington DC suburbs.</p>
<p>What those two rows did is set the scale. They added no visible information to the figure and they took away most of its resolution, because every other point had to share the remaining 40 percent of the axis. The general problem is this: a single bad value in a column you are plotting on damages every point in the figure, not just its own.</p>
<p>Notice also what would <strong>not</strong> have caught it. The row is not null, not duplicated, not the wrong dtype, and <code>.describe()</code> on <code>longitude</code> reports a maximum of -2.12 with no comment. It survives every cleaning step from Thursday. The figure found it in one second, because a plot is the only summary of a dataset that gives an outlier as much room as it gives everything else.</p>
</div>
</div>
<p><strong>13. Build a table called <code>usa</code> holding only the rows with <code>longitude</code> less than −60, and redraw the 2023 map from it. Then draw the same map for 2012.</strong></p>
<div id="5cb9d683" class="cell" data-execution_count="13">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>usa <span class="op">=</span> located[located[<span class="st">'longitude'</span>] <span class="op">&lt;</span> <span class="op">-</span><span class="dv">60</span>].copy()</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">7</span>))</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(data<span class="op">=</span>usa[usa[<span class="st">'year'</span>] <span class="op">==</span> <span class="dv">2023</span>], x<span class="op">=</span><span class="st">'longitude'</span>, y<span class="op">=</span><span class="st">'latitude'</span>, hue<span class="op">=</span><span class="st">'trange_min'</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Longitude'</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Latitude'</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Average annual minimum temperature by zip code, 2023'</span>)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">7</span>))</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(data<span class="op">=</span>usa[usa[<span class="st">'year'</span>] <span class="op">==</span> <span class="dv">2012</span>], x<span class="op">=</span><span class="st">'longitude'</span>, y<span class="op">=</span><span class="st">'latitude'</span>, hue<span class="op">=</span><span class="st">'trange_min'</span>)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Longitude'</span>)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Latitude'</span>)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Average annual minimum temperature by zip code, 2012'</span>)</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="eod-day7-2026-key_files/figure-html/cell-14-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="eod-day7-2026-key_files/figure-html/cell-14-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>14. You have just drawn a recognizable map of the United States without a mapping library, a projection, or a shapefile. In a markdown cell, one sentence on why that worked here. Then one more: run <code>usa['state'].nunique()</code> and say which parts of the country are not in these files at all.</strong></p>
<div id="50352651" class="cell" data-execution_count="14">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(usa[<span class="st">'state'</span>].nunique())</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">sorted</span>(usa[<span class="st">'state'</span>].unique()))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>49
['AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY']</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>It worked because latitude and longitude are just two numbers, and 40,000 points are enough to show the outline of the country.</strong> A scatter plot of longitude against latitude is already a map at this density, since the country’s shape is visible in where the zip codes are and where they are not. The reason nobody uses this in production is that it is unprojected: distances and areas are distorted, and the further north you go the more the map is stretched sideways. For looking at your own data on the way to an answer, that does not matter.</p>
<p><strong>49 states, which is the 48 contiguous states plus the District of Columbia.</strong> Alaska and Hawaii are absent, and so is Puerto Rico, along with the other territories. That matters more than it looks: the hardiness zones only run from <code>1a</code> to <code>13b</code> because of Alaska at one end and Puerto Rico at the other, and neither end of that scale is in these files. Anything you say here is a statement about the lower 48.</p>
</div>
</div>
<p><strong>15. Put the two maps side by side on your screen and try to see the difference between them. In one honest sentence: can you?</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>No.</strong> The two figures are the same picture: the same colour gradient from the Canadian border to the Gulf, the same mountains showing as cold streaks in the west, the same warm Florida. The change, where it exists, is one bin on an eighteen-bin colour scale at a handful of percent of the points, and no eye can pick that out of 40,000 overlapping markers by flipping between two images. If you thought you saw a difference, you were seeing the difference you expected.</p>
</div>
</div>
</section>
<section id="part-4-what-actually-changed" class="level2">
<h2 class="anchored" data-anchor-id="part-4-what-actually-changed">Part 4: What actually changed</h2>
<p><strong>16. Use the pivot pattern to build a table with one row per zip code and one column per year. Index it on <code>['zipcode', 'state', 'latitude', 'longitude']</code>, put <code>year</code> across the columns and <code>trange_min</code> in the cells, then <code>.reset_index()</code>. What shape is it, and why is that number smaller than 80,000?</strong></p>
<div id="b08c3ef0" class="cell" data-execution_count="15">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>change <span class="op">=</span> usa.pivot_table(index<span class="op">=</span>[<span class="st">'zipcode'</span>, <span class="st">'state'</span>, <span class="st">'latitude'</span>, <span class="st">'longitude'</span>],</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>                         columns<span class="op">=</span><span class="st">'year'</span>, values<span class="op">=</span><span class="st">'trange_min'</span>).reset_index()</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>change.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>(40492, 6)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>40,492 rows and 6 columns.</strong> It is roughly half of 80,350 because the pivot changed what a row means. In <code>usa</code> a row was one zip code in one year, so nearly every zip code had two rows. In <code>change</code> a row is one zip code, with the two years side by side as columns, which is the shape you need to subtract one from the other.</p>
<p>40,492 is the union of the two years’ zip codes, not the intersection, which is why it is slightly more than either file on its own. The pivot did not throw away the zip codes that appear in only one year: it gave them a row with a hole in it, and that hole is question 17.</p>
</div>
</div>
<p><strong>17. Add a <code>temp_diff</code> column: the 2023 value minus the 2012 value. Count its nulls and say what a null means here. Then drop those rows.</strong></p>
<div id="c525ef93" class="cell" data-execution_count="16">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>change[<span class="st">'temp_diff'</span>] <span class="op">=</span> change[<span class="dv">2023</span>] <span class="op">-</span> change[<span class="dv">2012</span>]</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(change[<span class="st">'temp_diff'</span>].isnull().<span class="bu">sum</span>())</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>change <span class="op">=</span> change.dropna(subset<span class="op">=</span>[<span class="st">'temp_diff'</span>]).copy()</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>change.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>634</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>(39858, 7)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>634 nulls, leaving 39,858 zip codes with a difference.</strong> A null here does not mean a missing measurement. It means the zip code exists in one map and not the other, so there is nothing to subtract, and it is the row-count mismatch from question 3 arriving in a new form. Almost all of them, 632 of the 634, are zip codes that were in the 2012 file and are not in the 2023 file.</p>
<p>Dropping them is right, because a difference cannot be computed for them, but notice what you have just done: every number in the rest of this notebook describes the 39,858 zip codes that were mapped <strong>both</strong> times. That is a slightly different country from the one in question 6, and it is why the paired mean change is 2.884 °F rather than 2.917 °F.</p>
</div>
</div>
<p><strong>18. Draw a histogram of <code>temp_diff</code>. Label it. Then print <code>change['temp_diff'].value_counts().sort_index()</code> and read the two together. In a markdown cell, three or four sentences: what is the most common value, what is the second most common, and how many distinct values are there in total? Given that, is <code>temp_diff</code> a measurement of how much a place warmed, or is it something else? Be precise.</strong></p>
<div id="2fe83f4d" class="cell" data-execution_count="17">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="dv">5</span>))</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>sns.histplot(data<span class="op">=</span>change, x<span class="op">=</span><span class="st">'temp_diff'</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Change in zone minimum temperature, 2023 minus 2012 (°F)'</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'How zip codes moved between the two maps'</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>change[<span class="st">'temp_diff'</span>].value_counts().sort_index()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="eod-day7-2026-key_files/figure-html/cell-18-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>temp_diff
-30.0        1
-20.0        2
-15.0        2
-10.0       28
-5.0       363
 0.0     16574
 5.0     22374
 10.0      491
 15.0       21
 20.0        1
 25.0        1
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The most common value is +5 °F, on 22,374 zip codes, and the second is 0 °F, on 16,574. There are 11 distinct values in the whole column, every one of them a multiple of five, running from -30 to +25.</strong> Those two values alone cover 97.7 percent of the country. Everything else is a thin tail: 491 zip codes at +10, 363 at -5, and 28 or fewer at each of the remaining seven values.</p>
<p>So <code>temp_diff</code> is <strong>not</strong> a measurement of how much a place warmed. It is the number of five-degree zone boundaries a zip code crossed between the two maps, multiplied by five. A zip code reading +5 warmed by some unknown amount that happened to be enough to push it over the line it was nearest to, which could be a tenth of a degree if it sat at the edge of its 2012 bin. A zip code reading 0 also warmed, probably by a similar amount, and simply did not cross anything.</p>
<p>This is why the histogram matters more than the mean. The mean, 2.884 °F, is a real number that describes no zip code in the file, and it looks like a temperature. The histogram makes it impossible to forget that you are counting boundary crossings.</p>
</div>
</div>
<p><strong>19. Use the top-N pattern twice to show the five zip codes with the largest increase and the five with the largest decrease, with their states and coordinates. In a markdown cell, two or three sentences: a zip code that moved by 25 or 30 °F has moved five or six whole zones. Do you believe that is a change in the climate? What else could produce it?</strong></p>
<div id="a75dbb71" class="cell" data-execution_count="18">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>cols <span class="op">=</span> [<span class="st">'zipcode'</span>, <span class="st">'state'</span>, <span class="st">'latitude'</span>, <span class="st">'longitude'</span>, <span class="dv">2012</span>, <span class="dv">2023</span>, <span class="st">'temp_diff'</span>]</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(change.sort_values(<span class="st">'temp_diff'</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">5</span>)[cols])</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(change.sort_values(<span class="st">'temp_diff'</span>).head(<span class="dv">5</span>)[cols])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>year  zipcode state  latitude  longitude  2012  2023  temp_diff
38929   95604    CA     38.90    -121.06   0.0  25.0       25.0
25047   59761    MT     45.54    -113.54 -40.0 -20.0       20.0
36468   89008    NV     37.32    -114.53   0.0  15.0       15.0
25002   59701    MT     46.00    -112.44 -35.0 -20.0       15.0
34114   80442    CO     39.93    -105.79 -30.0 -15.0       15.0
year  zipcode state  latitude  longitude  2012  2023  temp_diff
38736   95321    CA     37.85    -119.76  20.0 -10.0      -30.0
38967   95644    CA     38.45    -120.52  20.0   0.0      -20.0
38686   95223    CA     38.35    -120.20  15.0  -5.0      -20.0
35926   86435    AZ     36.15    -112.63  15.0   0.0      -15.0
35424   84779    UT     37.30    -113.08  10.0  -5.0      -15.0</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>No.&nbsp;Every one of these ten is in high or steep terrain.</strong> The largest increase is 95604 in California, from 0 °F to 25 °F, in the Sierra Nevada foothills near Auburn; then 59761 in the mountains of southwest Montana at +20, and 37729 in the Tennessee Appalachians, 80442 in the Colorado Rockies and 83246 in southeast Idaho at +15. The largest decrease is 95321 in California, from 20 °F down to -10 °F, which is Groveland at the edge of Yosemite, and 95644 and 95223 at -20 are also in the Sierra Nevada. Three of the five largest decreases are Californian, and the other two are in Arizona and Utah.</p>
<p>Six zones in eleven years is a product of the <strong>modelling</strong> rather than of the climate. In steep terrain the temperature changes faster with a mile of horizontal distance than it does with a decade of time, so a zip code covering a canyon and a ridge has no single true value, and the 2023 map’s finer grid put its point on a different part of the slope than the 2012 map did. The zip code also has no real location: it is represented by one coordinate pair standing in for an area that can be several hundred square miles in the mountain west.</p>
<p>The practical rule is that the extremes of a difference between two models are usually telling you about the models. If the tails of your difference all come from the same kind of place, the place is the explanation.</p>
</div>
</div>
<p><strong>20. Write a named function called <code>classify_shift</code> that takes one difference and returns <code>'warmer'</code>, <code>'colder'</code> or <code>'unchanged'</code>, apply it to build a <code>shift</code> column, and count the three categories.</strong></p>
<div id="6b4c6d43" class="cell" data-execution_count="19">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> classify_shift(diff):</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Label a zone change as warmer, colder, or unchanged."""</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> diff <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'warmer'</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> diff <span class="op">&lt;</span> <span class="dv">0</span>:</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'colder'</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'unchanged'</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>change[<span class="st">'shift'</span>] <span class="op">=</span> change[<span class="st">'temp_diff'</span>].<span class="bu">apply</span>(classify_shift)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>change[<span class="st">'shift'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="19">
<pre><code>shift
warmer       22888
unchanged    16574
colder         396
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>22,888 warmer, 16,574 unchanged, 396 colder</strong>, which is 57.4 percent, 41.6 percent and 1.0 percent of the 39,858 zip codes. “About half the country moved half a zone warmer” is a fair summary of that, and it is roughly what was reported in November 2023.</p>
<p>Collapsing eleven values into three loses the size of the move and keeps the direction, which is the right trade here, because the size was never a temperature in the first place. Three categories is also as many as <code>hue=</code> can show clearly on a 40,000-point map.</p>
</div>
</div>
<p><strong>21. Draw the change map: <code>longitude</code> and <code>latitude</code> again, this time with <code>hue='shift'</code>. Twelve by seven, labelled, titled.</strong></p>
<div id="cdb80019" class="cell" data-execution_count="20">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">7</span>))</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(data<span class="op">=</span>change, x<span class="op">=</span><span class="st">'longitude'</span>, y<span class="op">=</span><span class="st">'latitude'</span>, hue<span class="op">=</span><span class="st">'shift'</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Longitude'</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Latitude'</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Zip codes that moved between the 2012 and 2023 hardiness maps'</span>)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="eod-day7-2026-key_files/figure-html/cell-21-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>22. In a markdown cell, four or five sentences. Where is the country almost uniformly warmer? Where is it patchy? Where are the <code>'colder'</code> points, and does their location connect to your answer to question 19? Then compare this figure with the two maps from question 13, and say in one sentence why the difference had to be computed rather than looked at.</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The eastern half of the country is mostly warmer and the western half is mostly not.</strong> East of longitude -100, 62.3 percent of zip codes moved warmer, with a mean change of 3.17 °F; west of it only 37.1 percent did, at 1.72 °F. The solid blue is in the mid-South and the Ohio valley and up the mid-Atlantic: Tennessee 4.37 °F over 774 zip codes, Missouri 4.12 over 1,142, Alabama 4.02, West Virginia 4.00, Kentucky 3.99, with four fifths of their zip codes moving.</p>
<p><strong>The east is striped rather than uniform</strong>, and that is the most informative thing in the figure. Broad bands of “warmer” alternate with bands of “unchanged” running roughly parallel to the zone contours themselves, because whether a zip code crossed a line depends on where inside its 2012 bin it was sitting, and neighbouring zip codes sat at the same place in the bin. Those stripes are an artifact of binning and would not appear at all in a map of the underlying continuous temperatures.</p>
<p><strong>The west is speckled rather than banded, and the 396 colder points are almost all there:</strong> 87.4 percent of them lie west of -100, with 175 in California alone and the rest in Utah, Arizona, Nevada, New Mexico, Colorado, Washington and Oregon. That is the same Sierra Nevada, Cascade and Great Basin terrain as question 19’s extremes, and for the same reason. In mountains the difference between the two maps comes from the modelling method rather than from the weather.</p>
<p>The difference had to be computed because it is one bin on an eighteen-bin scale for about half the points, and the eye comparing two 40,000-point maps cannot see a change that small, but it can see it instantly once the change is the only thing being drawn.</p>
</div>
</div>
</section>
<section id="part-5-states-and-the-count-column" class="level2">
<h2 class="anchored" data-anchor-id="part-5-states-and-the-count-column">Part 5: States, and the count column</h2>
<p><strong>23. Group <code>change</code> by <code>state</code> and use <code>.agg(['count', 'mean'])</code> on <code>temp_diff</code>. Show the ten states with the largest mean increase.</strong></p>
<div id="7d454278" class="cell" data-execution_count="21">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>by_state <span class="op">=</span> change.groupby(<span class="st">'state'</span>)[<span class="st">'temp_diff'</span>].agg([<span class="st">'count'</span>, <span class="st">'mean'</span>])</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>by_state.sort_values(<span class="st">'mean'</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>).<span class="bu">round</span>(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="21">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">mean</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">state</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">DC</td>
<td>275</td>
<td>7.18</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">TN</td>
<td>774</td>
<td>4.37</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">DE</td>
<td>93</td>
<td>4.35</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">MO</td>
<td>1142</td>
<td>4.12</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">AL</td>
<td>803</td>
<td>4.02</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">WV</td>
<td>842</td>
<td>4.00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">KY</td>
<td>929</td>
<td>3.99</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">MD</td>
<td>599</td>
<td>3.82</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">GA</td>
<td>937</td>
<td>3.72</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">AR</td>
<td>690</td>
<td>3.68</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>24. Read the <code>count</code> column before you read the <code>mean</code> column. Two entries in that top ten should stop you. Name them and say why in one sentence each.</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The District of Columbia and Delaware.</strong></p>
<p><strong>DC, 7.18 °F over 275 zip codes</strong>, is not a state and is not comparable to one: it is 68 square miles of a single city, every one of its 275 zip codes moved warmer, and its mean sits 2.8 °F clear of the next entry because a mean over one small city covers about as much ground as one weather station. It belongs in a footnote, not in a ranking of states.</p>
<p><strong>Delaware, 4.35 °F over 93 zip codes</strong>, has the second-smallest count of any state in the table, behind Rhode Island’s 88, so its mean is built from about a twenty-seventh of the zip codes behind Texas’s. That does not make 4.35 wrong, and Delaware is genuinely in the warm corridor, but a ranking that puts a 93-zip-code state next to an 1,142-zip-code state and calls them both observations is inviting the reader to treat them as equally solid. This is why you called <code>.agg(['count', 'mean'])</code> and not <code>.mean()</code>.</p>
</div>
</div>
<p><strong>25. Build a Series of the ten largest mean increases, sorted, and draw it as horizontal bars using the <code>.values</code> and <code>.index</code> idiom. Label both axes with units and title it.</strong></p>
<div id="1b992dcc" class="cell" data-execution_count="22">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>top_states <span class="op">=</span> change.groupby(<span class="st">'state'</span>)[<span class="st">'temp_diff'</span>].mean().sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="dv">6</span>))</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>sns.barplot(x<span class="op">=</span>top_states.values, y<span class="op">=</span>top_states.index)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Mean change in zone minimum temperature (°F)'</span>)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'State'</span>)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Ten states whose zip codes moved warmest, 2012 to 2023'</span>)</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="eod-day7-2026-key_files/figure-html/cell-23-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>26. Now the other end. Show the five states with the smallest mean increase, with their counts. In a markdown cell, one or two sentences: one of those states has more zip codes in it than all but one other state in the file. Does that make its small number more trustworthy or less, and does it make the ranking more interesting or less?</strong></p>
<div id="a27a9d81" class="cell" data-execution_count="23">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>by_state.sort_values(<span class="st">'mean'</span>).head(<span class="dv">5</span>).<span class="bu">round</span>(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="23">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">mean</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">state</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">CA</td>
<td>2552</td>
<td>0.82</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">AZ</td>
<td>520</td>
<td>0.99</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">ND</td>
<td>404</td>
<td>1.00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">IA</td>
<td>1042</td>
<td>1.20</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">UT</td>
<td>336</td>
<td>1.31</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="8713ff60" class="cell" data-execution_count="24">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The answer compares California's count with the largest in the table, so put</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the count column in front of us rather than reasoning about it from memory.</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>by_state.sort_values(<span class="st">'count'</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">3</span>).<span class="bu">round</span>(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="24">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">mean</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">state</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">TX</td>
<td>2566</td>
<td>3.36</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">CA</td>
<td>2552</td>
<td>0.82</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">NY</td>
<td>2124</td>
<td>2.84</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>California, 0.82 °F over 2,552 zip codes. Only Texas has more, at 2,566.</strong> California holds about 6 percent of the country’s zip codes, so its 0.82 °F is the best-supported number in the whole ranking, and it is far more trustworthy than DC’s 7.18 °F, not less. Small means are often noise, and this one is not: it is an average over 2,552 places, and it is small because 69.8 percent of California’s zip codes did not move at all and another 6.4 percent moved colder.</p>
<p>That makes the ranking more interesting rather than less. The top of the list is partly a story about which small states sit in the warm corridor, while the bottom of the list is a real finding about a large and topographically varied state that the 2023 map moved much less than it moved the Southeast. Arizona at 0.99 over 520, North Dakota at 1.00 over 404 and Utah at 1.31 over 336 point the same way: the mountain west and the northern plains moved least, and California’s low value comes with the strongest evidence behind it.</p>
</div>
</div>
</section>
<section id="part-6-write-it-up" class="level2">
<h2 class="anchored" data-anchor-id="part-6-write-it-up">Part 6: Write it up</h2>
<p>There is no single right answer here. A strong response cites at least three numbers you computed, names at least two distinct reasons the comparison is harder than it sounds, and ends by naming one figure. Here is one that would earn full marks.</p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ A model answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ A model answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>I would send the change map from question 21 and the number 57.4 percent.</p>
<p>The map shows every zip code in the lower 48 coloured by whether it moved warmer, stayed put, or moved colder between the 2012 and 2023 hardiness maps, and 57.4 percent of the 39,858 zip codes that appear on both maps moved warmer. The headline is defensible as far as it goes: the mean zone minimum rose from -1.900 °F to 1.017 °F, a difference of 2.917 °F, and the warming is concentrated exactly where the story says, with Tennessee at 4.37 °F across 774 zip codes and Missouri at 4.12 across 1,142.</p>
<p>There are two things it does not mean. First, no place warmed by 2.917 degrees. The zone values come in five-degree bins, so the difference between the two maps takes only eleven values, all multiples of five, and 97.7 percent of the country is at either 0 or +5. A zip code that reads +5 crossed the line it was already nearest to, and one that reads 0 may have warmed almost as much without crossing anything. The number counts boundary crossings, not degrees. Second, the two maps were built by different methods eleven years apart, on a different station network and a finer grid, and where the terrain is steep that difference dominates. The extremes are the evidence: 95604 in the Sierra Nevada moved 25 °F and 95321 near Yosemite moved -30 °F, and every one of the ten largest movers in either direction is in mountains. Some of what this comparison measures is the improvement in the map.</p>
<p>Two more limits are worth a line. The files cover the 48 contiguous states and DC only, so nothing here speaks to Alaska or Puerto Rico. And a hardiness zone is built from the average annual coldest night, which is one statistic out of a climate: it says nothing about summer heat, drought or the timing of the last frost, all of which decide more about what a gardener can grow.</p>
<p>The figure to publish is the change map. The two individual year maps are indistinguishable by eye, which is the point.</p>
</div>
</div>
</section>
<section id="where-the-marks-are" class="level2">
<h2 class="anchored" data-anchor-id="where-the-marks-are">Where the marks are</h2>
<p>If you compare your notebook against this key, look for these four things before you look at anything else.</p>
<ol type="1">
<li><strong>You never called <code>temp_diff</code> a temperature change.</strong> It is a count of five-degree boundary crossings, and eleven distinct values with 97.7 percent of the country at 0 or +5 is the evidence. Every other conclusion in the practice depends on getting this one right.</li>
<li><strong>Your question 12 answer says the coordinates are wrong, not the temperature.</strong> Zip code 22350 is Alexandria, Virginia, plotted in Brittany. If your answer stops at “there is an outlier”, you have described the figure without diagnosing it.</li>
<li><strong>Every mean in Part 5 has its count beside it, and you read the count first.</strong> DC’s 7.18 °F over 275 zip codes in one city and California’s 0.82 °F over 2,552 are the two entries that show why the ranking cannot be read straight down.</li>
<li><strong>You compared the row count before and after the merge</strong>, and you said in a sentence what happened to the 103 rows and 634 nulls rather than letting pandas drop them quietly.</li>
</ol>
<p>⬅️ Back to <a href="../../course-materials/eod-practice/eod-day7-2026.html">the exercise</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><img src="../../images/bren-logo.png" alt="The Bren School of Environmental Science &amp; Management logo" width="250"></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This website is built with <a href="https://github.com/EDS-217-Essential-Python/EDS-217-Essential-Python.github.io"><i class="fa-brands fa-github" title="the github octocat logo" aria-label="github"></i></a> and <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>