<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Answer Key</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../course-materials/assets/css/exercises.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">EDS 217</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">🏠 home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-daily-materials" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">🗓️ daily materials</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-daily-materials">    
        <li>
    <a class="dropdown-item" href="../../course-materials/day1.html">
 <span class="dropdown-text">1️⃣ Day 1 (8/31)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day2.html">
 <span class="dropdown-text">2️⃣ Day 2 (9/1)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day3.html">
 <span class="dropdown-text">3️⃣ Day 3 (9/2)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day4.html">
 <span class="dropdown-text">4️⃣ Day 4 (9/3)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day5.html">
 <span class="dropdown-text">5️⃣ Day 5 (9/4)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day6.html">
 <span class="dropdown-text">6️⃣ Day 6 (9/8)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day7.html">
 <span class="dropdown-text">7️⃣ Day 7 (9/9)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day8.html">
 <span class="dropdown-text">8️⃣ Day 8 (9/10)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day9.html">
 <span class="dropdown-text">9️⃣ Day 9 (9/11)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-interactive-sessions" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">💻 interactive sessions</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-interactive-sessions">    
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1a_positron_notebooks.html">
 <span class="dropdown-text">Session 1a - ⚒️ Positron &amp; Jupyter Notebooks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1b_python_essentials.html">
 <span class="dropdown-text">Session 1b - 🐍 Python Essentials</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1c_data_science_workflow_1.html">
 <span class="dropdown-text">Session 1c - 🎬 The Python Data Science Workflow, Part 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1d_data_science_workflow_2.html">
 <span class="dropdown-text">Session 1d - 🎬 The Python Data Science Workflow, Part 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/2a_reading_data.html">
 <span class="dropdown-text">Session 2a - 🐼 Reading Data into pandas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/2b_exploring_data.html">
 <span class="dropdown-text">Session 2b - 🔎 Exploring a DataFrame</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/2d_lists_and_dicts.html">
 <span class="dropdown-text">Session 2d - 📝 Lists &amp; Dictionaries</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/3a_booleans_and_conditionals.html">
 <span class="dropdown-text">Session 3a - 📝 Booleans &amp; Conditionals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/3b_filtering_data.html">
 <span class="dropdown-text">Session 3b - 🔍 The Filter Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/3c_sorting_and_ranking.html">
 <span class="dropdown-text">Session 3c - 🥇 The Top-N Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4a_cleaning_data.html">
 <span class="dropdown-text">Session 4a - 🧼 Missing, Duplicated, Miscast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4b_functions.html">
 <span class="dropdown-text">Session 4b - ⚙️ Write It Once, Name It, Use It</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4c_transforming_data.html">
 <span class="dropdown-text">Session 4c - ➕ The Derived-Column Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/5a_grouping_data.html">
 <span class="dropdown-text">Session 5a - 🗂️ The Split-Apply-Combine Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/5b_aggregating_data.html">
 <span class="dropdown-text">Session 5b - 📊 Several Answers at Once</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/5d_loops_over_groups.html">
 <span class="dropdown-text">Session 5d - 🔁 When a Pattern Is Not Enough</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6a_joining_data.html">
 <span class="dropdown-text">Session 6a - 🔗 The Join Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6b_reshaping_data.html">
 <span class="dropdown-text">Session 6b - 🧩 Long and Wide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6c_dates.html">
 <span class="dropdown-text">Session 6c - 📆 A Date Is Not a Number</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7a_matplotlib.html">
 <span class="dropdown-text">Session 7a - 🖼️ The Anatomy of a Figure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7b_seaborn.html">
 <span class="dropdown-text">Session 7b - 🎨 Name the Columns, Not the Colours</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7d_project_kickoff.html">
 <span class="dropdown-text">Session 7d - 🚀 Project Kickoff</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-coding-colabs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">🙌 coding colabs</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-coding-colabs">    
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/2c_exploring_unfamiliar_data.html">
 <span class="dropdown-text">🙌 Session 2c - Five Claims About a Dataset You’ve Never Seen</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/3d_ranking_questions.html">
 <span class="dropdown-text">🙌 Session 3d - Which One, and How Do You Know?</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/4d_cleaning_messy_data.html">
 <span class="dropdown-text">🙌 Session 4d - From Field Sheet to DataFrame</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/5c_grouped_comparisons.html">
 <span class="dropdown-text">🙌 Session 5c - The Comparison You Made Yesterday, Properly</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/6d_two_table_exercise.html">
 <span class="dropdown-text">🙌 Session 6d - Two Records, Sixty-Six Years Apart</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/7c_penguins.html">
 <span class="dropdown-text">🙌 Session 7c - One Cloud of Points, Three Species</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../cheatsheets.html"> 
<span class="menu-text">👀 cheatsheets</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-resources" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">📚 resources</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-resources">    
        <li>
    <a class="dropdown-item" href="https://docs.python.org/3/" target="_blank">
 <span class="dropdown-text">📚 Python Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pandas.pydata.org/docs/" target="_blank">
 <span class="dropdown-text">📚 Pandas Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://numpy.org/doc/stable/" target="_blank">
 <span class="dropdown-text">📚 Numpy Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://matplotlib.org/stable/contents.html" target="_blank">
 <span class="dropdown-text">📚 Matplotlib Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://seaborn.pydata.org/" target="_blank">
 <span class="dropdown-text">📚 Seaborn Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://positron.posit.co/" target="_blank">
 <span class="dropdown-text">📚 Positron Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://docs.anaconda.com/" target="_blank">
 <span class="dropdown-text">📚 Anaconda Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://stackoverflow.com/" target="_blank">
 <span class="dropdown-text">📚 Stack Overflow</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://realpython.com/" target="_blank">
 <span class="dropdown-text">📚 Real Python</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://towardsdatascience.com/" target="_blank">
 <span class="dropdown-text">📚 Towards Data Science</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.datacamp.com/" target="_blank">
 <span class="dropdown-text">📚 DataCamp</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.kaggle.com/" target="_blank">
 <span class="dropdown-text">📚 Kaggle</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="http://pythontutor.com/" target="_blank">
 <span class="dropdown-text">🧰 Python Tutor</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pandastutor.com/vis.html#" target="_blank">
 <span class="dropdown-text">🧰 Pandas Tutor</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://wesmckinney.com/book/" target="_blank">
 <span class="dropdown-text">📙 Python for Data Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://jakevdp.github.io/PythonDataScienceHandbook/" target="_blank">
 <span class="dropdown-text">📙 Python for Data Science Handbook</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/jakevdp/PythonDataScienceHandbook" target="_blank">
 <span class="dropdown-text">📙 Python Data Science Handbook (GitHub)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://talkpython.fm/" target="_blank">
 <span class="dropdown-text">📻 Talk Python to Me</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/EDS-217-Essential-Python/EDS-217-Essential-Python.github.io" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-left">
      <h1 class="title">Answer Key</h1>
            <p class="subtitle lead">🔬 A Data Biography: Toolik Field Station</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta column-page-left">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#setup" id="toc-setup" class="nav-link active" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#part-1-vital-statistics" id="toc-part-1-vital-statistics" class="nav-link" data-scroll-target="#part-1-vital-statistics">Part 1: Vital statistics</a></li>
  <li><a href="#part-2-the-health-check" id="toc-part-2-the-health-check" class="nav-link" data-scroll-target="#part-2-the-health-check">Part 2: The health check</a></li>
  <li><a href="#part-3-what-varies-and-what-doesnt" id="toc-part-3-what-varies-and-what-doesnt" class="nav-link" data-scroll-target="#part-3-what-varies-and-what-doesnt">Part 3: What varies, and what doesn’t</a></li>
  <li><a href="#part-4-the-numbers" id="toc-part-4-the-numbers" class="nav-link" data-scroll-target="#part-4-the-numbers">Part 4: The numbers</a></li>
  <li><a href="#part-5-a-tidier-table" id="toc-part-5-a-tidier-table" class="nav-link" data-scroll-target="#part-5-a-tidier-table">Part 5: A tidier table</a></li>
  <li><a href="#part-6-write-the-biography" id="toc-part-6-write-the-biography" class="nav-link" data-scroll-target="#part-6-write-the-biography">Part 6: Write the biography</a>
  <ul class="collapse">
  <li><a href="#the-optional-loop" id="toc-the-optional-loop" class="nav-link" data-scroll-target="#the-optional-loop">The optional loop</a></li>
  </ul></li>
  <li><a href="#where-the-marks-are" id="toc-where-the-marks-are" class="nav-link" data-scroll-target="#where-the-marks-are">Where the marks are</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block column-page-left" id="quarto-document-content">





<div class="callout callout-style-default callout-important callout-titled" title="How to use this key">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How to use this key
</div>
</div>
<div class="callout-body-container callout-body">
<p>Work the exercise first, then come here. The code below is <strong>one</strong> correct answer, not the only one. If your code looks different but produces the same numbers, you were right!</p>
<p>The written answers matter more than the code. You can already tell whether your code ran, but you cannot tell on your own whether you read the result correctly, and reading the result correctly is what the green <strong>Answer</strong> boxes are for. Compare your markdown cells against them.</p>
<p>⬅️ Back to <a href="../../course-materials/eod-practice/eod-day2-2026.html">the exercise</a></p>
</div>
</div>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<div id="01b03f4c" class="cell" data-execution_count="1">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="st">'https://eds-217-essential-python.github.io/data/toolik_weather.csv'</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>toolik <span class="op">=</span> pd.read_csv(url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="part-1-vital-statistics" class="level2">
<h2 class="anchored" data-anchor-id="part-1-vital-statistics">Part 1: Vital statistics</h2>
<p><strong>1. How many rows and how many columns does the dataset have?</strong></p>
<div id="a1bf60fc" class="cell" data-execution_count="2">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>toolik.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="2">
<pre><code>(11171, 21)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>11,171 rows and 21 columns.</strong> One row per day. Hold on to the row count, because several of the later questions compare a column’s count against it: 11,171 is what “complete” looks like in this file, and any count below it is a gap somewhere.</p>
</div>
</div>
<p><strong>2. What are the column names? Get them as a Python list.</strong></p>
<div id="4db10afd" class="cell" data-execution_count="3">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>toolik.columns.tolist()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>['Year',
 'Month',
 'Date',
 'LTER_Site',
 'Station',
 'Daily_AirTemp_Mean_C',
 'Flag_Daily_AirTemp_Mean_C',
 'Daily_AirTemp_AbsMax_C',
 'Flag_Daily_AirTemp_AbsMax_C',
 'Daily_AirTemp_AbsMin_C',
 'Flag_Daily_AirTemp_AbsMin_C',
 'Daily_Precip_Total_mm',
 'Flag_Daily_Precip_Total_mm',
 'Daily_windsp_mean_msec',
 'FLAG_Daily_windsp_mean_msec',
 'Daily_Windspeed_AbsMax_m_s',
 'Daily_globalrad_total_jcm2',
 'FLAG_Daily_globalrad_total_mjm2',
 'Moss',
 'Soil20cm',
 'Comments']</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>Twenty-one names, and they fall into three groups. Three columns are time labels (<code>Year</code>, <code>Month</code>, <code>Date</code>), two more identify the site (<code>LTER_Site</code>, <code>Station</code>), and the remaining sixteen are nine measurements, six <code>Flag_</code> columns and <code>Comments</code>. Each flag column sits immediately after the measurement it annotates, which makes the list look at a glance like a neat alternation of measurement, flag, measurement, flag. Nine and six do not pair up, though, and three of the measurements have no flag column at all: <code>Daily_Windspeed_AbsMax_m_s</code>, <code>Moss</code> and <code>Soil20cm</code>.</p>
<p>Two details in the spelling are worth writing down while the list is on screen. First, the flag prefix is <code>Flag_</code> on four columns and <code>FLAG_</code> on two, and Python string matching is case sensitive, so any attempt to select “all the flag columns” by name has to account for both spellings. Second, <code>FLAG_Daily_globalrad_total_mjm2</code> sits directly after a measurement column named <code>Daily_globalrad_total_jcm2</code>, which is megajoules per square metre against joules per square centimetre. No column in this file is called <code>Daily_globalrad_total_mjm2</code>, and the radiation values run into the low thousands, which is an ordinary daily total in J/cm² and an impossible one in MJ/m², so the flag name is probably the one nobody updated. Noticing a mismatch like that from the column names alone is most of what today’s practice is for!</p>
</div>
</div>
<p><strong>3. What is the data type of each column?</strong></p>
<div id="65f04c48" class="cell" data-execution_count="4">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>toolik.dtypes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>Year                                 int64
Month                                int64
Date                                 int64
LTER_Site                           object
Station                             object
Daily_AirTemp_Mean_C               float64
Flag_Daily_AirTemp_Mean_C           object
Daily_AirTemp_AbsMax_C             float64
Flag_Daily_AirTemp_AbsMax_C         object
Daily_AirTemp_AbsMin_C             float64
Flag_Daily_AirTemp_AbsMin_C         object
Daily_Precip_Total_mm              float64
Flag_Daily_Precip_Total_mm          object
Daily_windsp_mean_msec             float64
FLAG_Daily_windsp_mean_msec         object
Daily_Windspeed_AbsMax_m_s         float64
Daily_globalrad_total_jcm2         float64
FLAG_Daily_globalrad_total_mjm2     object
Moss                               float64
Soil20cm                           float64
Comments                            object
dtype: object</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Three <code>int64</code> columns, nine <code>float64</code>, and nine <code>object</code>.</strong> The nine object columns are the site and station labels, the six flag columns and <code>Comments</code>, all of which hold text.</p>
<p>The column to look at twice is <strong><code>Date</code>, which pandas has stored as <code>int64</code>, not as a date.</strong> The file writes 1 June 1988 as <code>19880601</code>, which is a perfectly valid integer, so <code>read_csv</code> took it as a number. Storing a date that way means you can add 1 to it and get <code>19880602</code> by luck, then add 31 to <code>19880601</code> and get <code>19880632</code>, which is not a day at all. Nothing here is broken, but until we convert the column properly on Day 6, treat it as a label rather than as a date.</p>
</div>
</div>
<p><strong>4. Yesterday’s practice told you this record runs from June 1988 to December 2018. Do not take that on trust. Use <code>.min()</code> and <code>.max()</code> on the <code>Date</code> column to find the exact first and last day, and say which cell is your evidence.</strong></p>
<div id="decdf90e" class="cell" data-execution_count="5">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>toolik.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Month</th>
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th">Daily_AirTemp_Mean_C</th>
<th data-quarto-table-cell-role="th">Daily_AirTemp_AbsMax_C</th>
<th data-quarto-table-cell-role="th">Daily_AirTemp_AbsMin_C</th>
<th data-quarto-table-cell-role="th">Daily_Precip_Total_mm</th>
<th data-quarto-table-cell-role="th">Daily_windsp_mean_msec</th>
<th data-quarto-table-cell-role="th">Daily_Windspeed_AbsMax_m_s</th>
<th data-quarto-table-cell-role="th">Daily_globalrad_total_jcm2</th>
<th data-quarto-table-cell-role="th">Moss</th>
<th data-quarto-table-cell-role="th">Soil20cm</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>11171.000000</td>
<td>11171.000000</td>
<td>1.117100e+04</td>
<td>11171.000000</td>
<td>11001.000000</td>
<td>10967.000000</td>
<td>10751.000000</td>
<td>10345.000000</td>
<td>10325.000000</td>
<td>4118.000000</td>
<td>10333.000000</td>
<td>10351.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>2003.203384</td>
<td>6.570674</td>
<td>2.003271e+07</td>
<td>-8.196437</td>
<td>-3.447132</td>
<td>-13.295924</td>
<td>0.950953</td>
<td>2.995592</td>
<td>6.321288</td>
<td>1324.307188</td>
<td>-1.471402</td>
<td>-2.055647</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>8.831548</td>
<td>3.443637</td>
<td>8.830795e+04</td>
<td>14.831314</td>
<td>14.805298</td>
<td>14.727318</td>
<td>2.749060</td>
<td>1.553574</td>
<td>2.878432</td>
<td>866.670139</td>
<td>7.354649</td>
<td>5.555551</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>1988.000000</td>
<td>1.000000</td>
<td>1.988060e+07</td>
<td>-55.600000</td>
<td>-53.600000</td>
<td>-57.600000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>-2.000000</td>
<td>-24.000000</td>
<td>-21.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>1996.000000</td>
<td>4.000000</td>
<td>1.996012e+07</td>
<td>-19.700000</td>
<td>-14.200000</td>
<td>-25.600000</td>
<td>0.000000</td>
<td>2.000000</td>
<td>4.300000</td>
<td>591.000000</td>
<td>-7.000000</td>
<td>-6.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>2003.000000</td>
<td>7.000000</td>
<td>2.003092e+07</td>
<td>-7.100000</td>
<td>-2.900000</td>
<td>-12.300000</td>
<td>0.000000</td>
<td>2.800000</td>
<td>5.900000</td>
<td>1268.000000</td>
<td>-2.000000</td>
<td>-1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>2011.000000</td>
<td>10.000000</td>
<td>2.011051e+07</td>
<td>4.400000</td>
<td>8.900000</td>
<td>-0.100000</td>
<td>0.400000</td>
<td>3.600000</td>
<td>7.800000</td>
<td>2026.000000</td>
<td>4.000000</td>
<td>2.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>2018.000000</td>
<td>12.000000</td>
<td>2.018123e+07</td>
<td>20.700000</td>
<td>28.200000</td>
<td>14.900000</td>
<td>64.500000</td>
<td>12.500000</td>
<td>27.000000</td>
<td>3205.000000</td>
<td>19.000000</td>
<td>11.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="ade5f711" class="cell" data-execution_count="6">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>toolik[<span class="st">'Date'</span>].<span class="bu">min</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>np.int64(19880601)</code></pre>
</div>
</div>
<div id="f61bfa81" class="cell" data-execution_count="7">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>toolik[<span class="st">'Date'</span>].<span class="bu">max</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>np.int64(20181231)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The record runs from 1 June 1988 to 31 December 2018.</strong> The two cells above are the evidence: they print <code>19880601</code> and <code>20181231</code>.</p>
<p>Yesterday’s page was right, and checking it was still worth doing. “June 1988” and “1 June 1988” are different claims, and only one of them is in the file. Repeating what another page told you is not evidence, which is why today’s practice asks for a cell underneath every sentence you write.</p>
<p>Read the two numbers rather than the <code>min</code> and <code>max</code> rows of <code>.describe()</code>. <code>Date</code> is stored as an integer, so <code>.describe()</code> also reports a mean and a standard deviation for it, and neither of those means anything: the average of <code>19880601</code> and <code>20181231</code> is not a day.</p>
<p>Beginning on 1 June rather than 1 January leaves 1988 a partial year in this file, which question 10 takes up in more detail.</p>
<p>The <code>count</code> row of the <code>.describe()</code> you ran back in Part 1 is worth a second look while you are here, read across the columns rather than down one: <code>Daily_AirTemp_Mean_C</code> has all 11,171 values, but <code>Daily_globalrad_total_jcm2</code> has only 4,118.</p>
</div>
</div>
</section>
<section id="part-2-the-health-check" class="level2">
<h2 class="anchored" data-anchor-id="part-2-the-health-check">Part 2: The health check</h2>
<p><strong>5. Run <code>.info()</code>. How many columns have fewer non-null values than there are rows?</strong></p>
<div id="6715c4c3" class="cell" data-execution_count="8">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>toolik.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 11171 entries, 0 to 11170
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   Year                             11171 non-null  int64  
 1   Month                            11171 non-null  int64  
 2   Date                             11171 non-null  int64  
 3   LTER_Site                        11171 non-null  object 
 4   Station                          11171 non-null  object 
 5   Daily_AirTemp_Mean_C             11171 non-null  float64
 6   Flag_Daily_AirTemp_Mean_C        1310 non-null   object 
 7   Daily_AirTemp_AbsMax_C           11001 non-null  float64
 8   Flag_Daily_AirTemp_AbsMax_C      1020 non-null   object 
 9   Daily_AirTemp_AbsMin_C           10967 non-null  float64
 10  Flag_Daily_AirTemp_AbsMin_C      1236 non-null   object 
 11  Daily_Precip_Total_mm            10751 non-null  float64
 12  Flag_Daily_Precip_Total_mm       3169 non-null   object 
 13  Daily_windsp_mean_msec           10345 non-null  float64
 14  FLAG_Daily_windsp_mean_msec      1 non-null      object 
 15  Daily_Windspeed_AbsMax_m_s       10325 non-null  float64
 16  Daily_globalrad_total_jcm2       4118 non-null   float64
 17  FLAG_Daily_globalrad_total_mjm2  15 non-null     object 
 18  Moss                             10333 non-null  float64
 19  Soil20cm                         10351 non-null  float64
 20  Comments                         8924 non-null   object 
dtypes: float64(9), int64(3), object(9)
memory usage: 1.8+ MB</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>15 of the 21 columns.</strong> Only six columns are complete at 11,171 values: <code>Year</code>, <code>Month</code>, <code>Date</code>, <code>LTER_Site</code>, <code>Station</code> and <code>Daily_AirTemp_Mean_C</code>. Every other column, including every measurement other than the mean air temperature, has gaps somewhere.</p>
<p>One piece of good news: <code>Daily_AirTemp_Mean_C</code>, the column yesterday’s whole workflow was built on, is the only measurement in the file with no missing values at all.</p>
</div>
</div>
<p><strong>6. Use <code>.isnull().sum()</code> to count missing values per column. Which three columns are the emptiest?</strong></p>
<div id="f5202e33" class="cell" data-execution_count="9">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>toolik.isnull().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>Year                                   0
Month                                  0
Date                                   0
LTER_Site                              0
Station                                0
Daily_AirTemp_Mean_C                   0
Flag_Daily_AirTemp_Mean_C           9861
Daily_AirTemp_AbsMax_C               170
Flag_Daily_AirTemp_AbsMax_C        10151
Daily_AirTemp_AbsMin_C               204
Flag_Daily_AirTemp_AbsMin_C         9935
Daily_Precip_Total_mm                420
Flag_Daily_Precip_Total_mm          8002
Daily_windsp_mean_msec               826
FLAG_Daily_windsp_mean_msec        11170
Daily_Windspeed_AbsMax_m_s           846
Daily_globalrad_total_jcm2          7053
FLAG_Daily_globalrad_total_mjm2    11156
Moss                                 838
Soil20cm                             820
Comments                            2247
dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong><code>FLAG_Daily_windsp_mean_msec</code> (11,170 missing), <code>FLAG_Daily_globalrad_total_mjm2</code> (11,156) and <code>Flag_Daily_AirTemp_AbsMax_C</code> (10,151).</strong> The three emptiest columns are all flag columns, and so are the next three: every one of the six flag columns is missing more than 8,000 of its 11,171 values. The emptiest two columns that are not flags are <code>Daily_globalrad_total_jcm2</code>, with 7,053 missing, and <code>Comments</code>, with 2,247.</p>
<p>Finding those three takes a little reading, because <code>.isnull().sum()</code> prints the columns in the order they appear in the file rather than in order of emptiness, so the six flag columns are scattered down the list next to the measurements they annotate. Chaining <code>.sort_values(ascending=False)</code> on the end will rank them for you, which is worth doing on a wider file than this one.</p>
<p>However you get there, all six flag columns come out emptier than any measurement in the file, and the gap is a hint rather than an alarm: a flag column is only filled in on the days when something about the reading was worth writing down, so a nearly-empty one is a column doing exactly its job.</p>
</div>
</div>
<p><strong>7. One of the flag columns is empty in all but a very small number of rows. Which one, and how many values does it actually have?</strong></p>
<div id="15aad56f" class="cell" data-execution_count="10">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>toolik.notnull().<span class="bu">sum</span>().sort_values()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>FLAG_Daily_windsp_mean_msec            1
FLAG_Daily_globalrad_total_mjm2       15
Flag_Daily_AirTemp_AbsMax_C         1020
Flag_Daily_AirTemp_AbsMin_C         1236
Flag_Daily_AirTemp_Mean_C           1310
Flag_Daily_Precip_Total_mm          3169
Daily_globalrad_total_jcm2          4118
Comments                            8924
Daily_Windspeed_AbsMax_m_s         10325
Moss                               10333
Daily_windsp_mean_msec             10345
Soil20cm                           10351
Daily_Precip_Total_mm              10751
Daily_AirTemp_AbsMin_C             10967
Daily_AirTemp_AbsMax_C             11001
Daily_AirTemp_Mean_C               11171
Station                            11171
LTER_Site                          11171
Date                               11171
Month                              11171
Year                               11171
dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong><code>FLAG_Daily_windsp_mean_msec</code>, which is missing in 11,170 of 11,171 rows and therefore holds exactly one value.</strong> The next emptiest column, <code>FLAG_Daily_globalrad_total_mjm2</code>, holds 15.</p>
<p>A flag column is an annotation, not a measurement. It is there to mark the days on which something was unusual about the reading, and on an ordinary day there is nothing to say, so the cell is left empty. An almost-empty flag column means almost every wind speed reading was routine. A full flag column would be the alarming result!</p>
<p>The practical consequence is that emptiness alone is not a quality score. <code>Comments</code> is 20% empty and <code>Daily_globalrad_total_jcm2</code> is 63% empty, and those two nulls mean completely different things: one is a note nobody needed to write, the other is a measurement nobody made.</p>
</div>
</div>
</section>
<section id="part-3-what-varies-and-what-doesnt" class="level2">
<h2 class="anchored" data-anchor-id="part-3-what-varies-and-what-doesnt">Part 3: What varies, and what doesn’t</h2>
<p><strong>8. Use <code>.value_counts()</code> on <code>LTER_Site</code> and on <code>Station</code>. What does each column tell you?</strong></p>
<div id="30cbaf56" class="cell" data-execution_count="11">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>toolik[<span class="st">'LTER_Site'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>LTER_Site
ARC    11171
Name: count, dtype: int64</code></pre>
</div>
</div>
<div id="5c46ff59" class="cell" data-execution_count="12">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>toolik[<span class="st">'Station'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>Station
TLKMAIN    11171
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Neither column varies, so neither one can tell you anything about the differences between rows.</strong> <code>LTER_Site</code> is <code>ARC</code> in all 11,171 rows and <code>Station</code> is <code>TLKMAIN</code> in all 11,171 rows. A column with one distinct value cannot distinguish one row from another, so it can never explain anything, and grouping by it would return a single group.</p>
<p>They still have a use, though. They record <strong>provenance</strong>: every row came from the main meteorological station at the Arctic LTER site, so this whole file is one instrument at one place. Provenance is worth a sentence in your biography, because it settles two questions at once. Nothing here needs to be averaged across stations, and these data describe one point on the North Slope rather than the Arctic in general.</p>
</div>
</div>
<p><strong>9. Use <code>.value_counts()</code> on <code>Flag_Daily_AirTemp_Mean_C</code>. What values appear, and what do you think they mean?</strong></p>
<div id="982387fe" class="cell" data-execution_count="13">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>toolik[<span class="st">'Flag_Daily_AirTemp_Mean_C'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>Flag_Daily_AirTemp_Mean_C
E    1310
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>One value appears, <code>E</code>, on 1,310 days.</strong> In the Arctic LTER flag convention, <code>E</code> marks a value that was <strong>estimated</strong> rather than measured directly, usually filled in from a nearby sensor by regression when the main logger failed. The <code>Comments</code> column says so in words on those rows, with entries such as “Air temp 1 &amp; 5 meter estimated from regression”.</p>
<p>Question 5 found <code>Daily_AirTemp_Mean_C</code> to be the one measurement with no missing values, which made it look like the most trustworthy column in the file. Put the two results together and the picture changes: 1,310 of those 11,171 values, or 11.7%, are flagged as estimated. The column is complete because somebody filled the gaps, not because the instrument never stopped. Counting nulls would never have shown you this, and it is worth knowing before you compute a temperature trend from the column.</p>
<p>Note also that <code>.value_counts()</code> drops nulls by default, which is why the 9,861 unflagged days do not appear. Use <code>.value_counts(dropna=False)</code> when you want to see them.</p>
</div>
</div>
<p><strong>10. Use <code>.value_counts()</code> on the <code>Year</code> column and look at both ends of the result, with <code>.head()</code> and then with <code>.tail()</code>. Do all years have the same number of observations? What would explain a year with fewer?</strong></p>
<div id="97d22ae0" class="cell" data-execution_count="14">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>toolik[<span class="st">'Year'</span>].value_counts().head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>Year
1996    366
2012    366
2008    366
2000    366
2004    366
Name: count, dtype: int64</code></pre>
</div>
</div>
<div id="6480bd52" class="cell" data-execution_count="15">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>toolik[<span class="st">'Year'</span>].value_counts().tail()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>Year
1994    365
1993    365
1991    365
1990    365
1988    214
Name: count, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>No, and the two ends of the result show you two different things.</strong> <code>.value_counts()</code> sorts by count from largest to smallest, so <code>.head()</code> returns five years with 366 rows each. Seven years in this file have 366 rows, because seven of them are leap years, and every other full year has 365. Five of those seven tie for the top of the list, so which five you see, and in what order, depends on how pandas breaks the tie. Your list may not match the one printed above, which is fine and expected! <code>.tail()</code> returns the other end of the same list, and the short year sits down there: <strong>1988 has 214 rows.</strong></p>
<p>The question asks for both ends because a list sorted by count puts each year wherever its count happens to fall, so a year with fewer observations than its neighbours sorts to the bottom and is invisible from the top. Whenever you use <code>.value_counts()</code> to check whether groups are the same size, read both ends of it.</p>
<p>The 214 days are the start of the record rather than a gap in the middle of a year. Counting back 214 days from 31 December 1988 reaches 1 June, which agrees with the <code>Date</code> minimum of <code>19880601</code> you saw in question 4. Toolik began recording in mid-year.</p>
<p>The consequence is a real one. Any per-year summary you compute for 1988 covers June to December only, so it leaves out the coldest five months and will not be comparable with any other year in the file. Whenever a group has fewer rows than its neighbours, find out which rows are missing before you compare the groups.</p>
</div>
</div>
</section>
<section id="part-4-the-numbers" class="level2">
<h2 class="anchored" data-anchor-id="part-4-the-numbers">Part 4: The numbers</h2>
<p><strong>11. What is the mean daily air temperature across the whole record? The minimum? The maximum?</strong></p>
<div id="89171a2f" class="cell" data-execution_count="16">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>toolik[<span class="st">'Daily_AirTemp_Mean_C'</span>].describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>count    11171.000000
mean        -8.196437
std         14.831314
min        -55.600000
25%        -19.700000
50%         -7.100000
75%          4.400000
max         20.700000
Name: Daily_AirTemp_Mean_C, dtype: float64</code></pre>
</div>
</div>
<p><strong>12. Are the mean, the minimum and the maximum plausible for a site above the Arctic Circle? Say why or why not.</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Mean -8.20 °C, minimum -55.60 °C, maximum 20.70 °C, over all 11,171 days</strong>, with a standard deviation of 14.83 °C and a median of -7.10 °C.</p>
<p>All three numbers are plausible for the North Slope of Alaska. A mean well below freezing is what makes this a permafrost site. The extremes are extremes of a <em>daily mean</em>, not of an instantaneous reading, so -55.6 °C is a day that averaged -55.6 °C, which is a good deal more remarkable than a brief cold spike. The quartiles are the useful check on plausibility: 25% of days average below -19.7 °C and 75% are below 4.4 °C, so this is a place that spends most of the year frozen and thaws briefly.</p>
<p>One caution about the mean. It is the average of every day in the file, and the file starts on 1 June 1988, so the first year contributes a summer and no winter. The effect is small here, -8.26 °C if you exclude 1988 entirely against -8.20 °C with it, but the direction is predictable: an unbalanced record pulls the average toward whatever season is over-represented.</p>
</div>
</div>
<p><strong>13. Pick one other numeric column and report its range. Does anything about it look wrong?</strong></p>
<div id="8077d978" class="cell" data-execution_count="17">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>toolik[[<span class="st">'Daily_AirTemp_Mean_C'</span>, <span class="st">'Daily_Precip_Total_mm'</span>, <span class="st">'Daily_windsp_mean_msec'</span>]].describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="17">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Daily_AirTemp_Mean_C</th>
<th data-quarto-table-cell-role="th">Daily_Precip_Total_mm</th>
<th data-quarto-table-cell-role="th">Daily_windsp_mean_msec</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>11171.000000</td>
<td>10751.000000</td>
<td>10345.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>-8.196437</td>
<td>0.950953</td>
<td>2.995592</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>14.831314</td>
<td>2.749060</td>
<td>1.553574</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>-55.600000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>-19.700000</td>
<td>0.000000</td>
<td>2.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>-7.100000</td>
<td>0.000000</td>
<td>2.800000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>4.400000</td>
<td>0.400000</td>
<td>3.600000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>20.700000</td>
<td>64.500000</td>
<td>12.500000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong><code>Daily_Precip_Total_mm</code> runs from 0 to 64.5 mm, with a mean of 0.95 mm.</strong> Nothing in that range is physically impossible. The <code>count</code> is the problem: <strong>10,751</strong>, which is 420 days short of the 11,171 in the file, and those absences are not spread evenly. They fall in six years, mostly in 1995 (183 missing days), 1994 (92), 1990 (88) and 2004 (52), with the last five days split between 1989 and 1993. So 1995 reports precipitation on 182 days out of 365, and any annual rainfall total for that year would be roughly half a year of rain presented as a whole one.</p>
<p>The trap is that a missing day and a dry day look the same once they are summed. The median precipitation is 0.0 mm, because 7,278 of the recorded days had no rain at all, so a missing day quietly resembles the most common real value. Reporting the mean of 0.95 mm is safe, because pandas divides by the days it actually has, but any <code>.sum()</code> over this column will undercount without warning you.</p>
<p><code>Daily_windsp_mean_msec</code> shows the same pattern more mildly: 0 to 12.5 m/s over 10,345 days, so 826 days have no wind reading. If you looked at <code>Daily_globalrad_total_jcm2</code> instead, its minimum of -2.0 J/cm² is genuinely impossible, because a day cannot receive negative sunlight, and that single value is a good example of an error that only a physical sanity check will catch.</p>
</div>
</div>
</section>
<section id="part-5-a-tidier-table" class="level2">
<h2 class="anchored" data-anchor-id="part-5-a-tidier-table">Part 5: A tidier table</h2>
<p><strong>14. Build a list of the five columns you’d keep if you had to hand this dataset to a colleague who only cared about temperature. Use it to make a smaller DataFrame.</strong></p>
<div id="c013e7e2" class="cell" data-execution_count="18">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>temp_columns <span class="op">=</span> [<span class="st">'Year'</span>, <span class="st">'Month'</span>, <span class="st">'Date'</span>, <span class="st">'Daily_AirTemp_Mean_C'</span>, <span class="st">'Daily_AirTemp_AbsMin_C'</span>]</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>toolik_temps <span class="op">=</span> toolik[temp_columns]</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>toolik_temps.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="18">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Year</th>
<th data-quarto-table-cell-role="th">Month</th>
<th data-quarto-table-cell-role="th">Date</th>
<th data-quarto-table-cell-role="th">Daily_AirTemp_Mean_C</th>
<th data-quarto-table-cell-role="th">Daily_AirTemp_AbsMin_C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1988</td>
<td>6</td>
<td>19880601</td>
<td>8.4</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1988</td>
<td>6</td>
<td>19880602</td>
<td>6.0</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>1988</td>
<td>6</td>
<td>19880603</td>
<td>5.8</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>1988</td>
<td>6</td>
<td>19880604</td>
<td>1.8</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>1988</td>
<td>6</td>
<td>19880605</td>
<td>6.8</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>15. Build a dictionary that renames at least two of those columns to something shorter and clearer. Apply it with <code>.rename(columns=...)</code> and confirm the new names.</strong></p>
<div id="43921abb" class="cell" data-execution_count="19">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>shorter <span class="op">=</span> {</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Daily_AirTemp_Mean_C'</span>: <span class="st">'temp_mean_c'</span>,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Daily_AirTemp_AbsMin_C'</span>: <span class="st">'temp_min_c'</span>,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>toolik_temps <span class="op">=</span> toolik_temps.rename(columns<span class="op">=</span>shorter)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>toolik_temps.columns.tolist()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="19">
<pre><code>['Year', 'Month', 'Date', 'temp_mean_c', 'temp_min_c']</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>Two Day 2 collections doing two different jobs. The <strong>list</strong> is an ordered selection: passing it to <code>toolik[...]</code> returns the columns in the order you wrote them, so the list decides both what is kept and how it is arranged. The <strong>dictionary</strong> is a lookup from old name to new name, and because it is a mapping rather than a sequence, its order is irrelevant and it may name only some of the columns. Anything not mentioned as a key keeps its current name.</p>
<p>Two things to check in your own version. First, keeping the time columns matters: a table of temperatures with no <code>Year</code>, <code>Month</code> or <code>Date</code> cannot be plotted against time, so the useful five columns are three labels and two measurements. Second, <code>.rename()</code> returns a <strong>new</strong> DataFrame and does not alter the original, which is why the code reassigns <code>toolik_temps</code>. Confirm this by running <code>toolik.columns.tolist()</code> again: the full table still has <code>Daily_AirTemp_Mean_C</code> under its original name. Keeping units in the new names, as <code>temp_mean_c</code> does, is worth the two extra characters.</p>
</div>
</div>
</section>
<section id="part-6-write-the-biography" class="level2">
<h2 class="anchored" data-anchor-id="part-6-write-the-biography">Part 6: Write the biography</h2>
<p>There is no single right answer here. A strong biography states a number for every claim, names at least one problem that the file does not announce, and gives a fitness-for-purpose verdict with a condition attached rather than an unqualified yes. Here is one that would earn full marks.</p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ A model answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ A model answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>This file holds daily weather from the main meteorological station (<code>TLKMAIN</code>) at Toolik Field Station, part of the Arctic LTER site (<code>ARC</code>) on the North Slope of Alaska. Both identifier columns hold a single value throughout, so every observation comes from one instrument cluster at one place. The 21 columns cover nine measurements: air temperature (daily mean, absolute maximum, absolute minimum), precipitation, mean and maximum wind speed, global radiation, and moss and 20 cm soil temperature. Six of the nine have a flag column.</p>
<p>Coverage is 11,171 daily rows from 1 June 1988 to 31 December 2018, with every calendar day present. 1988 holds only 214 rows because the record starts in June, so it is a partial year, not a lost one.</p>
<p>Fifteen of the 21 columns have missing values. Daily mean air temperature, complete at 11,171 values, is the column I would trust most. I would not trust global radiation, which has 4,118 values and includes an impossible -2.0 J/cm², or annual precipitation totals, because 420 days are absent and 183 of them fall in 1995 alone.</p>
<p>Two cautions. First, <code>Date</code> is stored as the integer 19880601, not as a date, so it cannot be sorted or differenced as a date until converted. Second, the complete temperature column is not fully measured: 1,310 days, 11.7% of the record, have an <code>E</code> flag meaning the value was estimated from a nearby sensor.</p>
<p>Could this describe change in Arctic summer temperatures since 1988? Yes, with one check first. All 31 years have complete June to August coverage and no missing means, but 85 of the 92 summer days in 1988 are flagged estimated, and no summer day after 2006 has a flag. Because 1988 anchors any trend, I would confirm the result holds with those days excluded.</p>
</div>
</div>
<section id="the-optional-loop" class="level3">
<h3 class="anchored" data-anchor-id="the-optional-loop">The optional loop</h3>
<p>The Field Note offered a loop as a shortcut for checking several columns at once. Running it on the two columns in the example prints the missing-value count for each, which is the same pair of numbers you would get from two separate calls:</p>
<div id="4d468a69" class="cell" data-execution_count="20">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> column_name <span class="kw">in</span> [<span class="st">'Daily_AirTemp_Mean_C'</span>, <span class="st">'Daily_Precip_Total_mm'</span>]:</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(column_name, toolik[column_name].isnull().<span class="bu">sum</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Daily_AirTemp_Mean_C 0
Daily_Precip_Total_mm 420</code></pre>
</div>
</div>
<p>Anyone who worked one column at a time has lost nothing. The loop saves typing, not insight.</p>
</section>
</section>
<section id="where-the-marks-are" class="level2">
<h2 class="anchored" data-anchor-id="where-the-marks-are">Where the marks are</h2>
<p>If you compare your notebook against this key, look for these four things before you look at anything else.</p>
<ol type="1">
<li><strong>Every factual claim in your biography has a code cell above it that produced it.</strong> A sentence such as “the record covers about thirty years” is the failure mode this exercise is built to catch. “1 June 1988 to 31 December 2018, 11,171 daily rows” is the pass.</li>
<li><strong>You found 1988 and explained it.</strong> Reporting that 1988 has 214 rows is half the answer. The mark is for saying why: the record begins on 1 June 1988, so 1988 is a partial year rather than a year with days missing from it, and no per-year figure for 1988 is comparable with any other year in the file.</li>
<li><strong>You read the flag columns as part of the file’s design rather than as errors,</strong> and you connected them back to <code>Daily_AirTemp_Mean_C</code>. The column with no missing values contains 1,310 estimated ones, and a biography that reports it as complete without mentioning the flags sends its reader off with the wrong idea of how solid the temperature record is.</li>
<li><strong>Your answers say what a number means rather than what it is.</strong> “420 values are missing from precipitation” restates the output. “420 missing days, 183 of them in 1995, so an annual total for that year covers half a year of rain” reads it.</li>
</ol>
<p>⬅️ Back to <a href="../../course-materials/eod-practice/eod-day2-2026.html">the exercise</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><img src="../../images/bren-logo.png" alt="The Bren School of Environmental Science &amp; Management logo" width="250"></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This website is built with <a href="https://github.com/EDS-217-Essential-Python/EDS-217-Essential-Python.github.io"><i class="fa-brands fa-github" title="the github octocat logo" aria-label="github"></i></a> and <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>