<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Answer Key</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../course-materials/assets/css/exercises.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">EDS 217</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">🏠 home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-daily-materials" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">🗓️ daily materials</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-daily-materials">    
        <li>
    <a class="dropdown-item" href="../../course-materials/day1.html">
 <span class="dropdown-text">1️⃣ Day 1 (8/31)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day2.html">
 <span class="dropdown-text">2️⃣ Day 2 (9/1)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day3.html">
 <span class="dropdown-text">3️⃣ Day 3 (9/2)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day4.html">
 <span class="dropdown-text">4️⃣ Day 4 (9/3)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day5.html">
 <span class="dropdown-text">5️⃣ Day 5 (9/4)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day6.html">
 <span class="dropdown-text">6️⃣ Day 6 (9/8)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day7.html">
 <span class="dropdown-text">7️⃣ Day 7 (9/9)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day8.html">
 <span class="dropdown-text">8️⃣ Day 8 (9/10)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/day9.html">
 <span class="dropdown-text">9️⃣ Day 9 (9/11)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-interactive-sessions" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">💻 interactive sessions</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-interactive-sessions">    
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1a_positron_notebooks.html">
 <span class="dropdown-text">Session 1a - ⚒️ Positron &amp; Jupyter Notebooks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1b_python_essentials.html">
 <span class="dropdown-text">Session 1b - 🐍 Python Essentials</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1c_data_science_workflow_1.html">
 <span class="dropdown-text">Session 1c - 🎬 The Python Data Science Workflow, Part 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/1d_data_science_workflow_2.html">
 <span class="dropdown-text">Session 1d - 🎬 The Python Data Science Workflow, Part 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/2a_reading_data.html">
 <span class="dropdown-text">Session 2a - 🐼 Reading Data into pandas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/2b_exploring_data.html">
 <span class="dropdown-text">Session 2b - 🔎 Exploring a DataFrame</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/2d_lists_and_dicts.html">
 <span class="dropdown-text">Session 2d - 📝 Lists &amp; Dictionaries</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/3a_booleans_and_conditionals.html">
 <span class="dropdown-text">Session 3a - 📝 Booleans &amp; Conditionals</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/3b_filtering_data.html">
 <span class="dropdown-text">Session 3b - 🔍 The Filter Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/3c_sorting_and_ranking.html">
 <span class="dropdown-text">Session 3c - 🥇 The Top-N Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4a_cleaning_data.html">
 <span class="dropdown-text">Session 4a - 🧼 Missing, Duplicated, Miscast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4b_functions.html">
 <span class="dropdown-text">Session 4b - ⚙️ Write It Once, Name It, Use It</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/4c_transforming_data.html">
 <span class="dropdown-text">Session 4c - ➕ The Derived-Column Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/5a_grouping_data.html">
 <span class="dropdown-text">Session 5a - 🗂️ The Split-Apply-Combine Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/5b_aggregating_data.html">
 <span class="dropdown-text">Session 5b - 📊 Several Answers at Once</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/5d_loops_over_groups.html">
 <span class="dropdown-text">Session 5d - 🔁 When a Pattern Is Not Enough</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6a_joining_data.html">
 <span class="dropdown-text">Session 6a - 🔗 The Join Pattern</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6b_reshaping_data.html">
 <span class="dropdown-text">Session 6b - 🧩 Long and Wide</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/6c_dates.html">
 <span class="dropdown-text">Session 6c - 📆 A Date Is Not a Number</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/live-coding/70_building_a_table.html">
 <span class="dropdown-text">Session 7.0 - 🧱 Building a Table Row by Row</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7a_matplotlib.html">
 <span class="dropdown-text">Session 7a - 🖼️ The Anatomy of a Figure</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7b_seaborn.html">
 <span class="dropdown-text">Session 7b - 🎨 Name the Columns, Not the Colours</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/interactive-sessions/7d_project_kickoff.html">
 <span class="dropdown-text">Session 7d - 🚀 Project Kickoff</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-coding-colabs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">🙌 coding colabs</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-coding-colabs">    
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/2c_exploring_unfamiliar_data.html">
 <span class="dropdown-text">🙌 Session 2c - Five Claims About a Dataset You’ve Never Seen</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/3d_ranking_questions.html">
 <span class="dropdown-text">🙌 Session 3d - Which One, and How Do You Know?</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/4d_cleaning_messy_data.html">
 <span class="dropdown-text">🙌 Session 4d - From Field Sheet to DataFrame</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/5c_grouped_comparisons.html">
 <span class="dropdown-text">🙌 Session 5c - The Comparison You Made Yesterday, Properly</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/6d_two_table_exercise.html">
 <span class="dropdown-text">🙌 Session 6d - Two Records, Sixty-Six Years Apart</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../course-materials/coding-colabs/7c_penguins.html">
 <span class="dropdown-text">🙌 Session 7c - One Cloud of Points, Three Species</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../cheatsheets.html"> 
<span class="menu-text">👀 cheatsheets</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-resources" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">📚 resources</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-resources">    
        <li>
    <a class="dropdown-item" href="https://docs.python.org/3/" target="_blank">
 <span class="dropdown-text">📚 Python Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pandas.pydata.org/docs/" target="_blank">
 <span class="dropdown-text">📚 Pandas Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://numpy.org/doc/stable/" target="_blank">
 <span class="dropdown-text">📚 Numpy Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://matplotlib.org/stable/contents.html" target="_blank">
 <span class="dropdown-text">📚 Matplotlib Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://seaborn.pydata.org/" target="_blank">
 <span class="dropdown-text">📚 Seaborn Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://positron.posit.co/" target="_blank">
 <span class="dropdown-text">📚 Positron Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://docs.anaconda.com/" target="_blank">
 <span class="dropdown-text">📚 Anaconda Documentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://stackoverflow.com/" target="_blank">
 <span class="dropdown-text">📚 Stack Overflow</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://realpython.com/" target="_blank">
 <span class="dropdown-text">📚 Real Python</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://towardsdatascience.com/" target="_blank">
 <span class="dropdown-text">📚 Towards Data Science</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.datacamp.com/" target="_blank">
 <span class="dropdown-text">📚 DataCamp</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://www.kaggle.com/" target="_blank">
 <span class="dropdown-text">📚 Kaggle</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="http://pythontutor.com/" target="_blank">
 <span class="dropdown-text">🧰 Python Tutor</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://pandastutor.com/vis.html#" target="_blank">
 <span class="dropdown-text">🧰 Pandas Tutor</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://wesmckinney.com/book/" target="_blank">
 <span class="dropdown-text">📙 Python for Data Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://jakevdp.github.io/PythonDataScienceHandbook/" target="_blank">
 <span class="dropdown-text">📙 Python for Data Science Handbook</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/jakevdp/PythonDataScienceHandbook" target="_blank">
 <span class="dropdown-text">📙 Python Data Science Handbook (GitHub)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://talkpython.fm/" target="_blank">
 <span class="dropdown-text">📻 Talk Python to Me</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/EDS-217-Essential-Python/EDS-217-Essential-Python.github.io" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-left">
      <h1 class="title">Answer Key</h1>
            <p class="subtitle lead">🌬️ Three Stations, One Atmosphere</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta column-page-left">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#setup" id="toc-setup" class="nav-link active" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#part-1-what-is-in-each-pile" id="toc-part-1-what-is-in-each-pile" class="nav-link" data-scroll-target="#part-1-what-is-in-each-pile">Part 1: What is in each pile</a></li>
  <li><a href="#part-2-compare-the-stations" id="toc-part-2-compare-the-stations" class="nav-link" data-scroll-target="#part-2-compare-the-stations">Part 2: Compare the stations</a></li>
  <li><a href="#part-3-the-data-still-has-problems" id="toc-part-3-the-data-still-has-problems" class="nav-link" data-scroll-target="#part-3-the-data-still-has-problems">Part 3: The data still has problems</a></li>
  <li><a href="#part-4-the-question-the-day-was-for" id="toc-part-4-the-question-the-day-was-for" class="nav-link" data-scroll-target="#part-4-the-question-the-day-was-for">Part 4: The question the day was for</a></li>
  <li><a href="#part-5-write-it-up" id="toc-part-5-write-it-up" class="nav-link" data-scroll-target="#part-5-write-it-up">Part 5: Write it up</a></li>
  <li><a href="#where-the-marks-are" id="toc-where-the-marks-are" class="nav-link" data-scroll-target="#where-the-marks-are">Where the marks are</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block column-page-left" id="quarto-document-content">





<div class="callout callout-style-default callout-important callout-titled" title="How to use this key">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
How to use this key
</div>
</div>
<div class="callout-body-container callout-body">
<p>Work the exercise first, then come here. The code below is <strong>one</strong> correct answer, not the only one. If your code looks different but produces the same numbers, you were right.</p>
<p>The written answers matter more than the code. You can already tell whether your code ran. What you cannot check on your own is whether you read the result correctly, and that is what the green <strong>Answer</strong> boxes are for. Compare your markdown cells against them.</p>
<p>⬅️ Back to <a href="../../course-materials/eod-practice/eod-day5-2026.html">the exercise</a></p>
</div>
</div>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<div id="24c82358" class="cell" data-execution_count="1">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>base <span class="op">=</span> <span class="st">'https://eds-217-essential-python.github.io/data/'</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>goleta <span class="op">=</span> pd.read_csv(base <span class="op">+</span> <span class="st">'openaq_goleta_measurments.csv'</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>santa_barbara <span class="op">=</span> pd.read_csv(base <span class="op">+</span> <span class="st">'openaq_santa_barbara_measurments.csv'</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>cnsi <span class="op">=</span> pd.read_csv(base <span class="op">+</span> <span class="st">'openaq_CNSI_measurments.csv'</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>goleta[<span class="st">'site'</span>] <span class="op">=</span> <span class="st">'Goleta'</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>santa_barbara[<span class="st">'site'</span>] <span class="op">=</span> <span class="st">'Santa Barbara'</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>cnsi[<span class="st">'site'</span>] <span class="op">=</span> <span class="st">'CNSI'</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>aq <span class="op">=</span> pd.concat([goleta, santa_barbara, cnsi], ignore_index<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>aq[<span class="st">'hour'</span>] <span class="op">=</span> aq[<span class="st">'datetimeLocal'</span>].<span class="bu">str</span>[<span class="dv">11</span>:<span class="dv">13</span>]</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>aq.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>(4942, 17)</code></pre>
</div>
</div>
</section>
<section id="part-1-what-is-in-each-pile" class="level2">
<h2 class="anchored" data-anchor-id="part-1-what-is-in-each-pile">Part 1: What is in each pile</h2>
<p><strong>1. How many readings came from each site?</strong></p>
<div id="47860cba" class="cell" data-execution_count="2">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>aq.groupby(<span class="st">'site'</span>)[<span class="st">'value'</span>].count()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="2">
<pre><code>site
CNSI              714
Goleta           1962
Santa Barbara    2266
Name: value, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Santa Barbara 2,266, Goleta 1,962 and CNSI 714</strong>, which add to the 4,942 rows in the stacked table. The piles are very uneven, and the reason is not that one station ran for fewer days. All three cover the same month. Santa Barbara has more than three times as many readings as CNSI because it measures three things and CNSI measures one, which is what question 2 makes visible.</p>
</div>
</div>
<p><strong>2. How many distinct parameters does each site measure? Use the dictionary form of <code>.agg()</code> to report the reading count and the parameter count side by side.</strong></p>
<div id="c977e18b" class="cell" data-execution_count="3">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>aq.groupby(<span class="st">'site'</span>).agg({<span class="st">'value'</span>: <span class="st">'count'</span>, <span class="st">'parameter'</span>: <span class="st">'nunique'</span>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">value</th>
<th data-quarto-table-cell-role="th">parameter</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">site</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">CNSI</td>
<td>714</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Goleta</td>
<td>1962</td>
<td>3</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Santa Barbara</td>
<td>2266</td>
<td>3</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Goleta and Santa Barbara measure 3 parameters each, CNSI measures 1.</strong> Notice what the dictionary form gives you: one call, two different summaries, applied to two different columns. <code>'count'</code> on <code>value</code> counts readings and <code>'nunique'</code> on <code>parameter</code> counts distinct labels, so the 714 and the 1 in the CNSI row are answering two unrelated questions about the same group.</p>
</div>
</div>
<p><strong>3. One of the three stations is not like the others. Name it, say what it does not do, and say in one sentence what that means for any comparison you will make across all three stations.</strong></p>
<div id="aa979f8c" class="cell" data-execution_count="4">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>aq.groupby([<span class="st">'site'</span>, <span class="st">'parameter'</span>])[<span class="st">'value'</span>].count()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>site           parameter
CNSI           pm25         714
Goleta         o3           711
               pm10         517
               pm25         734
Santa Barbara  o3           734
               pm10         766
               pm25         766
Name: value, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>CNSI measures PM2.5 and nothing else</strong>: 714 PM2.5 readings, no ozone and no PM10. Goleta and Santa Barbara each report all three pollutants.</p>
<p>The consequence is that PM2.5 is the only parameter on which all three stations can be compared, and every ozone or PM10 result in the rest of the practice is a two-station result whether or not you say so. Grouping by <code>site</code> will silently return two rows instead of three, and it is your job to notice which one is absent and why.</p>
<p>Note also that the two grouping keys nest: <code>groupby(['site', 'parameter'])</code> gives you one row per combination that actually occurs, so combinations with no data simply do not appear rather than appearing as zero.</p>
</div>
</div>
<p><strong>4. How many readings of each parameter are there across the whole table? Which parameter is the best measured? Which is the worst?</strong></p>
<div id="c0901d4a" class="cell" data-execution_count="5">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>aq.groupby(<span class="st">'parameter'</span>)[<span class="st">'value'</span>].count().sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>parameter
pm25    2214
o3      1445
pm10    1283
Name: value, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>PM2.5 is best measured at 2,214 readings and PM10 worst at 1,283</strong>, with ozone between them at 1,445. PM2.5 leads partly because three stations report it rather than two.</p>
<p>PM10 is short for a second reason as well. Santa Barbara returned 766 PM10 readings and Goleta only 517, although Goleta returned 734 PM2.5 readings over the same month. So roughly 30 per cent of Goleta’s PM10 hours are missing, and that is instrument downtime rather than a station that does not measure PM10 at all. Missing hours are not distributed evenly across stations, which is the sort of thing a count column tells you and a mean column never will.</p>
</div>
</div>
<p><strong>The units check.</strong></p>
<div id="3b4b1c6d" class="cell" data-execution_count="6">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>aq.groupby(<span class="st">'parameter'</span>)[<span class="st">'unit'</span>].nunique()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>parameter
o3      1
pm10    1
pm25    1
Name: unit, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>Each parameter uses exactly <strong>one</strong> unit, which is the reassuring part. The trap is between parameters: ozone is in parts per million and both particulate measures are in micrograms per cubic metre. Averaging a column that mixes 0.03 ppm with 17 µg/m³ produces a number that has no unit and no meaning. Filter to one parameter before you aggregate, every time.</p>
</div>
</div>
</section>
<section id="part-2-compare-the-stations" class="level2">
<h2 class="anchored" data-anchor-id="part-2-compare-the-stations">Part 2: Compare the stations</h2>
<p><strong>5. Build a table of just the PM2.5 readings, ending the line with <code>.copy()</code>, and call it <code>pm25</code>. How many rows?</strong></p>
<div id="8b1a9e22" class="cell" data-execution_count="7">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>pm25 <span class="op">=</span> aq[aq[<span class="st">'parameter'</span>] <span class="op">==</span> <span class="st">'pm25'</span>].copy()</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>pm25.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>(2214, 17)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>2,214 rows and 17 columns</strong>, matching the PM2.5 count from question 4. The column count is unchanged because filtering rows never touches columns. The <code>.copy()</code> matters because everything after this modifies or aggregates <code>pm25</code>, and a copy makes it a table in its own right rather than a view onto <code>aq</code>.</p>
</div>
</div>
<p><strong>6 and 7. Rank the site means, then report count, mean, min, max and standard deviation of PM2.5 at each site.</strong></p>
<div id="794e84f4" class="cell" data-execution_count="8">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>pm25.groupby(<span class="st">'site'</span>)[<span class="st">'value'</span>].mean().sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>site
Goleta           6.480926
Santa Barbara    6.172324
CNSI             6.083473
Name: value, dtype: float64</code></pre>
</div>
</div>
<div id="6fa2b20f" class="cell" data-execution_count="9">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>pm25.groupby(<span class="st">'site'</span>)[<span class="st">'value'</span>].agg([<span class="st">'count'</span>, <span class="st">'mean'</span>, <span class="st">'min'</span>, <span class="st">'max'</span>, <span class="st">'std'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">min</th>
<th data-quarto-table-cell-role="th">max</th>
<th data-quarto-table-cell-role="th">std</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">site</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">CNSI</td>
<td>714</td>
<td>6.083473</td>
<td>3.0</td>
<td>12.0</td>
<td>1.745242</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Goleta</td>
<td>734</td>
<td>6.480926</td>
<td>-4.0</td>
<td>22.0</td>
<td>3.651091</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Santa Barbara</td>
<td>766</td>
<td>6.172324</td>
<td>-1.0</td>
<td>17.0</td>
<td>3.040737</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Goleta is highest at 6.481 µg/m³</strong>, then Santa Barbara at 6.172 and CNSI at 6.083. The full spread across the three stations is 0.397 µg/m³, which is between a tenth and a quarter of one station’s standard deviation: 0.11 of Goleta’s, 0.13 of Santa Barbara’s and 0.23 of CNSI’s. Ranking these three means is technically correct and practically meaningless.</p>
<p>The five-column table is the reason you can say that. The counts are comparable (714 to 766), so no site is being averaged out of a handful of readings, but the standard deviations are not: 3.651 at Goleta, 3.041 at Santa Barbara and 1.745 at CNSI. Adding <code>'count'</code> and <code>'std'</code> to an <code>.agg()</code> list costs you nothing and is what turns a ranking into a judgement about whether the ranking means anything.</p>
</div>
</div>
<p><strong>8. In a markdown cell: The means are nearly identical and the maxima are not. What is different about these three stations, and which of the five columns in your table told you? Would you describe the South Coast as having one air quality or three?</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ A model answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ A model answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>The three stations agree almost exactly on the average hour and disagree completely on the extreme hour. Goleta reaches 22.0 µg/m³, Santa Barbara 17.0 and CNSI only 12.0, and the standard deviations rank the same way, 3.651 against 3.041 against 1.745. The <code>max</code> and <code>std</code> columns held all of the information here; the <code>mean</code> column held none of it.</p>
<p>The typical hour is a regional quantity, so on the mean the South Coast has <strong>one</strong> air quality and the stations are three measurements of it. The excursions are local, and CNSI never records one. Whether that is because the CNSI site is genuinely calmer or because its instrument responds differently is the question you cannot settle from this table, and question 14 is where you have to commit to a hypothesis.</p>
<p>Full marks for naming <code>max</code> or <code>std</code> as the informative column, quoting at least two of the values, and separating the regional signal from the local excursions instead of declaring one station cleanest.</p>
</div>
</div>
<p><strong>9. Now do the same for PM10. Which site is higher, and by how much? Note which site is missing from your answer and why.</strong></p>
<div id="c435b9e2" class="cell" data-execution_count="10">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>pm10 <span class="op">=</span> aq[aq[<span class="st">'parameter'</span>] <span class="op">==</span> <span class="st">'pm10'</span>].copy()</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>pm10.groupby(<span class="st">'site'</span>)[<span class="st">'value'</span>].agg([<span class="st">'count'</span>, <span class="st">'mean'</span>, <span class="st">'max'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">max</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">site</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Goleta</td>
<td>517</td>
<td>14.972921</td>
<td>40.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Santa Barbara</td>
<td>766</td>
<td>17.563969</td>
<td>47.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Santa Barbara is higher, at 17.564 µg/m³ against Goleta’s 14.973</strong>, a difference of 2.591 µg/m³, or about 17 per cent. Santa Barbara’s maximum is also higher, 47.0 against 40.0. Unlike the PM2.5 comparison, this gap is large enough relative to the data to be worth a sentence.</p>
<p><strong>CNSI is missing because it does not measure PM10 at all</strong>, which you established in question 3. The output shows two rows and gives no warning that a third station exists. Silent omission is the ordinary behaviour of <code>groupby</code>: it reports the groups present in the data you handed it, not the groups you were expecting.</p>
<p>Also read the counts before you read the means. Goleta contributes 517 readings against Santa Barbara’s 766, so the two means are averages over different numbers of hours, and Goleta’s missing hours are not a random sample of the month.</p>
</div>
</div>
<p><strong>10. Use the filter pattern and the split-apply-combine pattern together: how many hours did each site record a PM2.5 value above 12 µg/m³, which was the US annual standard until it was tightened to 9 in 2024?</strong></p>
<div id="5daec49e" class="cell" data-execution_count="11">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>pm25[pm25[<span class="st">'value'</span>] <span class="op">&gt;</span> <span class="dv">12</span>].groupby(<span class="st">'site'</span>)[<span class="st">'value'</span>].count()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>site
Goleta           51
Santa Barbara    25
Name: value, dtype: int64</code></pre>
</div>
</div>
<div id="806eed06" class="cell" data-execution_count="12">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>pm25[pm25[<span class="st">'value'</span>] <span class="op">==</span> <span class="dv">12</span>].groupby(<span class="st">'site'</span>)[<span class="st">'value'</span>].count()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>site
CNSI              3
Goleta           11
Santa Barbara    17
Name: value, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Goleta 51 hours and Santa Barbara 25.</strong> CNSI does not appear at all.</p>
<p>The second cell is why this question is worth more than it looks. Goleta and Santa Barbara report PM2.5 as whole micrograms, so readings of exactly 12 are common: 11 at Goleta, 17 at Santa Barbara and 3 at CNSI. Writing <code>&gt;= 12</code> instead of <code>&gt; 12</code> would give 62, 42 and 3, which changes Goleta by a fifth and Santa Barbara by two thirds. When a measurement is reported in whole units and your threshold is a whole number, a large share of the data sits exactly on the boundary, and strict against non-strict stops being a technicality.</p>
<p>One more caution about the framing: 12 µg/m³ was an <strong>annual mean</strong> standard, replaced by 9 in 2024, so counting hours above it is a rough screen for bad hours, not a compliance test. The comparable annual figure here would be the site means from question 6, and all three sites are close to 6.</p>
</div>
</div>
<p><strong>11. In a markdown cell: your answer to question 10 has a site missing from it entirely. Is that because the air there was clean, or for another reason? Look back at your answer to question 7.</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>CNSI is missing, and not because its air was clean.</strong> Its mean of 6.083 µg/m³ is within 0.4 of both other stations, so on a typical hour it measures the same air they do.</p>
<p>It is missing because of the top of its range. CNSI’s maximum for the whole month is exactly <strong>12.0</strong>, and the filter asked for values strictly greater than 12, so its three highest readings were excluded by 0.0. A station whose largest observed value equals your threshold will vanish from a <code>&gt;</code> filter and survive a <code>&gt;=</code> one, and here it is the same three readings deciding it either way.</p>
<p>What that really tells you is what question 7 already showed: CNSI’s standard deviation is 1.745 against Goleta’s 3.651. CNSI does not record extremes, whether or not extremes occurred there. Absence from a threshold count is a statement about the instrument’s range as much as about the air.</p>
</div>
</div>
</section>
<section id="part-3-the-data-still-has-problems" class="level2">
<h2 class="anchored" data-anchor-id="part-3-the-data-still-has-problems">Part 3: The data still has problems</h2>
<p><strong>12 and 13. The minimum PM2.5 at each site, and a count of the negative readings.</strong></p>
<div id="818ee048" class="cell" data-execution_count="13">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>pm25.groupby(<span class="st">'site'</span>)[<span class="st">'value'</span>].<span class="bu">min</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>site
CNSI             3.0
Goleta          -4.0
Santa Barbara   -1.0
Name: value, dtype: float64</code></pre>
</div>
</div>
<div id="3e3d2863" class="cell" data-execution_count="14">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>pm25[pm25[<span class="st">'value'</span>] <span class="op">&lt;</span> <span class="dv">0</span>].groupby(<span class="st">'site'</span>)[<span class="st">'value'</span>].count()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>site
Goleta           11
Santa Barbara     3
Name: value, dtype: int64</code></pre>
</div>
</div>
<div id="3ca80800" class="cell" data-execution_count="15">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>pm25[pm25[<span class="st">'value'</span>] <span class="op">&lt;</span> <span class="dv">0</span>].groupby(<span class="st">'hour'</span>)[<span class="st">'value'</span>].count()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>hour
02    1
04    3
05    6
06    2
08    1
17    1
Name: value, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Goleta 11 negative readings and Santa Barbara 3, out of 2,214.</strong> CNSI has none, and its minimum is 3.0 µg/m³ against Goleta’s -4.0 and Santa Barbara’s -1.0.</p>
<p>The third cell is the useful one. Thirteen of the fourteen negative readings fall between 02:00 and 08:00, with six of them at 05:00, and one lone case at 17:00. The cluster sits exactly at the trough of the daily PM2.5 cycle you will compute in question 21. Negative values are not scattered at random through the month, they cluster in the hours when the true concentration is closest to zero, which is the signature of instrument noise around a small number rather than of a broken sensor.</p>
</div>
</div>
<p><strong>14. In a markdown cell: the site with no negative readings is also the site with the smallest standard deviation and the lowest maximum. Propose one explanation that accounts for all three of those facts at once. Say what you would need to confirm it with this data.</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ A model answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ A model answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>One explanation covers all three facts: CNSI is a different instrument, sited differently, and reporting a smoother quantity. Its readings run from 3.0 to 12.0 with a standard deviation of 1.745, while Goleta ranges from -4.0 to 22.0 with a standard deviation of 3.651. An instrument that averages over a longer window, or sits on a roof rather than at street level, sees the regional background rather than the local plumes, and a series that never approaches zero cannot produce a negative reading, never spikes, and has a small spread. A single instrument difference is one cause with three consequences, which is better than three separate explanations.</p>
<p>There is supporting evidence in the numbers themselves. CNSI reports 73 distinct values in its 714 readings, in steps of 0.1 µg/m³ below 10, while Goleta reports 26 distinct values and Santa Barbara 19, all whole micrograms. The three stations are not running the same measurement pipeline.</p>
<p>To confirm it you would need the station metadata: instrument make and model, the averaging period behind each hourly value, the stated detection limit, the sampling height, and the calibration record. A period of co-located operation, two instruments sampling the same air side by side, would settle it directly. Full marks for one explanation that accounts for all three facts and a specific, obtainable piece of evidence that would test it.</p>
</div>
</div>
<p><strong>15. Would you drop the negative readings before computing site means? Compute both versions and report the difference, then say in one sentence which you would publish and why.</strong></p>
<div id="51da5822" class="cell" data-execution_count="16">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>clean_pm25 <span class="op">=</span> pm25[pm25[<span class="st">'value'</span>] <span class="op">&gt;=</span> <span class="dv">0</span>]</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pm25.groupby(<span class="st">'site'</span>)[<span class="st">'value'</span>].mean())</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(clean_pm25.groupby(<span class="st">'site'</span>)[<span class="st">'value'</span>].mean())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>site
CNSI             6.083473
Goleta           6.480926
Santa Barbara    6.172324
Name: value, dtype: float64
site
CNSI             6.083473
Goleta           6.614108
Santa Barbara    6.200524
Name: value, dtype: float64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ A model answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ A model answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dropping the negatives moves Goleta from 6.481 to 6.614 µg/m³, a rise of 0.133, and Santa Barbara from 6.172 to 6.201, a rise of 0.028. CNSI is unchanged because it had none. The effect is small, about 2 per cent at Goleta, but it is not neutral: every mean went up and none went down, and the gap between the highest and lowest station widened from 0.397 to 0.531.</p>
<p>The asymmetry is the argument against dropping them. A negative PM2.5 reading comes from measurement noise rather than from a data entry error. It is what an instrument reports when the true concentration is near its detection limit and the measurement noise happens to fall on the low side. The matching positive errors are still in the table, indistinguishable from real readings. Removing only the low half of the noise biases the mean upward by construction, and the bias is largest at the station that already reads highest, which is the station you least want to inflate.</p>
<p><strong>I would publish the uncorrected means and state the negatives explicitly</strong>, reporting that 14 of 2,214 readings are below zero, that they cluster in the pre-dawn hours, and that they are noise at the detection limit rather than errors. Full marks for computing both versions, quoting the difference in µg/m³, and giving a reason that refers to what a negative reading is rather than to tidiness.</p>
</div>
</div>
</section>
<section id="part-4-the-question-the-day-was-for" class="level2">
<h2 class="anchored" data-anchor-id="part-4-the-question-the-day-was-for">Part 4: The question the day was for</h2>
<p><strong>16. Build a table of just the ozone readings, ending the line with <code>.copy()</code>, and call it <code>o3</code>. Then group it by <code>hour</code> and report the count and mean of <code>value</code>, in hour order.</strong></p>
<div id="077e0a7f" class="cell" data-execution_count="17">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>o3 <span class="op">=</span> aq[aq[<span class="st">'parameter'</span>] <span class="op">==</span> <span class="st">'o3'</span>].copy()</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>o3.groupby(<span class="st">'hour'</span>)[<span class="st">'value'</span>].agg([<span class="st">'count'</span>, <span class="st">'mean'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="17">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">mean</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">hour</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">00</td>
<td>63</td>
<td>0.016921</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">01</td>
<td>62</td>
<td>0.015935</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">02</td>
<td>30</td>
<td>0.014833</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">03</td>
<td>32</td>
<td>0.015406</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">04</td>
<td>63</td>
<td>0.013333</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">05</td>
<td>63</td>
<td>0.012571</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">06</td>
<td>63</td>
<td>0.011127</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">07</td>
<td>63</td>
<td>0.013270</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">08</td>
<td>63</td>
<td>0.016333</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">09</td>
<td>63</td>
<td>0.020175</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>63</td>
<td>0.023286</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>63</td>
<td>0.026254</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>62</td>
<td>0.028468</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>62</td>
<td>0.030048</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>63</td>
<td>0.030873</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>63</td>
<td>0.030730</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">16</td>
<td>63</td>
<td>0.029587</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">17</td>
<td>63</td>
<td>0.027683</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">18</td>
<td>63</td>
<td>0.025333</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">19</td>
<td>63</td>
<td>0.023063</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">20</td>
<td>63</td>
<td>0.020952</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">21</td>
<td>63</td>
<td>0.019476</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">22</td>
<td>63</td>
<td>0.018016</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">23</td>
<td>63</td>
<td>0.017381</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>A twenty-four row table, one row per hour, with a count and a mean in each.</strong> The counts are close to 62 or 63 for twenty-two of the hours, and the means run from about 0.011 to about 0.031 ppm. Questions 17 to 19 are all readings of this one table, so keep it on screen.</p>
<p>Note that only two stations report ozone, so these counts are roughly two thirds of what the PM2.5 hourly table gave you. Grouping does not warn you that the population changed underneath the numbers, which is what question 17 asks you to notice.</p>
</div>
</div>
<p><strong>17. Read the <code>count</code> column first. Twenty-two of the twenty-four hours have about the same number of readings and two do not. Which two, and what does that tell you about how much weight to put on their means?</strong></p>
<div id="19994d09" class="cell" data-execution_count="18">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>o3.groupby([<span class="st">'hour'</span>, <span class="st">'site'</span>])[<span class="st">'value'</span>].count().head(<span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>hour  site         
00    Goleta           31
      Santa Barbara    32
01    Goleta           30
      Santa Barbara    32
02    Goleta           30
03    Santa Barbara    32
04    Goleta           31
      Santa Barbara    32
Name: value, dtype: int64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Hours <code>'02'</code> and <code>'03'</code>, with 30 and 32 readings against 62 or 63 everywhere else.</strong> Half the usual sample would already be a reason for caution, but the second cell shows something worse: every hour <code>'02'</code> reading is from <strong>Goleta</strong> and every hour <code>'03'</code> reading is from <strong>Santa Barbara</strong>. Each station is missing one hour of every day, and they are missing different ones.</p>
<p>So those two means are single-station means sitting in a column of two-station means. Goleta averages 0.02247 ppm of ozone across the month and Santa Barbara 0.01982, so hour <code>'02'</code> is tilted toward the higher station and hour <code>'03'</code> toward the lower one, and the difference between them tells you nothing about the time of day.</p>
<p>The hour counts are the argument for putting <code>'count'</code> first in every <code>.agg()</code> list. The mean column looked perfectly reasonable at both hours. Only the count showed that two rows of the table were built differently from the other twenty-two.</p>
</div>
</div>
<p><strong>18. Now rank the means. Which hour of the day has the highest average ozone, and which the lowest? What is the ratio between them?</strong></p>
<div id="58f23065" class="cell" data-execution_count="19">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>hourly_o3 <span class="op">=</span> o3.groupby(<span class="st">'hour'</span>)[<span class="st">'value'</span>].mean()</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(hourly_o3.sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">5</span>))</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(hourly_o3.sort_values().head(<span class="dv">5</span>))</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'peak hour:  '</span>, hourly_o3.idxmax())</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'lowest hour:'</span>, hourly_o3.idxmin())</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'ratio:      '</span>, hourly_o3.<span class="bu">max</span>() <span class="op">/</span> hourly_o3.<span class="bu">min</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>hour
14    0.030873
15    0.030730
13    0.030048
16    0.029587
12    0.028468
Name: value, dtype: float64
hour
06    0.011127
05    0.012571
07    0.013270
04    0.013333
02    0.014833
Name: value, dtype: float64
peak hour:   14
lowest hour: 06
ratio:       2.7746077032810277</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Hour <code>'14'</code> is highest at 0.03087 ppm and hour <code>'06'</code> lowest at 0.01113 ppm, a ratio of 2.77.</strong> Ozone is nearly three times as concentrated in the middle of the afternoon as it is at dawn, in the same air, at the same stations, in the same month.</p>
<p>The neighbouring hours agree, which is what makes the result trustworthy. The top five are <code>'14'</code>, <code>'15'</code>, <code>'13'</code>, <code>'16'</code> and <code>'12'</code>, a contiguous afternoon block, and the bottom five are <code>'06'</code>, <code>'05'</code>, <code>'07'</code>, <code>'04'</code> and <code>'02'</code>, which is the pre-dawn stretch with <code>'03'</code> just outside it. Neither extreme is a single odd hour, and neither <code>'14'</code> nor <code>'06'</code> is one of the two hours that question 17 flagged.</p>
<p><code>.idxmax()</code> returns the <strong>label</strong> <code>'14'</code> and not the value, which is what you want: the hour is the answer, and the concentration is a follow-up. The labels are text, so they sort as <code>'00'</code> through <code>'23'</code>, which is exactly hour order because the zeros are padded.</p>
</div>
</div>
<p><strong>19. Look at the full twenty-four-hour table from question 16 again, top to bottom. Describe the shape of the curve in a markdown cell. Where does it start rising, where does it turn over, and where does it stop falling?</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>The curve is a single broad hump with one minimum and one maximum, and no second peak.</p>
<p>It <strong>stops falling at hour <code>'06'</code></strong> (0.01113 ppm), which is the bottom of an overnight decline that has been running since midnight. It <strong>starts rising at <code>'07'</code></strong> and climbs for the next seven hours, slowly at first, fastest around <code>'09'</code> at about 0.004 ppm per hour, then easing to under 0.001 as it approaches the peak, through 0.02018 at <code>'09'</code> and 0.02625 at <code>'11'</code>. It <strong>turns over at <code>'14'</code></strong> (0.03087), holds nearly flat across <code>'13'</code> to <code>'16'</code>, then declines for the rest of the day and through the night at a gentler rate than it rose.</p>
<p>The asymmetry is worth naming: counting from the <code>'06'</code> minimum, the rise takes eight hours and the fall takes the remaining sixteen. The curve is not symmetric about noon: it climbs steeply through the morning and declines slowly through the evening.</p>
</div>
</div>
<p><strong>20. Ground-level ozone is not emitted by anything. It is manufactured in the air out of other pollutants, by sunlight. In three or four sentences, connect that fact to the shape you just described. Does the timing of the peak match what you would expect, and if it is later than you expected, why might that be?</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ A model answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ A model answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>The curve is a production curve, not an emission curve. Nothing releases ozone, so its concentration rises only while sunlight is driving the reactions that build it out of nitrogen oxides and volatile organic compounds, and it falls whenever removal outpaces production. The daily cycle is why the minimum at hour <code>'06'</code> sits at the end of the night, when there has been no sunlight for hours and the overnight chemistry has consumed what was left.</p>
<p>The peak at <code>'14'</code>, about an hour after solar noon, is later than the sun and that is the expected result. Ozone accumulates: each hour of sunlight adds to what the previous hours already made, so the concentration keeps climbing as long as production exceeds loss, and it turns over when those two balance rather than when sunlight is strongest. The morning traffic peak also loads the air with precursors several hours before the reactions have finished converting them.</p>
<p>The long slow evening decline fits the same picture. Production stops at sunset, but the ozone already present is removed only gradually, by deposition to surfaces and reaction with fresh emissions, so it takes most of the night to reach the dawn minimum. A pollutant that was emitted directly would track its sources hour by hour instead; this one follows the total amount of sunlight received so far that day.</p>
</div>
</div>
<p><strong>21. Do the same grouping for PM2.5 and compare. Does particulate matter follow the same daily pattern as ozone?</strong></p>
<div id="7216a5e5" class="cell" data-execution_count="20">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>hourly_pm25 <span class="op">=</span> pm25.groupby(<span class="st">'hour'</span>)[<span class="st">'value'</span>].mean()</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(hourly_pm25.sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">5</span>))</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(hourly_pm25.sort_values().head(<span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>hour
12    7.842391
13    7.678409
14    7.106593
11    7.076344
19    7.055319
Name: value, dtype: float64
hour
05    4.500000
04    4.667045
06    4.696774
07    5.191489
02    5.441758
Name: value, dtype: float64</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>There is a daily cycle in PM2.5, but it is a different shape and much weaker.</strong> The peak is at hour <code>'12'</code> (7.842 µg/m³) and the trough at <code>'05'</code> (4.500), a ratio of 1.74 against ozone’s 2.77.</p>
<p>The top five hours are <code>'12'</code>, <code>'13'</code>, <code>'14'</code>, <code>'11'</code> and <code>'19'</code>, and that last entry is the interesting one. Hours <code>'11'</code> to <code>'14'</code> are a midday block like ozone’s, but <code>'19'</code> at 7.055 is a separate evening rise that has nothing to do with sunlight and would look out of place in the ozone table. PM2.5 has two busy periods per day, ozone has one.</p>
<p>One caveat on the comparison. The PM2.5 hourly means pool all three stations and the ozone means pool only two, and CNSI’s own hourly cycle is markedly shallower than the pooled one, a peak-to-trough ratio of 1.4 against 1.7, so including it damps the pooled PM2.5 amplitude. The gap between the two pollutants is real, but part of its size comes from which stations are in each average.</p>
</div>
</div>
<p><strong>22. In a markdown cell: Which one of these two pollutants has a sharper daily cycle than the other? What does the difference suggest about where each one comes from?</strong></p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ Answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ Answer
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Ozone has the sharper cycle</strong>, a peak-to-trough ratio of 2.77 against 1.74 for PM2.5, and the difference points at the source. Ozone is manufactured on site by a process that runs only in daylight, so its concentration is set almost entirely by the time of day and swings by a factor of nearly three.</p>
<p>PM2.5 is emitted rather than made: by traffic, cooking, wood smoke, sea salt, dust, and any regional smoke drifting in. Some of those sources follow the clock, which is why the midday and evening bumps exist, but a large fraction of the particulate load is background that is present at every hour. A high floor and a moderate peak is the signature of a pollutant with a permanent baseline plus intermittent local additions, and the evening peak at hour <code>'19'</code> with no sunlight to explain it is the clearest evidence that a source rather than a chemical reaction produces it.</p>
</div>
</div>
</section>
<section id="part-5-write-it-up" class="level2">
<h2 class="anchored" data-anchor-id="part-5-write-it-up">Part 5: Write it up</h2>
<p>A strong answer cites at least four numbers computed in the practice, names something genuinely different about CNSI, and states at least one thing a single month cannot settle. Here is one that would earn full marks.</p>
<div class="callout callout-style-default callout-note callout-titled" title="✅ A model answer">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✅ A model answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>On the question as asked, the CNSI monitor adds less than its cost suggests, but it is not redundant either, and the reason matters for what you would do next.</p>
<p>Start with what it duplicates. Averaged over the month, all three stations measure the same air: 6.481 µg/m³ of PM2.5 at Goleta, 6.172 at Santa Barbara and 6.083 at CNSI, a total spread of 0.397 µg/m³ across fifteen kilometres. For the regional average, two stations would have told you what three did. CNSI also measures only PM2.5, in 714 readings, while the other two return ozone and PM10 as well, so it cannot contribute to two of the three parameters at all. On the pollutant with the largest and most policy-relevant daily swing, ozone, which runs from 0.01113 ppm at hour 06 to 0.03087 ppm at hour 14, CNSI reports no ozone at all.</p>
<p>What is genuinely different about it is its behaviour at the extremes. Its standard deviation is 1.745 µg/m³ against Goleta’s 3.651, its month-long maximum is 12.0 against Goleta’s 22.0, and it recorded none of the 14 negative readings that the other two produced near their detection limits. It also reports at 0.1 µg/m³ resolution while the other two report whole micrograms. Either it sits in a genuinely calmer spot, on a roof above street-level plumes, or its instrument responds more slowly than theirs. The two possibilities have opposite implications, and the district should care which is true, because Goleta recorded 51 hours above 12 µg/m³ and CNSI recorded none.</p>
<p>What one month cannot tell them: whether any of it holds outside a single summer. A one-month window contains no winter inversions, no rain, and no wildfire smoke event, which is when the stations would most likely disagree and when a third measurement would be worth most. Before cutting the site, I would ask for a co-located comparison against a reference monitor to settle the instrument question, and a full year of data.</p>
</div>
</div>
</section>
<section id="where-the-marks-are" class="level2">
<h2 class="anchored" data-anchor-id="where-the-marks-are">Where the marks are</h2>
<p>If you compare your notebook against this key, look for these four things before you look at anything else.</p>
<ol type="1">
<li><strong>Every mean you reported has a count beside it.</strong> Question 17 is the whole argument for this habit: the ozone means at hours <code>'02'</code> and <code>'03'</code> looked entirely normal, and only the count column revealed that each was a single station rather than two.</li>
<li><strong>You filtered to one parameter before every average.</strong> Ozone is in ppm and the particulates in µg/m³, so any mean taken across the <code>parameter</code> column produces a number that has no unit.</li>
<li><strong>Your question 10 answer treats the boundary explicitly.</strong> CNSI’s maximum is exactly 12.0 and the filter asked for values above 12, so a station disappeared from the result by 0.0. With <code>&gt;=</code> instead, Goleta goes from 51 hours to 62 and Santa Barbara from 25 to 42.</li>
<li><strong>Your interpretation answers say what the number means, not what it is.</strong> “Goleta has the highest mean” restates the output. “Goleta is highest by 0.397 µg/m³, a fraction of the standard deviation at every station, so the ranking means nothing” reads it.</li>
</ol>
<p>⬅️ Back to <a href="../../course-materials/eod-practice/eod-day5-2026.html">the exercise</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><img src="../../images/bren-logo.png" alt="The Bren School of Environmental Science &amp; Management logo" width="250"></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This website is built with <a href="https://github.com/EDS-217-Essential-Python/EDS-217-Essential-Python.github.io"><i class="fa-brands fa-github" title="the github octocat logo" aria-label="github"></i></a> and <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>